export type FamilienduellCategory = 'alltag' | 'essen' | 'familie';

export type FamilienduellAnswer = {
  text: string;
  points: number;
};

export type FamilienduellQuestion = {
  id: string;
  category: FamilienduellCategory;
  question: string;
  /** Immer 5 Antworten, absteigend nach Punkten sortiert, Summe = 100. */
  answers: FamilienduellAnswer[];
};

export const familienduellCategoryLabels: Record<FamilienduellCategory, string> = {
  alltag: 'Alltag & Allgemeinwissen',
  essen: 'Essen & Trinken',
  familie: 'Familie & Freizeit',
};

export const familienduellQuestions: FamilienduellQuestion[] = [
  // ─── Alltag & Allgemeinwissen ───
  {
    id: 'alltag-1',
    category: 'alltag',
    question: 'Was nimmt man mit an den Strand?',
    answers: [
      { text: 'Sonnencreme', points: 35 },
      { text: 'Handtuch', points: 25 },
      { text: 'Sonnenschirm', points: 15 },
      { text: 'Buch', points: 15 },
      { text: 'Getränke', points: 10 },
    ],
  },
  {
    id: 'alltag-2',
    category: 'alltag',
    question: 'Was macht man als Erstes am Morgen?',
    answers: [
      { text: 'Handy checken', points: 30 },
      { text: 'Duschen', points: 25 },
      { text: 'Kaffee/Frühstück machen', points: 20 },
      { text: 'Wecker ausschalten', points: 15 },
      { text: 'Zähne putzen', points: 10 },
    ],
  },
  {
    id: 'alltag-3',
    category: 'alltag',
    question: 'Welchen Beruf wollten viele Kinder früher werden?',
    answers: [
      { text: 'Feuerwehrmann/-frau', points: 30 },
      { text: 'Arzt/Ärztin', points: 25 },
      { text: 'Astronaut/in', points: 20 },
      { text: 'Fußballprofi', points: 15 },
      { text: 'Polizist/in', points: 10 },
    ],
  },
  {
    id: 'alltag-4',
    category: 'alltag',
    question: 'Was vergisst man am häufigsten, wenn man das Haus verlässt?',
    answers: [
      { text: 'Schlüssel', points: 30 },
      { text: 'Handy', points: 25 },
      { text: 'Portemonnaie', points: 20 },
      { text: 'Sonnenbrille', points: 15 },
      { text: 'Regenschirm', points: 10 },
    ],
  },
  {
    id: 'alltag-5',
    category: 'alltag',
    question: 'Womit verbringen Menschen zu viel Zeit?',
    answers: [
      { text: 'Handy/Social Media', points: 35 },
      { text: 'Fernsehen', points: 25 },
      { text: 'Arbeit', points: 20 },
      { text: 'Serien streamen', points: 12 },
      { text: 'Zocken', points: 8 },
    ],
  },
  {
    id: 'alltag-6',
    category: 'alltag',
    question: 'Was macht man, wenn man nicht einschlafen kann?',
    answers: [
      { text: 'Handy nutzen', points: 30 },
      { text: 'Aufstehen/etwas trinken', points: 20 },
      { text: 'Schäfchen zählen', points: 20 },
      { text: 'Buch lesen', points: 18 },
      { text: 'Musik/Podcast hören', points: 12 },
    ],
  },
  {
    id: 'alltag-7',
    category: 'alltag',
    question: 'Welchen Ort besucht man oft im Urlaub?',
    answers: [
      { text: 'Strand', points: 30 },
      { text: 'Berge', points: 22 },
      { text: 'Stadt/Sightseeing', points: 20 },
      { text: 'See', points: 15 },
      { text: 'Freizeitpark', points: 13 },
    ],
  },
  {
    id: 'alltag-8',
    category: 'alltag',
    question: 'Was tut man an einem verregneten Tag?',
    answers: [
      { text: 'Zuhause bleiben/Netflix', points: 30 },
      { text: 'Lesen', points: 20 },
      { text: 'Spiele spielen', points: 18 },
      { text: 'Schlafen', points: 17 },
      { text: 'Kochen/Backen', points: 15 },
    ],
  },
  {
    id: 'alltag-9',
    category: 'alltag',
    question: 'Wobei verliert man am ehesten die Geduld?',
    answers: [
      { text: 'Im Stau', points: 30 },
      { text: 'Beim Warten in der Schlange/Amt', points: 25 },
      { text: 'Bei langsamem Internet/PC', points: 20 },
      { text: 'Bei Technikproblemen', points: 15 },
      { text: 'Beim Möbelaufbauen', points: 10 },
    ],
  },
  {
    id: 'alltag-10',
    category: 'alltag',
    question: 'Was tut man, um sich zu entspannen?',
    answers: [
      { text: 'Fernsehen/Serien schauen', points: 28 },
      { text: 'Musik hören', points: 22 },
      { text: 'Spazieren gehen', points: 20 },
      { text: 'Baden/Duschen', points: 15 },
      { text: 'Sport machen', points: 15 },
    ],
  },

  // ─── Essen & Trinken ───
  {
    id: 'essen-1',
    category: 'essen',
    question: 'Was gehört auf eine klassische Pizza Margherita?',
    answers: [
      { text: 'Tomatensoße', points: 30 },
      { text: 'Käse/Mozzarella', points: 28 },
      { text: 'Basilikum', points: 22 },
      { text: 'Olivenöl', points: 12 },
      { text: 'Oregano', points: 8 },
    ],
  },
  {
    id: 'essen-2',
    category: 'essen',
    question: 'Was trinkt man morgens am liebsten?',
    answers: [
      { text: 'Kaffee', points: 40 },
      { text: 'Tee', points: 25 },
      { text: 'Orangensaft', points: 15 },
      { text: 'Wasser', points: 12 },
      { text: 'Kakao', points: 8 },
    ],
  },
  {
    id: 'essen-3',
    category: 'essen',
    question: 'Welches Gericht bestellt man oft beim Italiener?',
    answers: [
      { text: 'Pizza', points: 35 },
      { text: 'Pasta/Spaghetti', points: 30 },
      { text: 'Lasagne', points: 15 },
      { text: 'Tiramisu', points: 10 },
      { text: 'Bruschetta', points: 10 },
    ],
  },
  {
    id: 'essen-4',
    category: 'essen',
    question: 'Was isst man klassisch zu Weihnachten?',
    answers: [
      { text: 'Gans/Ente', points: 28 },
      { text: 'Kartoffelsalat mit Würstchen', points: 25 },
      { text: 'Raclette/Fondue', points: 20 },
      { text: 'Plätzchen', points: 15 },
      { text: 'Braten', points: 12 },
    ],
  },
  {
    id: 'essen-5',
    category: 'essen',
    question: 'Welcher Snack darf im Kino nicht fehlen?',
    answers: [
      { text: 'Popcorn', points: 40 },
      { text: 'Nachos', points: 20 },
      { text: 'Cola/Getränk', points: 18 },
      { text: 'Gummibärchen', points: 12 },
      { text: 'Eis', points: 10 },
    ],
  },
  {
    id: 'essen-6',
    category: 'essen',
    question: 'Was legt man klassisch auf ein Butterbrot?',
    answers: [
      { text: 'Marmelade', points: 25 },
      { text: 'Käse', points: 22 },
      { text: 'Wurst/Schinken', points: 22 },
      { text: 'Nutella', points: 20 },
      { text: 'Honig', points: 11 },
    ],
  },
  {
    id: 'essen-7',
    category: 'essen',
    question: 'Welches Gemüse mögen Kinder am wenigsten?',
    answers: [
      { text: 'Rosenkohl', points: 28 },
      { text: 'Spinat', points: 24 },
      { text: 'Brokkoli', points: 20 },
      { text: 'Aubergine', points: 16 },
      { text: 'Rote Bete', points: 12 },
    ],
  },
  {
    id: 'essen-8',
    category: 'essen',
    question: 'Was trinkt man an einem heißen Sommertag?',
    answers: [
      { text: 'Wasser', points: 30 },
      { text: 'Eistee', points: 22 },
      { text: 'Limonade', points: 20 },
      { text: 'Bier', points: 16 },
      { text: 'Cocktail', points: 12 },
    ],
  },
  {
    id: 'essen-9',
    category: 'essen',
    question: 'Womit isst man Pommes am liebsten?',
    answers: [
      { text: 'Ketchup', points: 35 },
      { text: 'Mayonnaise', points: 30 },
      { text: 'Currysauce', points: 18 },
      { text: 'Mayo-Ketchup gemischt', points: 10 },
      { text: 'Ranch/Kräuterdip', points: 7 },
    ],
  },
  {
    id: 'essen-10',
    category: 'essen',
    question: 'Was gehört zu einem klassischen Frühstück?',
    answers: [
      { text: 'Brötchen', points: 28 },
      { text: 'Ei', points: 24 },
      { text: 'Müsli', points: 20 },
      { text: 'Marmelade/Aufstrich', points: 16 },
      { text: 'Kaffee', points: 12 },
    ],
  },

  // ─── Familie & Freizeit ───
  {
    id: 'familie-1',
    category: 'familie',
    question: 'Was macht eine Familie am liebsten am Wochenende?',
    answers: [
      { text: 'Ausflug/Spaziergang', points: 28 },
      { text: 'Ausschlafen', points: 24 },
      { text: 'Zusammen kochen/essen', points: 20 },
      { text: 'Filme schauen', points: 16 },
      { text: 'Sport machen', points: 12 },
    ],
  },
  {
    id: 'familie-2',
    category: 'familie',
    question: 'Welches Spiel spielt man oft auf Familienfeiern?',
    answers: [
      { text: 'Kartenspiele (z.B. Uno)', points: 30 },
      { text: 'Mensch ärgere dich nicht', points: 26 },
      { text: 'Werwolf/Gesellschaftsspiele', points: 18 },
      { text: 'Tabu', points: 14 },
      { text: 'Activity', points: 12 },
    ],
  },
  {
    id: 'familie-3',
    category: 'familie',
    question: 'Wohin geht man gerne mit der Familie im Sommer?',
    answers: [
      { text: 'Schwimmbad', points: 30 },
      { text: 'Freizeitpark', points: 24 },
      { text: 'See/Strand', points: 22 },
      { text: 'Grillen im Garten', points: 14 },
      { text: 'Zoo', points: 10 },
    ],
  },
  {
    id: 'familie-4',
    category: 'familie',
    question: 'Was schenkt man gern zum Geburtstag?',
    answers: [
      { text: 'Geld', points: 28 },
      { text: 'Gutschein', points: 24 },
      { text: 'Buch', points: 16 },
      { text: 'Süßigkeiten/Pralinen', points: 16 },
      { text: 'Blumen', points: 16 },
    ],
  },
  {
    id: 'familie-5',
    category: 'familie',
    question: 'Wobei streiten sich Geschwister am häufigsten?',
    answers: [
      { text: 'Fernbedienung/TV-Programm', points: 28 },
      { text: 'Handy/Tablet', points: 24 },
      { text: 'Wer zuerst duschen darf', points: 20 },
      { text: 'Aufräumen', points: 16 },
      { text: 'Süßigkeiten teilen', points: 12 },
    ],
  },
  {
    id: 'familie-6',
    category: 'familie',
    question: 'Was braucht man für einen gelungenen Familienausflug?',
    answers: [
      { text: 'Gute Laune', points: 24 },
      { text: 'Essen & Getränke', points: 24 },
      { text: 'Auto/Verkehrsmittel', points: 20 },
      { text: 'Sonnencreme', points: 16 },
      { text: 'Spiele/Beschäftigung', points: 16 },
    ],
  },
  {
    id: 'familie-7',
    category: 'familie',
    question: 'Welches Haustier wünschen sich Kinder am meisten?',
    answers: [
      { text: 'Hund', points: 35 },
      { text: 'Katze', points: 28 },
      { text: 'Kaninchen/Hase', points: 15 },
      { text: 'Hamster', points: 12 },
      { text: 'Pferd', points: 10 },
    ],
  },
  {
    id: 'familie-8',
    category: 'familie',
    question: 'Was macht man an einem gemütlichen Abend zuhause?',
    answers: [
      { text: 'Fernsehen/Serie schauen', points: 30 },
      { text: 'Gesellschaftsspiel spielen', points: 22 },
      { text: 'Lesen', points: 18 },
      { text: 'Kochen/Backen', points: 16 },
      { text: 'Kuscheln/Reden', points: 14 },
    ],
  },
  {
    id: 'familie-9',
    category: 'familie',
    question: 'Welche Ausrede nutzen Kinder, um länger aufzubleiben?',
    answers: [
      { text: '"Ich bin noch nicht müde"', points: 28 },
      { text: 'Noch ein Glas Wasser', points: 22 },
      { text: 'Auf die Toilette müssen', points: 20 },
      { text: 'Noch eine Geschichte', points: 18 },
      { text: 'Angst im Dunkeln', points: 12 },
    ],
  },
  {
    id: 'familie-10',
    category: 'familie',
    question: 'Was vergisst man oft beim Packen für den Familienurlaub?',
    answers: [
      { text: 'Ladekabel', points: 26 },
      { text: 'Zahnbürste', points: 22 },
      { text: 'Sonnencreme', points: 20 },
      { text: 'Medikamente', points: 18 },
      { text: 'Lieblingskuscheltier', points: 14 },
    ],
  },

  // ─── Alltag & Allgemeinwissen (Teil 2) ───
  {
    id: 'alltag-11',
    category: 'alltag',
    question: 'Womit vertreibt man sich die Zeit im Wartezimmer?',
    answers: [
      { text: 'Handy', points: 35 },
      { text: 'Zeitschrift lesen', points: 25 },
      { text: 'Mit anderen reden', points: 15 },
      { text: 'Dösen/Nichts tun', points: 15 },
      { text: 'Nervös sein', points: 10 },
    ],
  },
  {
    id: 'alltag-12',
    category: 'alltag',
    question: 'Welches Geräusch nervt am meisten?',
    answers: [
      { text: 'Baustellenlärm', points: 28 },
      { text: 'Weckerklingeln', points: 22 },
      { text: 'Quietschende Tür', points: 20 },
      { text: 'Schnarchen', points: 18 },
      { text: 'Handy-Vibrieren', points: 12 },
    ],
  },
  {
    id: 'alltag-13',
    category: 'alltag',
    question: 'Welche App nutzt man täglich am meisten?',
    answers: [
      { text: 'WhatsApp', points: 32 },
      { text: 'Instagram', points: 24 },
      { text: 'YouTube', points: 20 },
      { text: 'E-Mail', points: 14 },
      { text: 'TikTok', points: 10 },
    ],
  },
  {
    id: 'alltag-14',
    category: 'alltag',
    question: 'Was tut man, wenn das Internet ausfällt?',
    answers: [
      { text: 'Handy-Daten nutzen', points: 28 },
      { text: 'WLAN vom Nachbarn suchen', points: 22 },
      { text: 'Buch lesen', points: 20 },
      { text: 'Spazieren gehen', points: 18 },
      { text: 'Genervt warten', points: 12 },
    ],
  },
  {
    id: 'alltag-15',
    category: 'alltag',
    question: 'Welches Fortbewegungsmittel nutzt man in der Stadt?',
    answers: [
      { text: 'Auto', points: 30 },
      { text: 'Fahrrad', points: 26 },
      { text: 'Bus/Bahn', points: 24 },
      { text: 'Zu Fuß', points: 12 },
      { text: 'E-Scooter', points: 8 },
    ],
  },
  {
    id: 'alltag-16',
    category: 'alltag',
    question: 'Was möchte man im Urlaub am liebsten gar nicht tun?',
    answers: [
      { text: 'Arbeiten/E-Mails checken', points: 30 },
      { text: 'Früh aufstehen', points: 26 },
      { text: 'Kochen', points: 18 },
      { text: 'Aufräumen', points: 16 },
      { text: 'Sport machen', points: 10 },
    ],
  },
  {
    id: 'alltag-17',
    category: 'alltag',
    question: 'Wobei schaut man am häufigsten aufs Handy?',
    answers: [
      { text: 'Beim Warten', points: 28 },
      { text: 'Vorm Einschlafen', points: 24 },
      { text: 'Beim Essen', points: 20 },
      { text: 'Auf der Toilette', points: 16 },
      { text: 'Beim Fernsehen', points: 12 },
    ],
  },
  {
    id: 'alltag-18',
    category: 'alltag',
    question: 'Was braucht man unbedingt im Büro?',
    answers: [
      { text: 'Kaffee', points: 30 },
      { text: 'Laptop/PC', points: 26 },
      { text: 'Ruhe/Kopfhörer', points: 18 },
      { text: 'Ordnung am Schreibtisch', points: 14 },
      { text: 'Pflanzen', points: 12 },
    ],
  },
  {
    id: 'alltag-19',
    category: 'alltag',
    question: 'Welchen Ort besucht man an einem freien Tag?',
    answers: [
      { text: 'Café', points: 26 },
      { text: 'Museum', points: 22 },
      { text: 'Park', points: 22 },
      { text: 'Einkaufszentrum', points: 16 },
      { text: 'Kino', points: 14 },
    ],
  },
  {
    id: 'alltag-20',
    category: 'alltag',
    question: 'Was macht man zuerst nach dem Aufwachen im Urlaub?',
    answers: [
      { text: 'Ausschlafen genießen', points: 30 },
      { text: 'Frühstücken', points: 24 },
      { text: 'Ans Meer/an den Pool gehen', points: 22 },
      { text: 'Handy checken', points: 14 },
      { text: 'Duschen', points: 10 },
    ],
  },

  // ─── Essen & Trinken (Teil 2) ───
  {
    id: 'essen-11',
    category: 'essen',
    question: 'Welches Gewürz darf in der Küche nicht fehlen?',
    answers: [
      { text: 'Salz', points: 32 },
      { text: 'Pfeffer', points: 26 },
      { text: 'Paprika', points: 18 },
      { text: 'Knoblauch', points: 14 },
      { text: 'Curry', points: 10 },
    ],
  },
  {
    id: 'essen-12',
    category: 'essen',
    question: 'Was isst man typischerweise beim Grillen?',
    answers: [
      { text: 'Bratwurst', points: 30 },
      { text: 'Steak', points: 24 },
      { text: 'Grillkäse', points: 18 },
      { text: 'Maiskolben', points: 16 },
      { text: 'Stockbrot', points: 12 },
    ],
  },
  {
    id: 'essen-13',
    category: 'essen',
    question: 'Welches Getränk trinkt man auf einer Party?',
    answers: [
      { text: 'Bier', points: 30 },
      { text: 'Sekt/Prosecco', points: 24 },
      { text: 'Cocktails', points: 20 },
      { text: 'Wasser', points: 14 },
      { text: 'Limo/Softdrinks', points: 12 },
    ],
  },
  {
    id: 'essen-14',
    category: 'essen',
    question: 'Was bringt man mit zu einer Grillparty?',
    answers: [
      { text: 'Fleisch/Würstchen', points: 28 },
      { text: 'Salat', points: 24 },
      { text: 'Getränke', points: 22 },
      { text: 'Chips/Snacks', points: 14 },
      { text: 'Dessert', points: 12 },
    ],
  },
  {
    id: 'essen-15',
    category: 'essen',
    question: 'Welche Süßigkeit kauft man sich im Kino?',
    answers: [
      { text: 'Gummibärchen', points: 28 },
      { text: 'Schokolade', points: 24 },
      { text: 'Popcorn', points: 22 },
      { text: 'Lakritz', points: 14 },
      { text: 'Kaubonbons', points: 12 },
    ],
  },
  {
    id: 'essen-16',
    category: 'essen',
    question: 'Was isst man am Sonntagmorgen?',
    answers: [
      { text: 'Frühstücksei', points: 24 },
      { text: 'Brötchen', points: 24 },
      { text: 'Pancakes/Waffeln', points: 22 },
      { text: 'Müsli', points: 16 },
      { text: 'Croissant', points: 14 },
    ],
  },
  {
    id: 'essen-17',
    category: 'essen',
    question: 'Welches Fastfood bestellt man am liebsten?',
    answers: [
      { text: 'Burger', points: 32 },
      { text: 'Döner', points: 26 },
      { text: 'Pizza', points: 20 },
      { text: 'Pommes', points: 14 },
      { text: 'Chicken Nuggets', points: 8 },
    ],
  },
  {
    id: 'essen-18',
    category: 'essen',
    question: 'Was trinkt man am liebsten zum Essen?',
    answers: [
      { text: 'Wasser', points: 30 },
      { text: 'Wein', points: 24 },
      { text: 'Cola/Softdrink', points: 22 },
      { text: 'Bier', points: 14 },
      { text: 'Saft', points: 10 },
    ],
  },
  {
    id: 'essen-19',
    category: 'essen',
    question: 'Welches Land hat aus deutscher Sicht die beliebteste Küche?',
    answers: [
      { text: 'Italien', points: 30 },
      { text: 'Deutschland', points: 22 },
      { text: 'Griechenland', points: 18 },
      { text: 'Türkei', points: 16 },
      { text: 'Asien allgemein', points: 14 },
    ],
  },
  {
    id: 'essen-20',
    category: 'essen',
    question: 'Was kocht man, wenn Freunde zu Besuch kommen?',
    answers: [
      { text: 'Pasta', points: 26 },
      { text: 'Gegrilltes', points: 24 },
      { text: 'Salat/Vorspeisen', points: 20 },
      { text: 'Auflauf', points: 16 },
      { text: 'Fingerfood', points: 14 },
    ],
  },

  // ─── Familie & Freizeit (Teil 2) ───
  {
    id: 'familie-11',
    category: 'familie',
    question: 'Was macht man mit den Großeltern am liebsten?',
    answers: [
      { text: 'Kaffee trinken/backen', points: 28 },
      { text: 'Geschichten erzählen', points: 24 },
      { text: 'Spazieren gehen', points: 22 },
      { text: 'Spielen', points: 16 },
      { text: 'Fernsehen', points: 10 },
    ],
  },
  {
    id: 'familie-12',
    category: 'familie',
    question: 'Welches Hobby betreibt die Familie gemeinsam?',
    answers: [
      { text: 'Wandern', points: 26 },
      { text: 'Radfahren', points: 24 },
      { text: 'Kochen/Backen', points: 22 },
      { text: 'Gesellschaftsspiele', points: 16 },
      { text: 'Sport', points: 12 },
    ],
  },
  {
    id: 'familie-13',
    category: 'familie',
    question: 'Was packt man für einen Familienausflug in den Park ein?',
    answers: [
      { text: 'Picknickdecke', points: 26 },
      { text: 'Essen/Getränke', points: 24 },
      { text: 'Ball/Spielzeug', points: 22 },
      { text: 'Sonnencreme', points: 16 },
      { text: 'Regenschirm', points: 12 },
    ],
  },
  {
    id: 'familie-14',
    category: 'familie',
    question: 'Welche Tradition pflegt die Familie an Weihnachten?',
    answers: [
      { text: 'Geschenke auspacken', points: 30 },
      { text: 'Gemeinsam kochen', points: 24 },
      { text: 'Weihnachtsbaum schmücken', points: 20 },
      { text: 'Kirche besuchen', points: 14 },
      { text: 'Plätzchen backen', points: 12 },
    ],
  },
  {
    id: 'familie-15',
    category: 'familie',
    question: 'Worüber streiten sich Eltern und Kinder am häufigsten?',
    answers: [
      { text: 'Handyzeit', points: 30 },
      { text: 'Hausaufgaben', points: 24 },
      { text: 'Zimmer aufräumen', points: 20 },
      { text: 'Schlafenszeit', points: 16 },
      { text: 'Süßigkeiten', points: 10 },
    ],
  },
  {
    id: 'familie-16',
    category: 'familie',
    question: 'Wohin fährt die Familie am liebsten in den Urlaub?',
    answers: [
      { text: 'Ans Meer', points: 32 },
      { text: 'In die Berge', points: 24 },
      { text: 'Ins Ausland/Städtereise', points: 20 },
      { text: 'Campingplatz', points: 14 },
      { text: 'Zu Verwandten', points: 10 },
    ],
  },
  {
    id: 'familie-17',
    category: 'familie',
    question: 'Was braucht ein Kind unbedingt im Kinderzimmer?',
    answers: [
      { text: 'Bett', points: 24 },
      { text: 'Spielzeug', points: 24 },
      { text: 'Schreibtisch', points: 20 },
      { text: 'Kuscheltier', points: 18 },
      { text: 'Bücherregal', points: 14 },
    ],
  },
  {
    id: 'familie-18',
    category: 'familie',
    question: 'Was macht man am Geburtstag eines Familienmitglieds?',
    answers: [
      { text: 'Kuchen backen', points: 28 },
      { text: 'Geschenke überreichen', points: 26 },
      { text: 'Feiern/Party machen', points: 20 },
      { text: 'Lieblingsessen kochen', points: 16 },
      { text: 'Anrufen/Gratulieren', points: 10 },
    ],
  },
  {
    id: 'familie-19',
    category: 'familie',
    question: 'Welchen Film schaut die ganze Familie zusammen?',
    answers: [
      { text: 'Disney/Animationsfilm', points: 30 },
      { text: 'Komödie', points: 24 },
      { text: 'Actionfilm', points: 18 },
      { text: 'Weihnachtsfilm', points: 16 },
      { text: 'Dokumentation', points: 12 },
    ],
  },
  {
    id: 'familie-20',
    category: 'familie',
    question: 'Was tut man an einem Familien-Spieleabend?',
    answers: [
      { text: 'Brettspiele spielen', points: 30 },
      { text: 'Kartenspiele spielen', points: 24 },
      { text: 'Snacks essen', points: 20 },
      { text: 'Musik hören', points: 14 },
      { text: 'Lachen/Quatschen', points: 12 },
    ],
  },

  // ─── Alltag & Allgemeinwissen (Teil 3) ───
  {
    id: 'alltag-21',
    category: 'alltag',
    question: 'Was macht man, bevor man das Haus verlässt?',
    answers: [
      { text: 'Spiegel checken', points: 28 },
      { text: 'Schlüssel/Handy einstecken', points: 26 },
      { text: 'Licht ausschalten', points: 20 },
      { text: 'Tür abschließen', points: 16 },
      { text: 'Wetter checken', points: 10 },
    ],
  },
  {
    id: 'alltag-22',
    category: 'alltag',
    question: 'Welchen Feiertag mögen die meisten Menschen am liebsten?',
    answers: [
      { text: 'Weihnachten', points: 32 },
      { text: 'Silvester', points: 24 },
      { text: 'Ostern', points: 18 },
      { text: 'Eigener Geburtstag', points: 16 },
      { text: 'Karneval', points: 10 },
    ],
  },
  {
    id: 'alltag-23',
    category: 'alltag',
    question: 'Was tut man an einem freien Sonntag?',
    answers: [
      { text: 'Ausschlafen', points: 30 },
      { text: 'Spazieren gehen', points: 24 },
      { text: 'Zeitung lesen', points: 18 },
      { text: 'Familie besuchen', points: 16 },
      { text: 'Faulenzen', points: 12 },
    ],
  },
  {
    id: 'alltag-24',
    category: 'alltag',
    question: 'Welches Wetter mögen die meisten Menschen am liebsten?',
    answers: [
      { text: 'Sonnenschein', points: 35 },
      { text: 'Leichte Wärme/Frühlingswetter', points: 24 },
      { text: 'Schnee', points: 18 },
      { text: 'Gewitter (gut zum Schlafen)', points: 13 },
      { text: 'Wind', points: 10 },
    ],
  },
  {
    id: 'alltag-25',
    category: 'alltag',
    question: 'Was macht man, wenn man krank zu Hause ist?',
    answers: [
      { text: 'Schlafen', points: 28 },
      { text: 'Tee trinken', points: 24 },
      { text: 'Fernsehen/Serien schauen', points: 20 },
      { text: 'Suppe essen', points: 16 },
      { text: 'Arzt anrufen', points: 12 },
    ],
  },
  {
    id: 'alltag-26',
    category: 'alltag',
    question: 'Welches Fach mochten die meisten in der Schule am wenigsten?',
    answers: [
      { text: 'Mathe', points: 32 },
      { text: 'Chemie', points: 22 },
      { text: 'Physik', points: 18 },
      { text: 'Latein', points: 16 },
      { text: 'Sport', points: 12 },
    ],
  },
  {
    id: 'alltag-27',
    category: 'alltag',
    question: 'Was braucht man für einen Umzug?',
    answers: [
      { text: 'Kartons', points: 28 },
      { text: 'Freunde zum Helfen', points: 24 },
      { text: 'Klebeband', points: 18 },
      { text: 'Transporter', points: 16 },
      { text: 'Geduld', points: 14 },
    ],
  },
  {
    id: 'alltag-28',
    category: 'alltag',
    question: 'Welchen Gegenstand verlegt man am häufigsten zu Hause?',
    answers: [
      { text: 'Fernbedienung', points: 30 },
      { text: 'Brille', points: 24 },
      { text: 'Handy', points: 20 },
      { text: 'Schlüssel', points: 16 },
      { text: 'Ladekabel', points: 10 },
    ],
  },
  {
    id: 'alltag-29',
    category: 'alltag',
    question: 'Was macht man am liebsten in den Ferien?',
    answers: [
      { text: 'Ausschlafen', points: 28 },
      { text: 'Verreisen', points: 26 },
      { text: 'Freunde treffen', points: 20 },
      { text: 'Nichts tun', points: 16 },
      { text: 'Zocken', points: 10 },
    ],
  },
  {
    id: 'alltag-30',
    category: 'alltag',
    question: 'Welches Tier hätten die meisten gern als Haustier?',
    answers: [
      { text: 'Hund', points: 34 },
      { text: 'Katze', points: 26 },
      { text: 'Pferd', points: 16 },
      { text: 'Vogel', points: 14 },
      { text: 'Fisch', points: 10 },
    ],
  },
  {
    id: 'alltag-31',
    category: 'alltag',
    question: 'Was tut man, um Geld zu sparen?',
    answers: [
      { text: 'Weniger einkaufen gehen', points: 26 },
      { text: 'Sparbuch/Sparschwein', points: 24 },
      { text: 'Angebote nutzen', points: 20 },
      { text: 'Selbst kochen statt Restaurant', points: 18 },
      { text: 'Second-Hand kaufen', points: 12 },
    ],
  },
  {
    id: 'alltag-32',
    category: 'alltag',
    question: 'Welche Ausrede nutzt man fürs Zuspätkommen?',
    answers: [
      { text: 'Verkehr/Stau', points: 30 },
      { text: 'Wecker nicht gehört', points: 24 },
      { text: 'Verspätung bei Bus/Bahn', points: 20 },
      { text: 'Etwas nicht wiedergefunden', points: 14 },
      { text: 'Falsch geplant', points: 12 },
    ],
  },
  {
    id: 'alltag-33',
    category: 'alltag',
    question: 'Was macht man beim Warten auf den Bus/die Bahn?',
    answers: [
      { text: 'Handy nutzen', points: 32 },
      { text: 'Musik hören', points: 22 },
      { text: 'Nachdenken/Tagträumen', points: 18 },
      { text: 'Mit anderen reden', points: 16 },
      { text: 'Zeitung/Buch lesen', points: 12 },
    ],
  },
  {
    id: 'alltag-34',
    category: 'alltag',
    question: 'Welchen Beruf respektiert man besonders?',
    answers: [
      { text: 'Arzt/Ärztin', points: 28 },
      { text: 'Feuerwehrmann/-frau', points: 24 },
      { text: 'Lehrer/in', points: 20 },
      { text: 'Polizist/in', points: 16 },
      { text: 'Krankenpfleger/in', points: 12 },
    ],
  },
  {
    id: 'alltag-35',
    category: 'alltag',
    question: 'Was tut man an einem Sonntagabend?',
    answers: [
      { text: 'Für die Woche vorbereiten', points: 26 },
      { text: 'Fernsehen', points: 24 },
      { text: 'Früh schlafen gehen', points: 20 },
      { text: 'Wäsche waschen', points: 16 },
      { text: 'Ausruhen', points: 14 },
    ],
  },
  {
    id: 'alltag-36',
    category: 'alltag',
    question: 'Welches Fortbewegungsmittel benutzt man für lange Reisen?',
    answers: [
      { text: 'Flugzeug', points: 34 },
      { text: 'Auto', points: 26 },
      { text: 'Zug', points: 22 },
      { text: 'Bus', points: 10 },
      { text: 'Schiff', points: 8 },
    ],
  },
  {
    id: 'alltag-37',
    category: 'alltag',
    question: 'Was macht man, wenn man gestresst ist?',
    answers: [
      { text: 'Durchatmen/Pause machen', points: 26 },
      { text: 'Spazieren gehen', points: 22 },
      { text: 'Musik hören', points: 20 },
      { text: 'Sport machen', points: 18 },
      { text: 'Mit jemandem reden', points: 14 },
    ],
  },
  {
    id: 'alltag-38',
    category: 'alltag',
    question: 'Welchen Ort meidet man an einem Sonntag?',
    answers: [
      { text: 'Supermarkt (geschlossen)', points: 26 },
      { text: 'Behörden/Amt', points: 24 },
      { text: 'Stadtzentrum (Menschenmenge)', points: 20 },
      { text: 'Arbeit/Büro', points: 18 },
      { text: 'Baumarkt', points: 12 },
    ],
  },
  {
    id: 'alltag-39',
    category: 'alltag',
    question: 'Was braucht man unbedingt im Auto?',
    answers: [
      { text: 'Navigationssystem/Handy', points: 26 },
      { text: 'Musik', points: 24 },
      { text: 'Wasser/Snacks', points: 20 },
      { text: 'Ladekabel', points: 16 },
      { text: 'Sonnenbrille', points: 14 },
    ],
  },
  {
    id: 'alltag-40',
    category: 'alltag',
    question: 'Welche Angewohnheit nervt Mitmenschen am meisten?',
    answers: [
      { text: 'Zuspätkommen', points: 26 },
      { text: 'Ständig aufs Handy schauen', points: 24 },
      { text: 'Laut telefonieren', points: 20 },
      { text: 'Beim Reden unterbrechen', points: 16 },
      { text: 'Nägelkauen', points: 14 },
    ],
  },
  {
    id: 'alltag-41',
    category: 'alltag',
    question: 'Was macht man zuerst im neuen Zuhause?',
    answers: [
      { text: 'Möbel aufbauen', points: 26 },
      { text: 'Kisten auspacken', points: 24 },
      { text: 'Putzen', points: 20 },
      { text: 'Einrichten/Dekorieren', points: 16 },
      { text: 'Nachbarn kennenlernen', points: 14 },
    ],
  },
  {
    id: 'alltag-42',
    category: 'alltag',
    question: 'Von welchem Fahrzeug träumen viele Menschen?',
    answers: [
      { text: 'Sportwagen', points: 30 },
      { text: 'Cabrio', points: 24 },
      { text: 'SUV', points: 20 },
      { text: 'Oldtimer', points: 16 },
      { text: 'Elektroauto', points: 10 },
    ],
  },
  {
    id: 'alltag-43',
    category: 'alltag',
    question: 'Was tut man, um fit zu bleiben?',
    answers: [
      { text: 'Joggen', points: 28 },
      { text: 'Ins Fitnessstudio gehen', points: 24 },
      { text: 'Radfahren', points: 20 },
      { text: 'Schwimmen', points: 16 },
      { text: 'Gesund essen', points: 12 },
    ],
  },
  {
    id: 'alltag-44',
    category: 'alltag',
    question: 'Welches Gerät kann man im Haushalt am wenigsten entbehren?',
    answers: [
      { text: 'Handy', points: 28 },
      { text: 'Waschmaschine', points: 24 },
      { text: 'Kühlschrank', points: 20 },
      { text: 'Herd', points: 16 },
      { text: 'Fernseher', points: 12 },
    ],
  },
  {
    id: 'alltag-45',
    category: 'alltag',
    question: 'Was macht man am ersten Ferientag?',
    answers: [
      { text: 'Ausschlafen', points: 30 },
      { text: 'Nichts planen/entspannen', points: 24 },
      { text: 'Koffer packen', points: 20 },
      { text: 'Freunde treffen', points: 16 },
      { text: 'Feiern', points: 10 },
    ],
  },
  {
    id: 'alltag-46',
    category: 'alltag',
    question: 'Was zieht man an einem kalten Wintertag an?',
    answers: [
      { text: 'Dicke Jacke', points: 28 },
      { text: 'Schal/Mütze', points: 24 },
      { text: 'Handschuhe', points: 20 },
      { text: 'Winterschuhe', points: 16 },
      { text: 'Thermounterwäsche', points: 12 },
    ],
  },
  {
    id: 'alltag-47',
    category: 'alltag',
    question: 'Was trinkt man bei einer Erkältung?',
    answers: [
      { text: 'Tee mit Honig', points: 32 },
      { text: 'Ingwertee', points: 24 },
      { text: 'Heiße Zitrone', points: 20 },
      { text: 'Wasser', points: 14 },
      { text: 'Glühwein', points: 10 },
    ],
  },
  {
    id: 'alltag-48',
    category: 'alltag',
    question: 'Was macht man an einem stressigen Arbeitstag als Erstes nach Feierabend?',
    answers: [
      { text: 'Auf dem Sofa entspannen', points: 30 },
      { text: 'Sport machen', points: 22 },
      { text: 'Kochen', points: 20 },
      { text: 'Mit Freunden/Familie reden', points: 16 },
      { text: 'Duschen', points: 12 },
    ],
  },
  {
    id: 'alltag-49',
    category: 'alltag',
    question: 'Welchen Ort besucht man gern an einem Sonntagnachmittag?',
    answers: [
      { text: 'Café', points: 26 },
      { text: 'Park', points: 24 },
      { text: 'Familie/Verwandte', points: 22 },
      { text: 'Museum', points: 16 },
      { text: 'Zuhause bleiben', points: 12 },
    ],
  },
  {
    id: 'alltag-50',
    category: 'alltag',
    question: 'Was braucht man für einen Campingausflug?',
    answers: [
      { text: 'Zelt', points: 30 },
      { text: 'Schlafsack', points: 24 },
      { text: 'Grill/Kocher', points: 20 },
      { text: 'Taschenlampe', points: 16 },
      { text: 'Insektenschutz', points: 10 },
    ],
  },
  {
    id: 'alltag-51',
    category: 'alltag',
    question: 'Welches Handwerk braucht man am häufigsten im Haus?',
    answers: [
      { text: 'Elektriker', points: 26 },
      { text: 'Klempner/Installateur', points: 24 },
      { text: 'Maler', points: 20 },
      { text: 'Schreiner', points: 16 },
      { text: 'Fliesenleger', points: 14 },
    ],
  },
  {
    id: 'alltag-52',
    category: 'alltag',
    question: 'Was macht man, wenn man ein Geschenk nicht mag?',
    answers: [
      { text: 'Trotzdem freuen/lächeln', points: 30 },
      { text: 'Umtauschen', points: 26 },
      { text: 'Weiterverschenken', points: 20 },
      { text: 'Ehrlich sagen', points: 14 },
      { text: 'Verstecken', points: 10 },
    ],
  },
  {
    id: 'alltag-53',
    category: 'alltag',
    question: 'Welche App nutzt man für die Navigation?',
    answers: [
      { text: 'Google Maps', points: 38 },
      { text: 'Waze', points: 22 },
      { text: 'Apple Maps', points: 20 },
      { text: 'Navigationsgerät', points: 12 },
      { text: 'Straßenkarte', points: 8 },
    ],
  },
  {
    id: 'alltag-54',
    category: 'alltag',
    question: 'Was tut man am liebsten an einem freien Nachmittag?',
    answers: [
      { text: 'Schlafen/Nickerchen', points: 26 },
      { text: 'Spazieren gehen', points: 24 },
      { text: 'Serien schauen', points: 22 },
      { text: 'Sport machen', points: 16 },
      { text: 'Lesen', points: 12 },
    ],
  },

  // ─── Essen & Trinken (Teil 3) ───
  {
    id: 'essen-21',
    category: 'essen',
    question: 'Was isst man auf dem Oktoberfest?',
    answers: [
      { text: 'Brezel', points: 28 },
      { text: 'Hendl (Brathähnchen)', points: 24 },
      { text: 'Weißwurst', points: 20 },
      { text: 'Schweinshaxe', points: 16 },
      { text: 'Steckerlfisch', points: 12 },
    ],
  },
  {
    id: 'essen-22',
    category: 'essen',
    question: 'Welches Getränk trinkt man zum Anstoßen?',
    answers: [
      { text: 'Sekt/Champagner', points: 34 },
      { text: 'Bier', points: 26 },
      { text: 'Wein', points: 20 },
      { text: 'Saft (alkoholfrei)', points: 12 },
      { text: 'Wasser', points: 8 },
    ],
  },
  {
    id: 'essen-23',
    category: 'essen',
    question: 'Was isst man zum Nachtisch?',
    answers: [
      { text: 'Eis', points: 30 },
      { text: 'Kuchen', points: 24 },
      { text: 'Pudding', points: 18 },
      { text: 'Obstsalat', points: 16 },
      { text: 'Schokolade', points: 12 },
    ],
  },
  {
    id: 'essen-24',
    category: 'essen',
    question: 'Welches Öl benutzt man am häufigsten zum Kochen?',
    answers: [
      { text: 'Sonnenblumenöl', points: 30 },
      { text: 'Olivenöl', points: 28 },
      { text: 'Rapsöl', points: 22 },
      { text: 'Butter/Butterschmalz', points: 12 },
      { text: 'Kokosöl', points: 8 },
    ],
  },
  {
    id: 'essen-25',
    category: 'essen',
    question: 'Was isst man zu Ostern?',
    answers: [
      { text: 'Schokoladeneier', points: 28 },
      { text: 'Lammbraten', points: 24 },
      { text: 'Bunte Ostereier', points: 20 },
      { text: 'Osterbrot/-kuchen', points: 16 },
      { text: 'Hefezopf', points: 12 },
    ],
  },
  {
    id: 'essen-26',
    category: 'essen',
    question: 'Welches Getränk trinkt man beim Camping?',
    answers: [
      { text: 'Bier', points: 26 },
      { text: 'Kaffee', points: 24 },
      { text: 'Wasser', points: 22 },
      { text: 'Wein', points: 16 },
      { text: 'Limo', points: 12 },
    ],
  },
  {
    id: 'essen-27',
    category: 'essen',
    question: 'Was bestellt man am liebsten beim Chinesen?',
    answers: [
      { text: 'Frühlingsrollen', points: 26 },
      { text: 'Gebratene Nudeln/Reis', points: 24 },
      { text: 'Süß-Sauer-Gerichte', points: 22 },
      { text: 'Peking-Ente', points: 16 },
      { text: 'Dim Sum', points: 12 },
    ],
  },
  {
    id: 'essen-28',
    category: 'essen',
    question: 'Welches Gewürz gehört in einen Kuchen?',
    answers: [
      { text: 'Zimt', points: 30 },
      { text: 'Vanille', points: 28 },
      { text: 'Kardamom', points: 16 },
      { text: 'Muskat', points: 14 },
      { text: 'Ingwer', points: 12 },
    ],
  },
  {
    id: 'essen-29',
    category: 'essen',
    question: 'Was isst man beim Frühstücksbuffet im Hotel?',
    answers: [
      { text: 'Rührei/Spiegelei', points: 24 },
      { text: 'Croissant', points: 22 },
      { text: 'Müsli/Joghurt', points: 22 },
      { text: 'Wurst/Käse', points: 18 },
      { text: 'Obst', points: 14 },
    ],
  },
  {
    id: 'essen-30',
    category: 'essen',
    question: 'Welches Getränk trinkt man auf einer Hochzeit?',
    answers: [
      { text: 'Sekt', points: 32 },
      { text: 'Wein', points: 24 },
      { text: 'Cocktails', points: 20 },
      { text: 'Bier', points: 16 },
      { text: 'Wasser', points: 8 },
    ],
  },
  {
    id: 'essen-31',
    category: 'essen',
    question: 'Was isst man am liebsten zu Silvester?',
    answers: [
      { text: 'Raclette/Fondue', points: 30 },
      { text: 'Berliner/Pfannkuchen', points: 24 },
      { text: 'Käsefondue', points: 18 },
      { text: 'Linsengericht (Glücksbringer)', points: 16 },
      { text: 'Feuerzangenbowle-Snacks', points: 12 },
    ],
  },
  {
    id: 'essen-32',
    category: 'essen',
    question: 'Welches Fleisch isst man am häufigsten?',
    answers: [
      { text: 'Hähnchen/Geflügel', points: 30 },
      { text: 'Schwein', points: 26 },
      { text: 'Rind', points: 24 },
      { text: 'Lamm', points: 12 },
      { text: 'Wild', points: 8 },
    ],
  },
  {
    id: 'essen-33',
    category: 'essen',
    question: 'Was trinkt man zum Kuchen?',
    answers: [
      { text: 'Kaffee', points: 38 },
      { text: 'Tee', points: 28 },
      { text: 'Kakao', points: 16 },
      { text: 'Milch', points: 10 },
      { text: 'Wasser', points: 8 },
    ],
  },
  {
    id: 'essen-34',
    category: 'essen',
    question: 'Welche Beilage gibt es am häufigsten zum Sonntagsbraten?',
    answers: [
      { text: 'Kartoffeln/Klöße', points: 30 },
      { text: 'Rotkohl', points: 24 },
      { text: 'Soße', points: 20 },
      { text: 'Gemüse', points: 16 },
      { text: 'Salat', points: 10 },
    ],
  },
  {
    id: 'essen-35',
    category: 'essen',
    question: 'Was legt man auf einen Hamburger?',
    answers: [
      { text: 'Käse', points: 26 },
      { text: 'Salat', points: 22 },
      { text: 'Tomate', points: 20 },
      { text: 'Zwiebeln', points: 18 },
      { text: 'Gurken', points: 14 },
    ],
  },
  {
    id: 'essen-36',
    category: 'essen',
    question: 'Welches Getränk trinkt man beim Sport?',
    answers: [
      { text: 'Wasser', points: 38 },
      { text: 'Isotonisches Getränk', points: 26 },
      { text: 'Proteinshake', points: 18 },
      { text: 'Saft', points: 10 },
      { text: 'Energydrink', points: 8 },
    ],
  },
  {
    id: 'essen-37',
    category: 'essen',
    question: 'Was isst man beim Sushi-Restaurant am liebsten?',
    answers: [
      { text: 'Maki-Rollen', points: 28 },
      { text: 'Nigiri', points: 24 },
      { text: 'California Roll', points: 22 },
      { text: 'Sashimi', points: 16 },
      { text: 'Tempura', points: 10 },
    ],
  },
  {
    id: 'essen-38',
    category: 'essen',
    question: 'Was gehört zum Kaffee dazu?',
    answers: [
      { text: 'Milch', points: 34 },
      { text: 'Zucker', points: 30 },
      { text: 'Sahne', points: 18 },
      { text: 'Sirup', points: 10 },
      { text: 'Nichts (schwarz)', points: 8 },
    ],
  },
  {
    id: 'essen-39',
    category: 'essen',
    question: 'Was isst man beim Picknick?',
    answers: [
      { text: 'Sandwiches', points: 28 },
      { text: 'Obst', points: 24 },
      { text: 'Chips', points: 20 },
      { text: 'Kuchen', points: 16 },
      { text: 'Salat', points: 12 },
    ],
  },
  {
    id: 'essen-40',
    category: 'essen',
    question: 'Welche Suppe isst man am liebsten?',
    answers: [
      { text: 'Tomatensuppe', points: 26 },
      { text: 'Hühnersuppe', points: 24 },
      { text: 'Kürbissuppe', points: 20 },
      { text: 'Gulaschsuppe', points: 18 },
      { text: 'Linsensuppe', points: 12 },
    ],
  },
  {
    id: 'essen-41',
    category: 'essen',
    question: 'Was trinkt man beim Grillabend am liebsten?',
    answers: [
      { text: 'Bier', points: 32 },
      { text: 'Cocktails', points: 22 },
      { text: 'Limonade', points: 20 },
      { text: 'Wein', points: 16 },
      { text: 'Wasser', points: 10 },
    ],
  },
  {
    id: 'essen-42',
    category: 'essen',
    question: 'Welches Gebäck isst man zum Kaffee am Nachmittag?',
    answers: [
      { text: 'Torte', points: 30 },
      { text: 'Streuselkuchen', points: 24 },
      { text: 'Kekse', points: 20 },
      { text: 'Muffins', points: 16 },
      { text: 'Croissant', points: 10 },
    ],
  },
  {
    id: 'essen-43',
    category: 'essen',
    question: 'Was isst man typischerweise zu Karneval/Fasching?',
    answers: [
      { text: 'Berliner/Krapfen', points: 32 },
      { text: 'Mutzenmandeln', points: 20 },
      { text: 'Popcorn', points: 18 },
      { text: 'Currywurst', points: 16 },
      { text: 'Kamelle/Süßigkeiten', points: 14 },
    ],
  },
  {
    id: 'essen-44',
    category: 'essen',
    question: 'Welches Getränk trinkt man in den Ferien am Pool?',
    answers: [
      { text: 'Cocktail', points: 30 },
      { text: 'Wasser', points: 24 },
      { text: 'Limonade', points: 22 },
      { text: 'Bier', points: 16 },
      { text: 'Saft', points: 8 },
    ],
  },
  {
    id: 'essen-45',
    category: 'essen',
    question: 'Was gibt man auf einen Salat?',
    answers: [
      { text: 'Dressing/Vinaigrette', points: 28 },
      { text: 'Käse', points: 24 },
      { text: 'Croutons', points: 20 },
      { text: 'Nüsse', points: 16 },
      { text: 'Tomaten', points: 12 },
    ],
  },
  {
    id: 'essen-46',
    category: 'essen',
    question: 'Welches Getränk trinkt man zum Käse?',
    answers: [
      { text: 'Rotwein', points: 32 },
      { text: 'Weißwein', points: 26 },
      { text: 'Bier', points: 20 },
      { text: 'Traubensaft', points: 12 },
      { text: 'Portwein', points: 10 },
    ],
  },
  {
    id: 'essen-47',
    category: 'essen',
    question: 'Was isst man beim Fußballgucken?',
    answers: [
      { text: 'Chips', points: 28 },
      { text: 'Pizza', points: 24 },
      { text: 'Bratwurst', points: 20 },
      { text: 'Popcorn', points: 16 },
      { text: 'Nachos', points: 12 },
    ],
  },
  {
    id: 'essen-48',
    category: 'essen',
    question: 'Welches Gemüse verwendet man am häufigsten beim Kochen?',
    answers: [
      { text: 'Zwiebeln', points: 28 },
      { text: 'Tomaten', points: 24 },
      { text: 'Kartoffeln', points: 22 },
      { text: 'Karotten', points: 16 },
      { text: 'Paprika', points: 10 },
    ],
  },
  {
    id: 'essen-49',
    category: 'essen',
    question: 'Was trinkt man auf einer Geburtstagsfeier?',
    answers: [
      { text: 'Sekt', points: 28 },
      { text: 'Saft/Limonade', points: 24 },
      { text: 'Bier', points: 20 },
      { text: 'Cocktails', points: 16 },
      { text: 'Kaffee/Tee', points: 12 },
    ],
  },
  {
    id: 'essen-50',
    category: 'essen',
    question: 'Welches Backwerk kauft man morgens beim Bäcker?',
    answers: [
      { text: 'Brötchen', points: 32 },
      { text: 'Croissant', points: 24 },
      { text: 'Vollkornbrot', points: 20 },
      { text: 'Kuchenstück', points: 14 },
      { text: 'Laugengebäck', points: 10 },
    ],
  },
  {
    id: 'essen-51',
    category: 'essen',
    question: 'Was isst man zu einer Currywurst?',
    answers: [
      { text: 'Pommes', points: 34 },
      { text: 'Brötchen', points: 26 },
      { text: 'Nichts extra', points: 18 },
      { text: 'Salat', points: 12 },
      { text: 'Reis', points: 10 },
    ],
  },
  {
    id: 'essen-52',
    category: 'essen',
    question: 'Welches Getränk trinkt man in der Sauna-Pause?',
    answers: [
      { text: 'Wasser', points: 36 },
      { text: 'Saft', points: 24 },
      { text: 'Tee', points: 22 },
      { text: 'Elektrolytgetränk', points: 10 },
      { text: 'Bier', points: 8 },
    ],
  },
  {
    id: 'essen-53',
    category: 'essen',
    question: 'Was isst man beim Betriebsausflug/Picknick im Büro?',
    answers: [
      { text: 'Belegte Brötchen', points: 28 },
      { text: 'Kuchen', points: 24 },
      { text: 'Obst', points: 20 },
      { text: 'Salate', points: 16 },
      { text: 'Fingerfood', points: 12 },
    ],
  },

  // ─── Familie & Freizeit (Teil 3) ───
  {
    id: 'familie-21',
    category: 'familie',
    question: 'Was macht die Familie am liebsten im Herbst?',
    answers: [
      { text: 'Kastanien/Blätter sammeln', points: 26 },
      { text: 'Kürbis schnitzen', points: 24 },
      { text: 'Spazieren im Wald', points: 22 },
      { text: 'Drachen steigen lassen', points: 16 },
      { text: 'Tee trinken/kuscheln', points: 12 },
    ],
  },
  {
    id: 'familie-22',
    category: 'familie',
    question: 'Welches Spielzeug lieben Kinder am meisten?',
    answers: [
      { text: 'Bauklötze/Lego', points: 28 },
      { text: 'Puppen', points: 24 },
      { text: 'Ferngesteuertes Auto', points: 20 },
      { text: 'Kuscheltier', points: 16 },
      { text: 'Ball', points: 12 },
    ],
  },
  {
    id: 'familie-23',
    category: 'familie',
    question: 'Was macht man am Muttertag?',
    answers: [
      { text: 'Blumen schenken', points: 30 },
      { text: 'Frühstück ans Bett bringen', points: 26 },
      { text: 'Karte basteln', points: 18 },
      { text: 'Gemeinsam essen gehen', points: 16 },
      { text: 'Anrufen', points: 10 },
    ],
  },
  {
    id: 'familie-24',
    category: 'familie',
    question: 'Welchen Ort besuchen Familien am Wochenende am liebsten?',
    answers: [
      { text: 'Spielplatz', points: 28 },
      { text: 'Freizeitpark', points: 24 },
      { text: 'Zoo/Tierpark', points: 22 },
      { text: 'Schwimmbad', points: 16 },
      { text: 'Wald/Natur', points: 10 },
    ],
  },
  {
    id: 'familie-25',
    category: 'familie',
    question: 'Was macht man beim Familien-Fotoshooting?',
    answers: [
      { text: 'Lächeln/Posieren', points: 28 },
      { text: 'Lustige Gesichter machen', points: 24 },
      { text: 'Sich streiten wer wo steht', points: 20 },
      { text: 'Warten', points: 16 },
      { text: 'Kinder beruhigen', points: 12 },
    ],
  },
  {
    id: 'familie-26',
    category: 'familie',
    question: 'Welche Regel gibt es am Esstisch?',
    answers: [
      { text: 'Handy verboten', points: 28 },
      { text: 'Erst aufstehen, wenn alle fertig sind', points: 24 },
      { text: 'Vorher Hände waschen', points: 20 },
      { text: 'Alles probieren', points: 16 },
      { text: 'Danke sagen', points: 12 },
    ],
  },
  {
    id: 'familie-27',
    category: 'familie',
    question: 'Was schenkt man zur Einschulung?',
    answers: [
      { text: 'Schultüte', points: 34 },
      { text: 'Schulranzen', points: 24 },
      { text: 'Süßigkeiten', points: 20 },
      { text: 'Geld', points: 14 },
      { text: 'Stifte/Schulsachen', points: 8 },
    ],
  },
  {
    id: 'familie-28',
    category: 'familie',
    question: 'Welches Familienritual gibt es vorm Schlafengehen?',
    answers: [
      { text: 'Gute-Nacht-Geschichte', points: 30 },
      { text: 'Zähneputzen', points: 24 },
      { text: 'Kuscheln', points: 20 },
      { text: 'Licht aus/Nachtlicht an', points: 16 },
      { text: 'Gute-Nacht-Kuss', points: 10 },
    ],
  },
  {
    id: 'familie-29',
    category: 'familie',
    question: 'Was macht man am Vatertag?',
    answers: [
      { text: 'Grillen', points: 28 },
      { text: 'Ausflug machen', points: 24 },
      { text: 'Männertour/Wandern', points: 20 },
      { text: 'Geschenk überreichen', points: 16 },
      { text: 'Bier trinken', points: 12 },
    ],
  },
  {
    id: 'familie-30',
    category: 'familie',
    question: 'Welches Fahrzeug nutzt die Familie für Ausflüge?',
    answers: [
      { text: 'Auto', points: 38 },
      { text: 'Fahrrad', points: 24 },
      { text: 'Bus/Bahn', points: 20 },
      { text: 'Wohnmobil', points: 10 },
      { text: 'Zu Fuß', points: 8 },
    ],
  },
  {
    id: 'familie-31',
    category: 'familie',
    question: 'Was macht man am liebsten mit Cousins/Cousinen?',
    answers: [
      { text: 'Spielen', points: 30 },
      { text: 'Toben/Herumtollen', points: 24 },
      { text: 'Quatschen', points: 20 },
      { text: 'Filme schauen', points: 16 },
      { text: 'Verstecken spielen', points: 10 },
    ],
  },
  {
    id: 'familie-32',
    category: 'familie',
    question: 'Welches Fest feiert die Familie am aufwendigsten?',
    answers: [
      { text: 'Weihnachten', points: 34 },
      { text: 'Geburtstag', points: 26 },
      { text: 'Hochzeit', points: 18 },
      { text: 'Silvester', points: 12 },
      { text: 'Ostern', points: 10 },
    ],
  },
  {
    id: 'familie-33',
    category: 'familie',
    question: 'Was macht man auf einer Kindergeburtstagsfeier?',
    answers: [
      { text: 'Spiele spielen', points: 26 },
      { text: 'Kuchen essen', points: 24 },
      { text: 'Geschenke auspacken', points: 22 },
      { text: 'Luftballons/Deko aufhängen', points: 16 },
      { text: 'Im Garten toben', points: 12 },
    ],
  },
  {
    id: 'familie-34',
    category: 'familie',
    question: 'Welches Haustier braucht am meisten Pflege?',
    answers: [
      { text: 'Hund', points: 32 },
      { text: 'Katze', points: 22 },
      { text: 'Pferd', points: 20 },
      { text: 'Kaninchen', points: 14 },
      { text: 'Vögel', points: 12 },
    ],
  },
  {
    id: 'familie-35',
    category: 'familie',
    question: 'Was packt man in die Schultüte?',
    answers: [
      { text: 'Süßigkeiten', points: 30 },
      { text: 'Schulsachen', points: 24 },
      { text: 'Spielzeug', points: 20 },
      { text: 'Gutschein', points: 16 },
      { text: 'Buch', points: 10 },
    ],
  },
  {
    id: 'familie-36',
    category: 'familie',
    question: 'Welche Aufgabe übernehmen Kinder im Haushalt?',
    answers: [
      { text: 'Zimmer aufräumen', points: 28 },
      { text: 'Tisch decken', points: 24 },
      { text: 'Müll rausbringen', points: 20 },
      { text: 'Geschirrspüler ausräumen', points: 16 },
      { text: 'Staubsaugen', points: 12 },
    ],
  },
  {
    id: 'familie-37',
    category: 'familie',
    question: 'Was macht man an einem Familien-Wandertag?',
    answers: [
      { text: 'Picknick machen', points: 26 },
      { text: 'Fotos machen', points: 22 },
      { text: 'Natur entdecken', points: 22 },
      { text: 'Sich übers Laufen beschweren', points: 16 },
      { text: 'Rasten/Pause machen', points: 14 },
    ],
  },
  {
    id: 'familie-38',
    category: 'familie',
    question: 'Welches Spiel spielt man im Auto auf langen Fahrten?',
    answers: [
      { text: '"Ich sehe was, was du nicht siehst"', points: 28 },
      { text: 'Kennzeichen-Raten', points: 24 },
      { text: 'Quizfragen/20 Fragen', points: 20 },
      { text: 'Schlafen', points: 16 },
      { text: 'Musik raten', points: 12 },
    ],
  },
  {
    id: 'familie-39',
    category: 'familie',
    question: 'Was macht man beim Familientreffen?',
    answers: [
      { text: 'Essen', points: 28 },
      { text: 'Erzählen/Quatschen', points: 24 },
      { text: 'Fotos anschauen', points: 20 },
      { text: 'Spielen', points: 16 },
      { text: 'Erinnerungen austauschen', points: 12 },
    ],
  },
  {
    id: 'familie-40',
    category: 'familie',
    question: 'Welches Ritual gibt es an Weihnachten vor dem Auspacken?',
    answers: [
      { text: 'Warten, bis alle da sind', points: 28 },
      { text: 'Weihnachtslieder singen', points: 24 },
      { text: 'Gemeinsam essen', points: 22 },
      { text: 'Foto machen', points: 16 },
      { text: 'Kerzen anzünden', points: 10 },
    ],
  },
  {
    id: 'familie-41',
    category: 'familie',
    question: 'Was ist eine typische Familien-Tradition im Sommer?',
    answers: [
      { text: 'Grillabend', points: 28 },
      { text: 'Eis essen gehen', points: 26 },
      { text: 'Ausflug ins Freibad', points: 22 },
      { text: 'Urlaub am Meer', points: 14 },
      { text: 'Campen', points: 10 },
    ],
  },
  {
    id: 'familie-42',
    category: 'familie',
    question: 'Welches Utensil braucht man für einen Kindergeburtstag?',
    answers: [
      { text: 'Luftballons', points: 26 },
      { text: 'Kuchen mit Kerzen', points: 24 },
      { text: 'Deko/Girlanden', points: 20 },
      { text: 'Geschenke', points: 16 },
      { text: 'Spiele', points: 14 },
    ],
  },
  {
    id: 'familie-43',
    category: 'familie',
    question: 'Was macht man, wenn das Baby nicht schlafen will?',
    answers: [
      { text: 'Herumtragen/Wiegen', points: 28 },
      { text: 'Singen', points: 24 },
      { text: 'Schnuller geben', points: 20 },
      { text: 'Im Kinderwagen spazieren fahren', points: 16 },
      { text: 'Geduldig warten', points: 12 },
    ],
  },
  {
    id: 'familie-44',
    category: 'familie',
    question: 'Welches Spiel liebt die ganze Familie an Regentagen?',
    answers: [
      { text: 'Gesellschaftsspiel', points: 30 },
      { text: 'Verstecken im Haus', points: 22 },
      { text: 'Puzzle', points: 20 },
      { text: 'Malen/Basteln', points: 16 },
      { text: 'Kissenschlacht', points: 12 },
    ],
  },
  {
    id: 'familie-45',
    category: 'familie',
    question: 'Was schenkt man zur Hochzeit eines Familienmitglieds?',
    answers: [
      { text: 'Geld', points: 30 },
      { text: 'Gutschein', points: 24 },
      { text: 'Haushaltsgegenstände', points: 20 },
      { text: 'Etwas von der Wunschliste', points: 16 },
      { text: 'Beitrag zur Hochzeitsreise', points: 10 },
    ],
  },
  {
    id: 'familie-46',
    category: 'familie',
    question: 'Welches Gefühl überwiegt bei einem Familien-Umzug?',
    answers: [
      { text: 'Aufregung', points: 28 },
      { text: 'Stress', points: 26 },
      { text: 'Vorfreude', points: 22 },
      { text: 'Wehmut', points: 14 },
      { text: 'Neugier', points: 10 },
    ],
  },
  {
    id: 'familie-47',
    category: 'familie',
    question: 'Was macht man, um Streit zwischen Geschwistern zu schlichten?',
    answers: [
      { text: 'Beide anhören', points: 28 },
      { text: 'Gemeinsame Regel aufstellen', points: 24 },
      { text: 'Auszeit geben', points: 20 },
      { text: 'Kompromiss finden', points: 16 },
      { text: 'Ablenken', points: 12 },
    ],
  },
  {
    id: 'familie-48',
    category: 'familie',
    question: 'Welche Aktivität passt zu einem Familien-Spieleabend im Winter?',
    answers: [
      { text: 'Brettspiele', points: 30 },
      { text: 'Kartenspiele', points: 24 },
      { text: 'Kakao trinken', points: 20 },
      { text: 'Filme schauen', points: 16 },
      { text: 'Puzzeln', points: 10 },
    ],
  },
  {
    id: 'familie-49',
    category: 'familie',
    question: 'Was braucht man für eine Übernachtungsparty der Kinder?',
    answers: [
      { text: 'Schlafsäcke', points: 28 },
      { text: 'Snacks', points: 24 },
      { text: 'Filme', points: 20 },
      { text: 'Taschenlampen', points: 16 },
      { text: 'Kissen/Decken', points: 12 },
    ],
  },
  {
    id: 'familie-50',
    category: 'familie',
    question: 'Welches Familienmitglied verwöhnt die Kinder am meisten?',
    answers: [
      { text: 'Oma', points: 34 },
      { text: 'Opa', points: 26 },
      { text: 'Tante/Onkel', points: 18 },
      { text: 'Eltern', points: 12 },
      { text: 'Patenonkel/-tante', points: 10 },
    ],
  },
  {
    id: 'familie-51',
    category: 'familie',
    question: 'Was macht man am ersten Schultag?',
    answers: [
      { text: 'Fotos machen', points: 28 },
      { text: 'Schultüte überreichen', points: 26 },
      { text: 'Zusammen zur Schule gehen', points: 20 },
      { text: 'Gemeinsam frühstücken', points: 16 },
      { text: 'Aufgeregt sein', points: 10 },
    ],
  },
  {
    id: 'familie-52',
    category: 'familie',
    question: 'Welches Familienspiel spielt man draußen im Garten?',
    answers: [
      { text: 'Fangen/Verstecken', points: 26 },
      { text: 'Federball/Badminton', points: 24 },
      { text: 'Fußball', points: 22 },
      { text: 'Wasserballon-Schlacht', points: 16 },
      { text: 'Seilspringen', points: 12 },
    ],
  },
  {
    id: 'familie-53',
    category: 'familie',
    question: 'Was macht man, wenn die ganze Familie zusammen kocht?',
    answers: [
      { text: 'Aufgaben verteilen', points: 28 },
      { text: 'Zusammen probieren', points: 24 },
      { text: 'Musik hören dabei', points: 20 },
      { text: 'Sich in die Quere kommen', points: 16 },
      { text: 'Am Ende gemeinsam essen', points: 12 },
    ],
  },
];
