// AUTO-GENERATED by scripts/generate-flag-cards.mjs
// Do not edit manually.
import { Card } from './types';

export const flagCards: Card[] = [
  {
    "id": "flag-ad",
    "title": "Flagge Andorra",
    "category": "country",
    "year": 1993,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Andorra – 1993, Erste Verfassung (Souveränität)",
    "hint": "Andorra",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/ad.png"
    }
  },
  {
    "id": "flag-ae",
    "title": "Flagge Vereinigte Arabische Emirate",
    "category": "country",
    "year": 1971,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Vereinigte Arabische Emirate – Staatsflagge (Jahr variabel).",
    "hint": "Vereinigte Arabische Emirate",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/ae.png"
    }
  },
  {
    "id": "flag-af",
    "title": "Flagge Afghanistan",
    "category": "country",
    "year": 2021,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Äfghanistan – Staatsflagge (Jahr variabel).",
    "hint": "Äfghanistan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/af.png"
    }
  },
  {
    "id": "flag-ag",
    "title": "Flagge Antigua und Barbuda",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Äntigua und Barbuda – Staatsflagge (Jahr variabel).",
    "hint": "Äntigua und Barbuda",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/ag.png"
    }
  },
  {
    "id": "flag-ai",
    "title": "Flagge Anguilla",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Änguilla – Staatsflagge (Jahr variabel).",
    "hint": "Änguilla",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/ai.png"
    }
  },
  {
    "id": "flag-al",
    "title": "Flagge Albanien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Älbanien – Staatsflagge (Jahr variabel).",
    "hint": "Älbanien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/al.png"
    }
  },
  {
    "id": "flag-am",
    "title": "Flagge Armenien",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Ärmenien – Staatsflagge (Jahr variabel).",
    "hint": "Ärmenien",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/am.png"
    }
  },
  {
    "id": "flag-ao",
    "title": "Flagge Angola",
    "category": "country",
    "year": 1975,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Ängola – Staatsflagge (Jahr variabel).",
    "hint": "Ängola",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/ao.png"
    }
  },
  {
    "id": "flag-aq",
    "title": "Flagge Antarktis",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Äntarktis – Staatsflagge (Jahr variabel).",
    "hint": "Äntarktis",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/aq.png"
    }
  },
  {
    "id": "flag-ar",
    "title": "Flagge Argentinien",
    "category": "country",
    "year": 1853,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Ärgentinien – Staatsflagge (Jahr variabel).",
    "hint": "Ärgentinien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/ar.png"
    }
  },
  {
    "id": "flag-as",
    "title": "Flagge Amerikanisch-Samoa",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Ämerikanisch-Samoa – Staatsflagge (Jahr variabel).",
    "hint": "Ämerikanisch-Samoa",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/as.png"
    }
  },
  {
    "id": "flag-at",
    "title": "Flagge Österreich",
    "category": "country",
    "year": 1945,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Österreich – 1945, Zweite Republik",
    "hint": "Österreich",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/at.png"
    }
  },
  {
    "id": "flag-au",
    "title": "Flagge Australien",
    "category": "country",
    "year": 1901,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Äustralien – Staatsflagge (Jahr variabel).",
    "hint": "Äustralien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/au.png"
    }
  },
  {
    "id": "flag-aw",
    "title": "Flagge Aruba",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Äruba – Staatsflagge (Jahr variabel).",
    "hint": "Äruba",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/aw.png"
    }
  },
  {
    "id": "flag-ax",
    "title": "Flagge Ålandinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Ålandinseln – Staatsflagge (Jahr variabel).",
    "hint": "Ålandinseln",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/ax.png"
    }
  },
  {
    "id": "flag-az",
    "title": "Flagge Aserbaidschan",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Äserbaidschan – Staatsflagge (Jahr variabel).",
    "hint": "Äserbaidschan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/az.png"
    }
  },
  {
    "id": "flag-ba",
    "title": "Flagge Bosnien und Herzegowina",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Bosnien und Herzegowina – Staatsflagge (Jahr variabel).",
    "hint": "Bosnien und Herzegowina",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/ba.png"
    }
  },
  {
    "id": "flag-bb",
    "title": "Flagge Barbados",
    "category": "country",
    "year": 2021,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Barbados – 2021, Übergang zur Republik",
    "hint": "Barbados",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/bb.png"
    }
  },
  {
    "id": "flag-bd",
    "title": "Flagge Bangladesch",
    "category": "country",
    "year": 1971,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Bangladesch – 1971, Unabhängigkeit",
    "hint": "Bangladesch",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/bd.png"
    }
  },
  {
    "id": "flag-be",
    "title": "Flagge Belgien",
    "category": "country",
    "year": 1831,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Belgien – 1831, Unabhängigkeit und Verfassung nach der Revolution",
    "hint": "Belgien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/be.png"
    }
  },
  {
    "id": "flag-bf",
    "title": "Flagge Burkina Faso",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Burkina Faso – 1960, Unabhängigkeit",
    "hint": "Burkina Faso",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/bf.png"
    }
  },
  {
    "id": "flag-bg",
    "title": "Flagge Bulgarien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Bulgarien – Staatsflagge (Jahr variabel).",
    "hint": "Bulgarien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/bg.png"
    }
  },
  {
    "id": "flag-bh",
    "title": "Flagge Bahrain",
    "category": "country",
    "year": 1971,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Bahrain – 1971, Unabhängigkeit",
    "hint": "Bahrain",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/bh.png"
    }
  },
  {
    "id": "flag-bi",
    "title": "Flagge Burundi",
    "category": "country",
    "year": 1962,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Burundi – 1962, Unabhängigkeit",
    "hint": "Burundi",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/bi.png"
    }
  },
  {
    "id": "flag-bj",
    "title": "Flagge Benin",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Benin – 1960, Unabhängigkeit",
    "hint": "Benin",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/bj.png"
    }
  },
  {
    "id": "flag-bl",
    "title": "Flagge St. Barthélemy",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "St. Barthélemy – Staatsflagge (Jahr variabel).",
    "hint": "St. Barthélemy",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/bl.png"
    }
  },
  {
    "id": "flag-bm",
    "title": "Flagge Bermuda",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Bermuda – Staatsflagge (Jahr variabel).",
    "hint": "Bermuda",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/bm.png"
    }
  },
  {
    "id": "flag-bn",
    "title": "Flagge Brunei Darussalam",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Brunei Darussalam – Staatsflagge (Jahr variabel).",
    "hint": "Brunei Darussalam",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/bn.png"
    }
  },
  {
    "id": "flag-bo",
    "title": "Flagge Bolivien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Bolivien – Staatsflagge (Jahr variabel).",
    "hint": "Bolivien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/bo.png"
    }
  },
  {
    "id": "flag-bq",
    "title": "Flagge Karibische Niederlande",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Karibische Niederlande – Staatsflagge (Jahr variabel).",
    "hint": "Karibische Niederlande",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/bq.png"
    }
  },
  {
    "id": "flag-br",
    "title": "Flagge Brasilien",
    "category": "country",
    "year": 1988,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Brasilien – 1988, Aktuelle Verfassung",
    "hint": "Brasilien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/br.png"
    }
  },
  {
    "id": "flag-bs",
    "title": "Flagge Bahamas",
    "category": "country",
    "year": 1973,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Bahamas – 1973, Unabhängigkeit",
    "hint": "Bahamas",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/bs.png"
    }
  },
  {
    "id": "flag-bt",
    "title": "Flagge Bhutan",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Bhutan – Staatsflagge (Jahr variabel).",
    "hint": "Bhutan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/bt.png"
    }
  },
  {
    "id": "flag-bv",
    "title": "Flagge Bouvetinsel",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Bouvetinsel – Staatsflagge (Jahr variabel).",
    "hint": "Bouvetinsel",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/bv.png"
    }
  },
  {
    "id": "flag-bw",
    "title": "Flagge Botsuana",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Botsuana – Staatsflagge (Jahr variabel).",
    "hint": "Botsuana",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/bw.png"
    }
  },
  {
    "id": "flag-by",
    "title": "Flagge Belarus",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Belarus – 1991, Unabhängigkeit von der UdSSR",
    "hint": "Belarus",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/by.png"
    }
  },
  {
    "id": "flag-bz",
    "title": "Flagge Belize",
    "category": "country",
    "year": 1981,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Belize – 1981, Unabhängigkeit",
    "hint": "Belize",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/bz.png"
    }
  },
  {
    "id": "flag-ca",
    "title": "Flagge Kanada",
    "category": "country",
    "year": 1867,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kanada – 1867, British North America Act (Beginn der Eigenstaatlichkeit)",
    "hint": "Kanada",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/ca.png"
    }
  },
  {
    "id": "flag-cc",
    "title": "Flagge Kokosinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kokosinseln – Staatsflagge (Jahr variabel).",
    "hint": "Kokosinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/cc.png"
    }
  },
  {
    "id": "flag-cd",
    "title": "Flagge Kongo-Kinshasa",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kongo-Kinshasa – Staatsflagge (Jahr variabel).",
    "hint": "Kongo-Kinshasa",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/cd.png"
    }
  },
  {
    "id": "flag-cf",
    "title": "Flagge Zentralafrikanische Republik",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Zentralafrikanische Republik – Staatsflagge (Jahr variabel).",
    "hint": "Zentralafrikanische Republik",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/cf.png"
    }
  },
  {
    "id": "flag-cg",
    "title": "Flagge Kongo-Brazzaville",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kongo-Brazzaville – Staatsflagge (Jahr variabel).",
    "hint": "Kongo-Brazzaville",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/cg.png"
    }
  },
  {
    "id": "flag-ch",
    "title": "Flagge Schweiz",
    "category": "country",
    "year": 1848,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Schweiz – 1848, Gründung des modernen Bundesstaates",
    "hint": "Schweiz",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/ch.png"
    }
  },
  {
    "id": "flag-ci",
    "title": "Flagge Côte d’Ivoire",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Côte d’Ivoire – Staatsflagge (Jahr variabel).",
    "hint": "Côte d’Ivoire",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/ci.png"
    }
  },
  {
    "id": "flag-ck",
    "title": "Flagge Cookinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Cookinseln – Staatsflagge (Jahr variabel).",
    "hint": "Cookinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/ck.png"
    }
  },
  {
    "id": "flag-cl",
    "title": "Flagge Chile",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Chile – Staatsflagge (Jahr variabel).",
    "hint": "Chile",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/cl.png"
    }
  },
  {
    "id": "flag-cm",
    "title": "Flagge Kamerun",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kamerun – 1960, Unabhängigkeit",
    "hint": "Kamerun",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/cm.png"
    }
  },
  {
    "id": "flag-cn",
    "title": "Flagge China",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "China – Staatsflagge (Jahr variabel).",
    "hint": "China",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/cn.png"
    }
  },
  {
    "id": "flag-co",
    "title": "Flagge Kolumbien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kolumbien – Staatsflagge (Jahr variabel).",
    "hint": "Kolumbien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/co.png"
    }
  },
  {
    "id": "flag-cr",
    "title": "Flagge Costa Rica",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Costa Rica – Staatsflagge (Jahr variabel).",
    "hint": "Costa Rica",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/cr.png"
    }
  },
  {
    "id": "flag-cu",
    "title": "Flagge Kuba",
    "category": "country",
    "year": 2019,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kuba – 2019, Neue Verfassung",
    "hint": "Kuba",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/cu.png"
    }
  },
  {
    "id": "flag-cv",
    "title": "Flagge Cabo Verde",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Cabo Verde – Staatsflagge (Jahr variabel).",
    "hint": "Cabo Verde",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/cv.png"
    }
  },
  {
    "id": "flag-cw",
    "title": "Flagge Curaçao",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Curaçao – Staatsflagge (Jahr variabel).",
    "hint": "Curaçao",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/cw.png"
    }
  },
  {
    "id": "flag-cx",
    "title": "Flagge Weihnachtsinsel",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Weihnachtsinsel – Staatsflagge (Jahr variabel).",
    "hint": "Weihnachtsinsel",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/cx.png"
    }
  },
  {
    "id": "flag-cy",
    "title": "Flagge Zypern",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Zypern – 1960, Unabhängigkeit",
    "hint": "Zypern",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/cy.png"
    }
  },
  {
    "id": "flag-cz",
    "title": "Flagge Tschechien",
    "category": "country",
    "year": 1993,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Tschechien – 1993, Teilung der Tschechoslowakei",
    "hint": "Tschechien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/cz.png"
    }
  },
  {
    "id": "flag-de",
    "title": "Flagge Deutschland",
    "category": "country",
    "year": 1949,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Deutschland – 1949, Grundgesetz (BRD)",
    "hint": "Deutschland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/de.png"
    }
  },
  {
    "id": "flag-dj",
    "title": "Flagge Dschibuti",
    "category": "country",
    "year": 1977,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Dschibuti – 1977, Unabhängigkeit",
    "hint": "Dschibuti",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/dj.png"
    }
  },
  {
    "id": "flag-dk",
    "title": "Flagge Dänemark",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Dänemark – Staatsflagge (Jahr variabel).",
    "hint": "Dänemark",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/dk.png"
    }
  },
  {
    "id": "flag-dm",
    "title": "Flagge Dominica",
    "category": "country",
    "year": 1978,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Dominica – 1978, Unabhängigkeit",
    "hint": "Dominica",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/dm.png"
    }
  },
  {
    "id": "flag-do",
    "title": "Flagge Dominikanische Republik",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Dominikanische Republik – Staatsflagge (Jahr variabel).",
    "hint": "Dominikanische Republik",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/do.png"
    }
  },
  {
    "id": "flag-dz",
    "title": "Flagge Algerien",
    "category": "country",
    "year": 1962,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Älgerien – Staatsflagge (Jahr variabel).",
    "hint": "Älgerien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/dz.png"
    }
  },
  {
    "id": "flag-ec",
    "title": "Flagge Ecuador",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Ecuador – Staatsflagge (Jahr variabel).",
    "hint": "Ecuador",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/ec.png"
    }
  },
  {
    "id": "flag-ee",
    "title": "Flagge Estland",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Estland – 1991, Wiederherstellung der Unabhängigkeit",
    "hint": "Estland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/ee.png"
    }
  },
  {
    "id": "flag-eg",
    "title": "Flagge Ägypten",
    "category": "country",
    "year": 1953,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Ägypten – 1953, Ausrufung der Republik",
    "hint": "Ägypten",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/eg.png"
    }
  },
  {
    "id": "flag-eh",
    "title": "Flagge Westsahara",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Westsahara – Staatsflagge (Jahr variabel).",
    "hint": "Westsahara",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/eh.png"
    }
  },
  {
    "id": "flag-er",
    "title": "Flagge Eritrea",
    "category": "country",
    "year": 1993,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Eritrea – 1993, Unabhängigkeit von Äthiopien",
    "hint": "Eritrea",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/er.png"
    }
  },
  {
    "id": "flag-es",
    "title": "Flagge Spanien",
    "category": "country",
    "year": 1978,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Spanien – 1978, Demokratische Verfassung",
    "hint": "Spanien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/es.png"
    }
  },
  {
    "id": "flag-et",
    "title": "Flagge Äthiopien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Äthiopien – Staatsflagge (Jahr variabel).",
    "hint": "Äthiopien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/et.png"
    }
  },
  {
    "id": "flag-fi",
    "title": "Flagge Finnland",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Finnland – Staatsflagge (Jahr variabel).",
    "hint": "Finnland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/fi.png"
    }
  },
  {
    "id": "flag-fj",
    "title": "Flagge Fidschi",
    "category": "country",
    "year": 1970,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Fidschi – 1970, Unabhängigkeit",
    "hint": "Fidschi",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/fj.png"
    }
  },
  {
    "id": "flag-fk",
    "title": "Flagge Falklandinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Falklandinseln – Staatsflagge (Jahr variabel).",
    "hint": "Falklandinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/fk.png"
    }
  },
  {
    "id": "flag-fm",
    "title": "Flagge Mikronesien",
    "category": "country",
    "year": 1986,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Mikronesien – 1986, Unabhängigkeit",
    "hint": "Mikronesien",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/fm.png"
    }
  },
  {
    "id": "flag-fo",
    "title": "Flagge Färöer",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Färöer – Staatsflagge (Jahr variabel).",
    "hint": "Färöer",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/fo.png"
    }
  },
  {
    "id": "flag-fr",
    "title": "Flagge Frankreich",
    "category": "country",
    "year": 1958,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Frankreich – 1958, Fünfte Republik",
    "hint": "Frankreich",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/fr.png"
    }
  },
  {
    "id": "flag-ga",
    "title": "Flagge Gabun",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Gabun – 1960, Unabhängigkeit",
    "hint": "Gabun",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/ga.png"
    }
  },
  {
    "id": "flag-gb-eng",
    "title": "Flagge GB-ENG",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "GB-ENG – Staatsflagge (Jahr variabel).",
    "hint": "GB-ENG",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/gb-eng.png"
    }
  },
  {
    "id": "flag-gb-nir",
    "title": "Flagge GB-NIR",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "GB-NIR – Staatsflagge (Jahr variabel).",
    "hint": "GB-NIR",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/gb-nir.png"
    }
  },
  {
    "id": "flag-gb-sct",
    "title": "Flagge GB-SCT",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "GB-SCT – Staatsflagge (Jahr variabel).",
    "hint": "GB-SCT",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/gb-sct.png"
    }
  },
  {
    "id": "flag-gb-wls",
    "title": "Flagge GB-WLS",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "GB-WLS – Staatsflagge (Jahr variabel).",
    "hint": "GB-WLS",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/gb-wls.png"
    }
  },
  {
    "id": "flag-gb",
    "title": "Flagge Vereinigtes Königreich",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Vereinigtes Königreich – Staatsflagge (Jahr variabel).",
    "hint": "Vereinigtes Königreich",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/gb.png"
    }
  },
  {
    "id": "flag-gd",
    "title": "Flagge Grenada",
    "category": "country",
    "year": 1974,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Grenada – 1974, Unabhängigkeit",
    "hint": "Grenada",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/gd.png"
    }
  },
  {
    "id": "flag-ge",
    "title": "Flagge Georgien",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Georgien – 1991, Unabhängigkeit von der UdSSR",
    "hint": "Georgien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/ge.png"
    }
  },
  {
    "id": "flag-gf",
    "title": "Flagge Französisch-Guayana",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Französisch-Guayana – Staatsflagge (Jahr variabel).",
    "hint": "Französisch-Guayana",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/gf.png"
    }
  },
  {
    "id": "flag-gg",
    "title": "Flagge Guernsey",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Guernsey – Staatsflagge (Jahr variabel).",
    "hint": "Guernsey",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/gg.png"
    }
  },
  {
    "id": "flag-gh",
    "title": "Flagge Ghana",
    "category": "country",
    "year": 1957,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Ghana – 1957, Unabhängigkeit",
    "hint": "Ghana",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/gh.png"
    }
  },
  {
    "id": "flag-gi",
    "title": "Flagge Gibraltar",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Gibraltar – Staatsflagge (Jahr variabel).",
    "hint": "Gibraltar",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/gi.png"
    }
  },
  {
    "id": "flag-gl",
    "title": "Flagge Grönland",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Grönland – Staatsflagge (Jahr variabel).",
    "hint": "Grönland",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/gl.png"
    }
  },
  {
    "id": "flag-gm",
    "title": "Flagge Gambia",
    "category": "country",
    "year": 1965,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Gambia – 1965, Unabhängigkeit",
    "hint": "Gambia",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/gm.png"
    }
  },
  {
    "id": "flag-gn",
    "title": "Flagge Guinea",
    "category": "country",
    "year": 1958,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Guinea – 1958, Unabhängigkeit",
    "hint": "Guinea",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/gn.png"
    }
  },
  {
    "id": "flag-gp",
    "title": "Flagge Guadeloupe",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Guadeloupe – Staatsflagge (Jahr variabel).",
    "hint": "Guadeloupe",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/gp.png"
    }
  },
  {
    "id": "flag-gq",
    "title": "Flagge Äquatorialguinea",
    "category": "country",
    "year": 1968,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Äquatorialguinea – 1968, Unabhängigkeit",
    "hint": "Äquatorialguinea",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/gq.png"
    }
  },
  {
    "id": "flag-gr",
    "title": "Flagge Griechenland",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Griechenland – Staatsflagge (Jahr variabel).",
    "hint": "Griechenland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/gr.png"
    }
  },
  {
    "id": "flag-gs",
    "title": "Flagge Südgeorgien und die Südlichen Sandwichinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Südgeorgien und die Südlichen Sandwichinseln – Staatsflagge (Jahr variabel).",
    "hint": "Südgeorgien und die Südlichen Sandwichinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/gs.png"
    }
  },
  {
    "id": "flag-gt",
    "title": "Flagge Guatemala",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Guatemala – Staatsflagge (Jahr variabel).",
    "hint": "Guatemala",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/gt.png"
    }
  },
  {
    "id": "flag-gu",
    "title": "Flagge Guam",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Guam – Staatsflagge (Jahr variabel).",
    "hint": "Guam",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/gu.png"
    }
  },
  {
    "id": "flag-gw",
    "title": "Flagge Guinea-Bissau",
    "category": "country",
    "year": 1974,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Guinea-Bissau – 1974, Unabhängigkeit",
    "hint": "Guinea-Bissau",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/gw.png"
    }
  },
  {
    "id": "flag-gy",
    "title": "Flagge Guyana",
    "category": "country",
    "year": 1966,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Guyana – 1966, Unabhängigkeit",
    "hint": "Guyana",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/gy.png"
    }
  },
  {
    "id": "flag-hk",
    "title": "Flagge Sonderverwaltungsregion Hongkong",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Sonderverwaltungsregion Hongkong – Staatsflagge (Jahr variabel).",
    "hint": "Sonderverwaltungsregion Hongkong",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/hk.png"
    }
  },
  {
    "id": "flag-hm",
    "title": "Flagge Heard und McDonaldinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Heard und McDonaldinseln – Staatsflagge (Jahr variabel).",
    "hint": "Heard und McDonaldinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/hm.png"
    }
  },
  {
    "id": "flag-hn",
    "title": "Flagge Honduras",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Honduras – Staatsflagge (Jahr variabel).",
    "hint": "Honduras",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/hn.png"
    }
  },
  {
    "id": "flag-hr",
    "title": "Flagge Kroatien",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kroatien – 1991, Unabhängigkeit von Jugoslawien",
    "hint": "Kroatien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/hr.png"
    }
  },
  {
    "id": "flag-ht",
    "title": "Flagge Haiti",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Haiti – Staatsflagge (Jahr variabel).",
    "hint": "Haiti",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/ht.png"
    }
  },
  {
    "id": "flag-hu",
    "title": "Flagge Ungarn",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Üngarn – Staatsflagge (Jahr variabel).",
    "hint": "Üngarn",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/hu.png"
    }
  },
  {
    "id": "flag-id",
    "title": "Flagge Indonesien",
    "category": "country",
    "year": 1945,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Indonesien – 1945, Unabhängigkeit",
    "hint": "Indonesien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/id.png"
    }
  },
  {
    "id": "flag-ie",
    "title": "Flagge Irland",
    "category": "country",
    "year": 1921,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Irland – 1921, Unabhängigkeit (Freistaat)",
    "hint": "Irland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/ie.png"
    }
  },
  {
    "id": "flag-il",
    "title": "Flagge Israel",
    "category": "country",
    "year": 1948,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Israel – 1948, Staatsgründung",
    "hint": "Israel",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/il.png"
    }
  },
  {
    "id": "flag-im",
    "title": "Flagge Isle of Man",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Isle of Man – Staatsflagge (Jahr variabel).",
    "hint": "Isle of Man",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/im.png"
    }
  },
  {
    "id": "flag-in",
    "title": "Flagge Indien",
    "category": "country",
    "year": 1947,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Indien – 1947, Unabhängigkeit",
    "hint": "Indien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/in.png"
    }
  },
  {
    "id": "flag-io",
    "title": "Flagge Britisches Territorium im Indischen Ozean",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Britisches Territorium im Indischen Ozean – Staatsflagge (Jahr variabel).",
    "hint": "Britisches Territorium im Indischen Ozean",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/io.png"
    }
  },
  {
    "id": "flag-iq",
    "title": "Flagge Irak",
    "category": "country",
    "year": 2005,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Irak – 2005, Post-Saddam Verfassung",
    "hint": "Irak",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/iq.png"
    }
  },
  {
    "id": "flag-ir",
    "title": "Flagge Iran",
    "category": "country",
    "year": 1979,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Iran – 1979, Islamische Republik",
    "hint": "Iran",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/ir.png"
    }
  },
  {
    "id": "flag-is",
    "title": "Flagge Island",
    "category": "country",
    "year": 1944,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Island – 1944, Republikgründung",
    "hint": "Island",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/is.png"
    }
  },
  {
    "id": "flag-it",
    "title": "Flagge Italien",
    "category": "country",
    "year": 1948,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Italien – 1948, Republikanische Verfassung",
    "hint": "Italien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/it.png"
    }
  },
  {
    "id": "flag-je",
    "title": "Flagge Jersey",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Jersey – Staatsflagge (Jahr variabel).",
    "hint": "Jersey",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/je.png"
    }
  },
  {
    "id": "flag-jm",
    "title": "Flagge Jamaika",
    "category": "country",
    "year": 1962,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Jamaika – 1962, Unabhängigkeit",
    "hint": "Jamaika",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/jm.png"
    }
  },
  {
    "id": "flag-jo",
    "title": "Flagge Jordanien",
    "category": "country",
    "year": 1946,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Jordanien – 1946, Unabhängigkeit",
    "hint": "Jordanien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/jo.png"
    }
  },
  {
    "id": "flag-jp",
    "title": "Flagge Japan",
    "category": "country",
    "year": 1946,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Japan – 1946, Nachkriegsverfassung",
    "hint": "Japan",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/jp.png"
    }
  },
  {
    "id": "flag-ke",
    "title": "Flagge Kenia",
    "category": "country",
    "year": 1963,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kenia – 1963, Unabhängigkeit",
    "hint": "Kenia",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/ke.png"
    }
  },
  {
    "id": "flag-kg",
    "title": "Flagge Kirgisistan",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kirgisistan – 1991, Unabhängigkeit von der UdSSR",
    "hint": "Kirgisistan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/kg.png"
    }
  },
  {
    "id": "flag-kh",
    "title": "Flagge Kambodscha",
    "category": "country",
    "year": 1953,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kambodscha – 1953, Unabhängigkeit",
    "hint": "Kambodscha",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/kh.png"
    }
  },
  {
    "id": "flag-ki",
    "title": "Flagge Kiribati",
    "category": "country",
    "year": 1979,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kiribati – 1979, Unabhängigkeit",
    "hint": "Kiribati",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/ki.png"
    }
  },
  {
    "id": "flag-km",
    "title": "Flagge Komoren",
    "category": "country",
    "year": 1975,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Komoren – 1975, Unabhängigkeit",
    "hint": "Komoren",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/km.png"
    }
  },
  {
    "id": "flag-kn",
    "title": "Flagge St. Kitts und Nevis",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "St. Kitts und Nevis – Staatsflagge (Jahr variabel).",
    "hint": "St. Kitts und Nevis",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/kn.png"
    }
  },
  {
    "id": "flag-kp",
    "title": "Flagge Nordkorea",
    "category": "country",
    "year": 1948,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Nordkorea – 1948, Gründung der DVRK",
    "hint": "Nordkorea",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/kp.png"
    }
  },
  {
    "id": "flag-kr",
    "title": "Flagge Südkorea",
    "category": "country",
    "year": 1948,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Südkorea – 1948, Gründung der Republik",
    "hint": "Südkorea",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/kr.png"
    }
  },
  {
    "id": "flag-kw",
    "title": "Flagge Kuwait",
    "category": "country",
    "year": 1961,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kuwait – 1961, Unabhängigkeit",
    "hint": "Kuwait",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/kw.png"
    }
  },
  {
    "id": "flag-ky",
    "title": "Flagge Kaimaninseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kaimaninseln – Staatsflagge (Jahr variabel).",
    "hint": "Kaimaninseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/ky.png"
    }
  },
  {
    "id": "flag-kz",
    "title": "Flagge Kasachstan",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kasachstan – 1991, Unabhängigkeit von der UdSSR",
    "hint": "Kasachstan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/kz.png"
    }
  },
  {
    "id": "flag-la",
    "title": "Flagge Laos",
    "category": "country",
    "year": 1949,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Laos – 1949, Unabhängigkeit von Frankreich",
    "hint": "Laos",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/la.png"
    }
  },
  {
    "id": "flag-lb",
    "title": "Flagge Libanon",
    "category": "country",
    "year": 1943,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Libanon – 1943, Unabhängigkeit von Frankreich",
    "hint": "Libanon",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/lb.png"
    }
  },
  {
    "id": "flag-lc",
    "title": "Flagge St. Lucia",
    "category": "country",
    "year": 1979,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "St. Lucia – 1979, Unabhängigkeit",
    "hint": "St. Lucia",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/lc.png"
    }
  },
  {
    "id": "flag-li",
    "title": "Flagge Liechtenstein",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Liechtenstein – Staatsflagge (Jahr variabel).",
    "hint": "Liechtenstein",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/li.png"
    }
  },
  {
    "id": "flag-lk",
    "title": "Flagge Sri Lanka",
    "category": "country",
    "year": 1948,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Sri Lanka – 1948, Unabhängigkeit",
    "hint": "Sri Lanka",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/lk.png"
    }
  },
  {
    "id": "flag-lr",
    "title": "Flagge Liberia",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Liberia – Staatsflagge (Jahr variabel).",
    "hint": "Liberia",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/lr.png"
    }
  },
  {
    "id": "flag-ls",
    "title": "Flagge Lesotho",
    "category": "country",
    "year": 1966,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Lesotho – 1966, Unabhängigkeit",
    "hint": "Lesotho",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/ls.png"
    }
  },
  {
    "id": "flag-lt",
    "title": "Flagge Litauen",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Litauen – 1991, Wiederherstellung der Unabhängigkeit",
    "hint": "Litauen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/lt.png"
    }
  },
  {
    "id": "flag-lu",
    "title": "Flagge Luxemburg",
    "category": "country",
    "year": 1868,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Luxemburg – 1868, Aktuelle Verfassung",
    "hint": "Luxemburg",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/lu.png"
    }
  },
  {
    "id": "flag-lv",
    "title": "Flagge Lettland",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Lettland – 1991, Wiederherstellung der Unabhängigkeit",
    "hint": "Lettland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/lv.png"
    }
  },
  {
    "id": "flag-ly",
    "title": "Flagge Libyen",
    "category": "country",
    "year": 1951,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Libyen – 1951, Unabhängigkeit (Systemwechsel 2011)",
    "hint": "Libyen",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/ly.png"
    }
  },
  {
    "id": "flag-ma",
    "title": "Flagge Marokko",
    "category": "country",
    "year": 1956,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Marokko – 1956, Ende der Protektorate",
    "hint": "Marokko",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/ma.png"
    }
  },
  {
    "id": "flag-mc",
    "title": "Flagge Monaco",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Monaco – Staatsflagge (Jahr variabel).",
    "hint": "Monaco",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/mc.png"
    }
  },
  {
    "id": "flag-md",
    "title": "Flagge Republik Moldau",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Republik Moldau – Staatsflagge (Jahr variabel).",
    "hint": "Republik Moldau",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/md.png"
    }
  },
  {
    "id": "flag-me",
    "title": "Flagge Montenegro",
    "category": "country",
    "year": 2006,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Montenegro – 2006, Unabhängigkeit von Serbien",
    "hint": "Montenegro",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/me.png"
    }
  },
  {
    "id": "flag-mf",
    "title": "Flagge St. Martin",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "St. Martin – Staatsflagge (Jahr variabel).",
    "hint": "St. Martin",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/mf.png"
    }
  },
  {
    "id": "flag-mg",
    "title": "Flagge Madagaskar",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Madagaskar – 1960, Unabhängigkeit",
    "hint": "Madagaskar",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/mg.png"
    }
  },
  {
    "id": "flag-mh",
    "title": "Flagge Marshallinseln",
    "category": "country",
    "year": 1986,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Marshallinseln – 1986, Unabhängigkeit",
    "hint": "Marshallinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/mh.png"
    }
  },
  {
    "id": "flag-mk",
    "title": "Flagge Nordmazedonien",
    "category": "country",
    "year": 1992,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Nordmazedonien – 1992, Unabhängigkeit von Jugoslawien",
    "hint": "Nordmazedonien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/mk.png"
    }
  },
  {
    "id": "flag-ml",
    "title": "Flagge Mali",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Mali – 1960, Unabhängigkeit",
    "hint": "Mali",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/ml.png"
    }
  },
  {
    "id": "flag-mm",
    "title": "Flagge Myanmar",
    "category": "country",
    "year": 1948,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Myanmar – 1948, Unabhängigkeit",
    "hint": "Myanmar",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/mm.png"
    }
  },
  {
    "id": "flag-mn",
    "title": "Flagge Mongolei",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Mongolei – Staatsflagge (Jahr variabel).",
    "hint": "Mongolei",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/mn.png"
    }
  },
  {
    "id": "flag-mo",
    "title": "Flagge Sonderverwaltungsregion Macau",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Sonderverwaltungsregion Macau – Staatsflagge (Jahr variabel).",
    "hint": "Sonderverwaltungsregion Macau",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/mo.png"
    }
  },
  {
    "id": "flag-mp",
    "title": "Flagge Nördliche Marianen",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Nördliche Marianen – Staatsflagge (Jahr variabel).",
    "hint": "Nördliche Marianen",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/mp.png"
    }
  },
  {
    "id": "flag-mq",
    "title": "Flagge Martinique",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Martinique – Staatsflagge (Jahr variabel).",
    "hint": "Martinique",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/mq.png"
    }
  },
  {
    "id": "flag-mr",
    "title": "Flagge Mauretanien",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Mauretanien – 1960, Unabhängigkeit",
    "hint": "Mauretanien",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/mr.png"
    }
  },
  {
    "id": "flag-ms",
    "title": "Flagge Montserrat",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Montserrat – Staatsflagge (Jahr variabel).",
    "hint": "Montserrat",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/ms.png"
    }
  },
  {
    "id": "flag-mt",
    "title": "Flagge Malta",
    "category": "country",
    "year": 1964,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Malta – 1964, Unabhängigkeit",
    "hint": "Malta",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/mt.png"
    }
  },
  {
    "id": "flag-mu",
    "title": "Flagge Mauritius",
    "category": "country",
    "year": 1968,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Mauritius – 1968, Unabhängigkeit",
    "hint": "Mauritius",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/mu.png"
    }
  },
  {
    "id": "flag-mv",
    "title": "Flagge Malediven",
    "category": "country",
    "year": 1965,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Malediven – 1965, Unabhängigkeit",
    "hint": "Malediven",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/mv.png"
    }
  },
  {
    "id": "flag-mw",
    "title": "Flagge Malawi",
    "category": "country",
    "year": 1964,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Malawi – 1964, Unabhängigkeit",
    "hint": "Malawi",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/mw.png"
    }
  },
  {
    "id": "flag-mx",
    "title": "Flagge Mexiko",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Mexiko – Staatsflagge (Jahr variabel).",
    "hint": "Mexiko",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/mx.png"
    }
  },
  {
    "id": "flag-my",
    "title": "Flagge Malaysia",
    "category": "country",
    "year": 1957,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Malaysia – 1957, Unabhängigkeit",
    "hint": "Malaysia",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/my.png"
    }
  },
  {
    "id": "flag-mz",
    "title": "Flagge Mosambik",
    "category": "country",
    "year": 1975,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Mosambik – 1975, Unabhängigkeit",
    "hint": "Mosambik",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/mz.png"
    }
  },
  {
    "id": "flag-na",
    "title": "Flagge Namibia",
    "category": "country",
    "year": 1990,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Namibia – 1990, Unabhängigkeit",
    "hint": "Namibia",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/na.png"
    }
  },
  {
    "id": "flag-nc",
    "title": "Flagge Neukaledonien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Neukaledonien – Staatsflagge (Jahr variabel).",
    "hint": "Neukaledonien",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/nc.png"
    }
  },
  {
    "id": "flag-ne",
    "title": "Flagge Niger",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Niger – 1960, Unabhängigkeit",
    "hint": "Niger",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/ne.png"
    }
  },
  {
    "id": "flag-nf",
    "title": "Flagge Norfolkinsel",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Norfolkinsel – Staatsflagge (Jahr variabel).",
    "hint": "Norfolkinsel",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/nf.png"
    }
  },
  {
    "id": "flag-ng",
    "title": "Flagge Nigeria",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Nigeria – 1960, Unabhängigkeit",
    "hint": "Nigeria",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/ng.png"
    }
  },
  {
    "id": "flag-ni",
    "title": "Flagge Nicaragua",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Nicaragua – Staatsflagge (Jahr variabel).",
    "hint": "Nicaragua",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/ni.png"
    }
  },
  {
    "id": "flag-nl",
    "title": "Flagge Niederlande",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Niederlande – Staatsflagge (Jahr variabel).",
    "hint": "Niederlande",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/nl.png"
    }
  },
  {
    "id": "flag-no",
    "title": "Flagge Norwegen",
    "category": "country",
    "year": 1814,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Norwegen – 1814, Verfassung von Eidsvoll (Konstitutionelle Monarchie)",
    "hint": "Norwegen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/no.png"
    }
  },
  {
    "id": "flag-np",
    "title": "Flagge Nepal",
    "category": "country",
    "year": 2008,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Nepal – 2008, Ausrufung der Republik",
    "hint": "Nepal",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/np.png"
    }
  },
  {
    "id": "flag-nr",
    "title": "Flagge Nauru",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Nauru – Staatsflagge (Jahr variabel).",
    "hint": "Nauru",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/nr.png"
    }
  },
  {
    "id": "flag-nu",
    "title": "Flagge Niue",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Niue – Staatsflagge (Jahr variabel).",
    "hint": "Niue",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/nu.png"
    }
  },
  {
    "id": "flag-nz",
    "title": "Flagge Neuseeland",
    "category": "country",
    "year": 1890,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Neuseeland – 1890, Erlangung des Selbstverwaltungsstatus (Dominion-Status 1907)",
    "hint": "Neuseeland",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/nz.png"
    }
  },
  {
    "id": "flag-om",
    "title": "Flagge Oman",
    "category": "country",
    "year": 1970,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Öman – Staatsflagge (Jahr variabel).",
    "hint": "Öman",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/om.png"
    }
  },
  {
    "id": "flag-pa",
    "title": "Flagge Panama",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Panama – Staatsflagge (Jahr variabel).",
    "hint": "Panama",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/pa.png"
    }
  },
  {
    "id": "flag-pe",
    "title": "Flagge Peru",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Peru – Staatsflagge (Jahr variabel).",
    "hint": "Peru",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/pe.png"
    }
  },
  {
    "id": "flag-pf",
    "title": "Flagge Französisch-Polynesien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Französisch-Polynesien – Staatsflagge (Jahr variabel).",
    "hint": "Französisch-Polynesien",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/pf.png"
    }
  },
  {
    "id": "flag-pg",
    "title": "Flagge Papua-Neuguinea",
    "category": "country",
    "year": 1975,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Papua-Neuguinea – 1975, Unabhängigkeit",
    "hint": "Papua-Neuguinea",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/pg.png"
    }
  },
  {
    "id": "flag-ph",
    "title": "Flagge Philippinen",
    "category": "country",
    "year": 1987,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Philippinen – 1987, Aktuelle Verfassung",
    "hint": "Philippinen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/ph.png"
    }
  },
  {
    "id": "flag-pk",
    "title": "Flagge Pakistan",
    "category": "country",
    "year": 1947,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Pakistan – 1947, Unabhängigkeit",
    "hint": "Pakistan",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/pk.png"
    }
  },
  {
    "id": "flag-pl",
    "title": "Flagge Polen",
    "category": "country",
    "year": 1997,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Polen – 1997, Aktuelle Verfassung",
    "hint": "Polen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/pl.png"
    }
  },
  {
    "id": "flag-pm",
    "title": "Flagge St. Pierre und Miquelon",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "St. Pierre und Miquelon – Staatsflagge (Jahr variabel).",
    "hint": "St. Pierre und Miquelon",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/pm.png"
    }
  },
  {
    "id": "flag-pn",
    "title": "Flagge Pitcairninseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Pitcairninseln – Staatsflagge (Jahr variabel).",
    "hint": "Pitcairninseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/pn.png"
    }
  },
  {
    "id": "flag-pr",
    "title": "Flagge Puerto Rico",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Puerto Rico – Staatsflagge (Jahr variabel).",
    "hint": "Puerto Rico",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/pr.png"
    }
  },
  {
    "id": "flag-ps",
    "title": "Flagge Palästinensische Autonomiegebiete",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Palästinensische Autonomiegebiete – Staatsflagge (Jahr variabel).",
    "hint": "Palästinensische Autonomiegebiete",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/ps.png"
    }
  },
  {
    "id": "flag-pt",
    "title": "Flagge Portugal",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Portugal – Staatsflagge (Jahr variabel).",
    "hint": "Portugal",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/pt.png"
    }
  },
  {
    "id": "flag-pw",
    "title": "Flagge Palau",
    "category": "country",
    "year": 1981,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Palau – 1981, Verfassung (Souveränität 1994)",
    "hint": "Palau",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/pw.png"
    }
  },
  {
    "id": "flag-py",
    "title": "Flagge Paraguay",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Paraguay – Staatsflagge (Jahr variabel).",
    "hint": "Paraguay",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/py.png"
    }
  },
  {
    "id": "flag-qa",
    "title": "Flagge Katar",
    "category": "country",
    "year": 1971,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Katar – 1971, Unabhängigkeit",
    "hint": "Katar",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/qa.png"
    }
  },
  {
    "id": "flag-re",
    "title": "Flagge Réunion",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Réunion – Staatsflagge (Jahr variabel).",
    "hint": "Réunion",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/re.png"
    }
  },
  {
    "id": "flag-ro",
    "title": "Flagge Rumänien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Rumänien – Staatsflagge (Jahr variabel).",
    "hint": "Rumänien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/ro.png"
    }
  },
  {
    "id": "flag-rs",
    "title": "Flagge Serbien",
    "category": "country",
    "year": 2006,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Serbien – 2006, Auflösung der Union mit Montenegro",
    "hint": "Serbien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/rs.png"
    }
  },
  {
    "id": "flag-ru",
    "title": "Flagge Russland",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Russland – 1991, Russische Föderation (Post-Sowjet)",
    "hint": "Russland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/ru.png"
    }
  },
  {
    "id": "flag-rw",
    "title": "Flagge Ruanda",
    "category": "country",
    "year": 1962,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Ruanda – 1962, Unabhängigkeit",
    "hint": "Ruanda",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/rw.png"
    }
  },
  {
    "id": "flag-sa",
    "title": "Flagge Saudi-Arabien",
    "category": "country",
    "year": 1932,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Saudi-Arabien – 1932, Vereinigung der Königreiche",
    "hint": "Saudi-Arabien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/sa.png"
    }
  },
  {
    "id": "flag-sb",
    "title": "Flagge Salomonen",
    "category": "country",
    "year": 1978,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Salomonen – 1978, Unabhängigkeit",
    "hint": "Salomonen",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/sb.png"
    }
  },
  {
    "id": "flag-sc",
    "title": "Flagge Seychellen",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Seychellen – Staatsflagge (Jahr variabel).",
    "hint": "Seychellen",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/sc.png"
    }
  },
  {
    "id": "flag-sd",
    "title": "Flagge Sudan",
    "category": "country",
    "year": 1956,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Sudan – 1956, Unabhängigkeit",
    "hint": "Sudan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/sd.png"
    }
  },
  {
    "id": "flag-se",
    "title": "Flagge Schweden",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Schweden – Staatsflagge (Jahr variabel).",
    "hint": "Schweden",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/se.png"
    }
  },
  {
    "id": "flag-sg",
    "title": "Flagge Singapur",
    "category": "country",
    "year": 1965,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Singapur – 1965, Trennung von Malaysia",
    "hint": "Singapur",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/sg.png"
    }
  },
  {
    "id": "flag-sh",
    "title": "Flagge St. Helena",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "St. Helena – Staatsflagge (Jahr variabel).",
    "hint": "St. Helena",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/sh.png"
    }
  },
  {
    "id": "flag-si",
    "title": "Flagge Slowenien",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Slowenien – 1991, Unabhängigkeit von Jugoslawien",
    "hint": "Slowenien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/si.png"
    }
  },
  {
    "id": "flag-sj",
    "title": "Flagge Spitzbergen und Jan Mayen",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Spitzbergen und Jan Mayen – Staatsflagge (Jahr variabel).",
    "hint": "Spitzbergen und Jan Mayen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/sj.png"
    }
  },
  {
    "id": "flag-sk",
    "title": "Flagge Slowakei",
    "category": "country",
    "year": 1993,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Slowakei – 1993, Teilung der Tschechoslowakei",
    "hint": "Slowakei",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/sk.png"
    }
  },
  {
    "id": "flag-sl",
    "title": "Flagge Sierra Leone",
    "category": "country",
    "year": 1961,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Sierra Leone – 1961, Unabhängigkeit",
    "hint": "Sierra Leone",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/sl.png"
    }
  },
  {
    "id": "flag-sm",
    "title": "Flagge San Marino",
    "category": "country",
    "year": 1600,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "San Marino – 1600, Verabschiedung der Statuten (älteste Republik)",
    "hint": "San Marino",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/sm.png"
    }
  },
  {
    "id": "flag-sn",
    "title": "Flagge Senegal",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Senegal – 1960, Unabhängigkeit",
    "hint": "Senegal",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/sn.png"
    }
  },
  {
    "id": "flag-so",
    "title": "Flagge Somalia",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Somalia – 1960, Unabhängigkeit",
    "hint": "Somalia",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/so.png"
    }
  },
  {
    "id": "flag-sr",
    "title": "Flagge Suriname",
    "category": "country",
    "year": 1975,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Suriname – 1975, Unabhängigkeit",
    "hint": "Suriname",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/sr.png"
    }
  },
  {
    "id": "flag-ss",
    "title": "Flagge Südsudan",
    "category": "country",
    "year": 2011,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Südsudan – 2011, Unabhängigkeit vom Sudan",
    "hint": "Südsudan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/ss.png"
    }
  },
  {
    "id": "flag-st",
    "title": "Flagge São Tomé und Príncipe",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "São Tomé und Príncipe – Staatsflagge (Jahr variabel).",
    "hint": "São Tomé und Príncipe",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/st.png"
    }
  },
  {
    "id": "flag-sv",
    "title": "Flagge El Salvador",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "El Salvador – Staatsflagge (Jahr variabel).",
    "hint": "El Salvador",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/sv.png"
    }
  },
  {
    "id": "flag-sx",
    "title": "Flagge Sint Maarten",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Sint Maarten – Staatsflagge (Jahr variabel).",
    "hint": "Sint Maarten",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/sx.png"
    }
  },
  {
    "id": "flag-sy",
    "title": "Flagge Syrien",
    "category": "country",
    "year": 1946,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Syrien – 1946, Unabhängigkeit von Frankreich",
    "hint": "Syrien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/sy.png"
    }
  },
  {
    "id": "flag-sz",
    "title": "Flagge Eswatini",
    "category": "country",
    "year": 1968,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Eswatini – 1968, Unabhängigkeit",
    "hint": "Eswatini",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/sz.png"
    }
  },
  {
    "id": "flag-tc",
    "title": "Flagge Turks- und Caicosinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Turks- und Caicosinseln – Staatsflagge (Jahr variabel).",
    "hint": "Turks- und Caicosinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/tc.png"
    }
  },
  {
    "id": "flag-td",
    "title": "Flagge Tschad",
    "category": "country",
    "year": 2022,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Tschad – 2022, Neue Verfassung/Übergangsrat",
    "hint": "Tschad",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/td.png"
    }
  },
  {
    "id": "flag-tf",
    "title": "Flagge Französische Süd- und Antarktisgebiete",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Französische Süd- und Antarktisgebiete – Staatsflagge (Jahr variabel).",
    "hint": "Französische Süd- und Antarktisgebiete",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/tf.png"
    }
  },
  {
    "id": "flag-tg",
    "title": "Flagge Togo",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Togo – 1960, Unabhängigkeit",
    "hint": "Togo",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/tg.png"
    }
  },
  {
    "id": "flag-th",
    "title": "Flagge Thailand",
    "category": "country",
    "year": 1932,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Thailand – 1932, Ende der absoluten Monarchie",
    "hint": "Thailand",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/th.png"
    }
  },
  {
    "id": "flag-tj",
    "title": "Flagge Tadschikistan",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Tadschikistan – 1991, Unabhängigkeit von der UdSSR",
    "hint": "Tadschikistan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/tj.png"
    }
  },
  {
    "id": "flag-tk",
    "title": "Flagge Tokelau",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Tokelau – Staatsflagge (Jahr variabel).",
    "hint": "Tokelau",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/tk.png"
    }
  },
  {
    "id": "flag-tl",
    "title": "Flagge Timor-Leste",
    "category": "country",
    "year": 2002,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Timor-Leste – Staatsflagge (Jahr variabel).",
    "hint": "Timor-Leste",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/tl.png"
    }
  },
  {
    "id": "flag-tm",
    "title": "Flagge Turkmenistan",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Turkmenistan – 1991, Unabhängigkeit von der UdSSR",
    "hint": "Turkmenistan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/tm.png"
    }
  },
  {
    "id": "flag-tn",
    "title": "Flagge Tunesien",
    "category": "country",
    "year": 2014,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Tunesien – 2014, Neue Verfassung (Arabischer Frühling)",
    "hint": "Tunesien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/tn.png"
    }
  },
  {
    "id": "flag-to",
    "title": "Flagge Tonga",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Tonga – Staatsflagge (Jahr variabel).",
    "hint": "Tonga",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/to.png"
    }
  },
  {
    "id": "flag-tr",
    "title": "Flagge Türkei",
    "category": "country",
    "year": 1923,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Türkei – 1923, Ausrufung der Republik",
    "hint": "Türkei",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/tr.png"
    }
  },
  {
    "id": "flag-tt",
    "title": "Flagge Trinidad und Tobago",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Trinidad und Tobago – Staatsflagge (Jahr variabel).",
    "hint": "Trinidad und Tobago",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/tt.png"
    }
  },
  {
    "id": "flag-tv",
    "title": "Flagge Tuvalu",
    "category": "country",
    "year": 1978,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Tuvalu – 1978, Unabhängigkeit",
    "hint": "Tuvalu",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/tv.png"
    }
  },
  {
    "id": "flag-tw",
    "title": "Flagge Taiwan",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Taiwan – Staatsflagge (Jahr variabel).",
    "hint": "Taiwan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/tw.png"
    }
  },
  {
    "id": "flag-tz",
    "title": "Flagge Tansania",
    "category": "country",
    "year": 1961,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Tansania – 1961, Unabhängigkeit (als Tanganjika)",
    "hint": "Tansania",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/tz.png"
    }
  },
  {
    "id": "flag-ua",
    "title": "Flagge Ukraine",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Ükraine – Staatsflagge (Jahr variabel).",
    "hint": "Ükraine",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/ua.png"
    }
  },
  {
    "id": "flag-ug",
    "title": "Flagge Uganda",
    "category": "country",
    "year": 1962,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Üganda – Staatsflagge (Jahr variabel).",
    "hint": "Üganda",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/ug.png"
    }
  },
  {
    "id": "flag-um",
    "title": "Flagge Amerikanische Überseeinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Ämerikanische Überseeinseln – Staatsflagge (Jahr variabel).",
    "hint": "Ämerikanische Überseeinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/um.png"
    }
  },
  {
    "id": "flag-us",
    "title": "Flagge Vereinigte Staaten",
    "category": "country",
    "year": 1789,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Vereinigte Staaten – Staatsflagge (Jahr variabel).",
    "hint": "Vereinigte Staaten",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/us.png"
    }
  },
  {
    "id": "flag-uy",
    "title": "Flagge Uruguay",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Üruguay – Staatsflagge (Jahr variabel).",
    "hint": "Üruguay",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/uy.png"
    }
  },
  {
    "id": "flag-uz",
    "title": "Flagge Usbekistan",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Üsbekistan – Staatsflagge (Jahr variabel).",
    "hint": "Üsbekistan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/uz.png"
    }
  },
  {
    "id": "flag-va",
    "title": "Flagge Vatikanstadt",
    "category": "country",
    "year": 1929,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Vatikanstadt – 1929, Lateranverträge",
    "hint": "Vatikanstadt",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/va.png"
    }
  },
  {
    "id": "flag-vc",
    "title": "Flagge St. Vincent und die Grenadinen",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "St. Vincent und die Grenadinen – Staatsflagge (Jahr variabel).",
    "hint": "St. Vincent und die Grenadinen",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/vc.png"
    }
  },
  {
    "id": "flag-ve",
    "title": "Flagge Venezuela",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Venezuela – Staatsflagge (Jahr variabel).",
    "hint": "Venezuela",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/ve.png"
    }
  },
  {
    "id": "flag-vg",
    "title": "Flagge Britische Jungferninseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Britische Jungferninseln – Staatsflagge (Jahr variabel).",
    "hint": "Britische Jungferninseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/vg.png"
    }
  },
  {
    "id": "flag-vi",
    "title": "Flagge Amerikanische Jungferninseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Ämerikanische Jungferninseln – Staatsflagge (Jahr variabel).",
    "hint": "Ämerikanische Jungferninseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/vi.png"
    }
  },
  {
    "id": "flag-vn",
    "title": "Flagge Vietnam",
    "category": "country",
    "year": 1975,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Vietnam – 1975, Wiedervereinigung",
    "hint": "Vietnam",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/vn.png"
    }
  },
  {
    "id": "flag-vu",
    "title": "Flagge Vanuatu",
    "category": "country",
    "year": 1980,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Vanuatu – 1980, Unabhängigkeit",
    "hint": "Vanuatu",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/vu.png"
    }
  },
  {
    "id": "flag-wf",
    "title": "Flagge Wallis und Futuna",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Wallis und Futuna – Staatsflagge (Jahr variabel).",
    "hint": "Wallis und Futuna",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/wf.png"
    }
  },
  {
    "id": "flag-ws",
    "title": "Flagge Samoa",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Samoa – Staatsflagge (Jahr variabel).",
    "hint": "Samoa",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/ws.png"
    }
  },
  {
    "id": "flag-xk",
    "title": "Flagge Kosovo",
    "category": "country",
    "year": 2008,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Kosovo – 2008, Unabhängigkeit (Teilweise anerkannt)",
    "hint": "Kosovo",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/flags/xk.png"
    }
  },
  {
    "id": "flag-ye",
    "title": "Flagge Jemen",
    "category": "country",
    "year": 1990,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Jemen – 1990, Wiedervereinigung",
    "hint": "Jemen",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/ye.png"
    }
  },
  {
    "id": "flag-yt",
    "title": "Flagge Mayotte",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Mayotte – Staatsflagge (Jahr variabel).",
    "hint": "Mayotte",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/flags/yt.png"
    }
  },
  {
    "id": "flag-za",
    "title": "Flagge Südafrika",
    "category": "country",
    "year": 1994,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Südafrika – 1994, Erste freie Wahlen (Ende Apartheid)",
    "hint": "Südafrika",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/za.png"
    }
  },
  {
    "id": "flag-zm",
    "title": "Flagge Sambia",
    "category": "country",
    "year": 1964,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Sambia – 1964, Unabhängigkeit",
    "hint": "Sambia",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/zm.png"
    }
  },
  {
    "id": "flag-zw",
    "title": "Flagge Simbabwe",
    "category": "country",
    "year": 1980,
    "cue": "Zu welchem Land gehört diese Flagge und wann wurde es gegründet?",
    "answer": "Simbabwe – 1980, Unabhängigkeit",
    "hint": "Simbabwe",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/flags/zw.png"
    }
  }
];


