// AUTO-GENERATED by scripts/generate-outline-cards.mjs
// Do not edit manually.
import { Card } from './types';

export const outlineCards: Card[] = [
  {
    "id": "outline-ad",
    "title": "Umriss Andorra",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Andorra – 1993, Erste Verfassung (Souveränität)",
    "hint": "Andorra",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ad.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ae",
    "title": "Umriss Vereinigte Arabische Emirate",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Vereinigte Arabische Emirate – 1971, Gründung der Föderation.",
    "hint": "Vereinigte Arabische Emirate",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ae.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-af",
    "title": "Umriss Afghanistan",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äfghanistan – 2021, Machtübernahme der Taliban.",
    "hint": "Äfghanistan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/af.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ag",
    "title": "Umriss Antigua und Barbuda",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äntigua und Barbuda – 1981, Unabhängigkeit vom UK.",
    "hint": "Äntigua und Barbuda",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ag.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ai",
    "title": "Umriss Anguilla",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Änguilla – 1982, Aktuelle Verfassungsordnung.",
    "hint": "Änguilla",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ai.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-al",
    "title": "Umriss Albanien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Älbanien – 1998, Aktuelle Verfassung.",
    "hint": "Älbanien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/al.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-am",
    "title": "Umriss Armenien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Ärmenie – 2015, Wechsel zum Parlamentarismus.",
    "hint": "Ärmenien",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/am.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ao",
    "title": "Umriss Angola",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Ängola – 2010, Aktuelle Verfassung.",
    "hint": "Ängola",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ao.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-as",
    "title": "Umriss Amerikanisch-Samoa",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Samoa – 1962, Unabhängigkeit.",
    "hint": "Ämerikanisch-Samoa",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/as.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-at",
    "title": "Umriss Österreich",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Österreich – 1945, Zweite Republik",
    "hint": "Österreich",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/at.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-au",
    "title": "Umriss Australien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äustralien – 1986, Australia Act.",
    "hint": "Äustralien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/au.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-aw",
    "title": "Umriss Aruba",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äruba – 1986, Status Aparte.",
    "hint": "Äruba",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/aw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ax",
    "title": "Umriss Ålandinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Ålandinseln – 1993, Neue Autonomie-Akte.",
    "hint": "Ålandinseln",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ax.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-az",
    "title": "Umriss Aserbaidschan",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äserbaidschan – 1995, Unabhängigkeitsverfassung.",
    "hint": "Äserbaidschan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/az.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ba",
    "title": "Umriss Bosnien und Herzegowina",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bosnien und Herzegowina – 1995, Dayton-Abkommen.",
    "hint": "Bosnien und Herzegowina",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ba.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bb",
    "title": "Umriss Barbados",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Barbados – 2021, Übergang zur Republik",
    "hint": "Barbados",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bb.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bd",
    "title": "Umriss Bangladesch",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bangladesch – 1971, Unabhängigkeit",
    "hint": "Bangladesch",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/bd.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-be",
    "title": "Umriss Belgien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Belgien – 1831, Unabhängigkeit und Verfassung nach der Revolution",
    "hint": "Belgien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/be.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bf",
    "title": "Umriss Burkina Faso",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Burkina Faso – 1960, Unabhängigkeit",
    "hint": "Burkina Faso",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/bf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bg",
    "title": "Umriss Bulgarien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bulgarien – 1991, Post-sozialistische Verfassung.",
    "hint": "Bulgarien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/bg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bh",
    "title": "Umriss Bahrain",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bahrain – 1971, Unabhängigkeit",
    "hint": "Bahrain",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bh.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bi",
    "title": "Umriss Burundi",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Burundi – 1962, Unabhängigkeit",
    "hint": "Burundi",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/bi.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bj",
    "title": "Umriss Benin",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Benin – 1960, Unabhängigkeit",
    "hint": "Benin",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/bj.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bl",
    "title": "Umriss St. Barthélemy",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "St. Barthélemy – 2007, Überseekollektiv.",
    "hint": "St. Barthélemy",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bl.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bm",
    "title": "Umriss Bermuda",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bermuda – 1968, Verfassungsordnung.",
    "hint": "Bermuda",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bn",
    "title": "Umriss Brunei Darussalam",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Brunei Darussalam – 1984, Unabhängigkeit.",
    "hint": "Brunei Darussalam",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bo",
    "title": "Umriss Bolivien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bolivien – 2009, Plurinationaler Staat.",
    "hint": "Bolivien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/bo.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bq",
    "title": "Umriss Karibische Niederlande",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Niederlande – 1983, Totalrevision.",
    "hint": "Karibische Niederlande",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bq.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-br",
    "title": "Umriss Brasilien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Brasilien – 1988, Aktuelle Verfassung",
    "hint": "Brasilien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/br.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bs",
    "title": "Umriss Bahamas",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bahamas – 1973, Unabhängigkeit",
    "hint": "Bahamas",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bs.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bt",
    "title": "Umriss Bhutan",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bhutan – 2008, Konstitutionelle Monarchie.",
    "hint": "Bhutan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bt.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bv",
    "title": "Umriss Bouvetinsel",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bouvetinsel – 1930, Norwegische Souveränität.",
    "hint": "Bouvetinsel",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bv.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bw",
    "title": "Umriss Botsuana",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Botsuana – 1966, Unabhängigkeit.",
    "hint": "Botsuana",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-by",
    "title": "Umriss Belarus",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Belarus – 1991, Unabhängigkeit von der UdSSR",
    "hint": "Belarus",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/by.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bz",
    "title": "Umriss Belize",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Belize – 1981, Unabhängigkeit",
    "hint": "Belize",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ca",
    "title": "Umriss Kanada",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kanada – 1867, British North America Act (Beginn der Eigenstaatlichkeit)",
    "hint": "Kanada",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ca.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cc",
    "title": "Umriss Kokosinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kokosinseln – 1984, Integration in Australien.",
    "hint": "Kokosinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/cc.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cd",
    "title": "Umriss Kongo-Kinshasa",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kongo-Kinshasa – 2006, III. Republik.",
    "hint": "Kongo-Kinshasa",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/cd.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cf",
    "title": "Umriss Zentralafrikanische Republik",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Zentralafrikanische Republik – 2023, Neue Verfassung.",
    "hint": "Zentralafrikanische Republik",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/cf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cg",
    "title": "Umriss Kongo-Brazzaville",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kongo-Brazzaville – 2015, Neue Verfassung.",
    "hint": "Kongo-Brazzaville",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/cg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ch",
    "title": "Umriss Schweiz",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Schweiz – 1848, Gründung des modernen Bundesstaates",
    "hint": "Schweiz",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ch.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ci",
    "title": "Umriss Côte d’Ivoire",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Côte d’Ivoire – 2016, III. Republik.",
    "hint": "Côte d’Ivoire",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ci.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ck",
    "title": "Umriss Cookinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Cookinseln – 1965, Selbstverwaltung.",
    "hint": "Cookinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ck.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cl",
    "title": "Umriss Chile",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Chile – 2005, Verfassungsreform.",
    "hint": "Chile",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/cl.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cm",
    "title": "Umriss Kamerun",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kamerun – 1960, Unabhängigkeit",
    "hint": "Kamerun",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/cm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cn",
    "title": "Umriss China",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "China – 1982, Aktuelle Verfassung.",
    "hint": "China",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/cn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-co",
    "title": "Umriss Kolumbien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kolumbien – 1991, Moderne Verfassung.",
    "hint": "Kolumbien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/co.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cr",
    "title": "Umriss Costa Rica",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Costa Rica – 1949, Post-Bürgerkriegsverfassung.",
    "hint": "Costa Rica",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/cr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cu",
    "title": "Umriss Kuba",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kuba – 2019, Neue Verfassung",
    "hint": "Kuba",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/cu.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cv",
    "title": "Umriss Cabo Verde",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Cabo Verde – 1992, Demokratisierung.",
    "hint": "Cabo Verde",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/cv.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cw",
    "title": "Umriss Curaçao",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Curaçao – 2010, Eigenständiges Land.",
    "hint": "Curaçao",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/cw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cx",
    "title": "Umriss Weihnachtsinsel",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Weihnachtsinsel – 1958, Australische Verwaltung.",
    "hint": "Weihnachtsinsel",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/cx.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cy",
    "title": "Umriss Zypern",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Zypern – 1960, Unabhängigkeit",
    "hint": "Zypern",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/cy.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cz",
    "title": "Umriss Tschechien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Tschechien – 1993, Teilung der Tschechoslowakei",
    "hint": "Tschechien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/cz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-de",
    "title": "Umriss Deutschland",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Deutschland – 1949, Grundgesetz (BRD)",
    "hint": "Deutschland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/de.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-dj",
    "title": "Umriss Dschibuti",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Dschibuti – 1977, Unabhängigkeit",
    "hint": "Dschibuti",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/dj.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-dk",
    "title": "Umriss Dänemark",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Dänemark – 1953, Verfassungsänderung.",
    "hint": "Dänemark",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/dk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-dm",
    "title": "Umriss Dominica",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Dominica – 1978, Unabhängigkeit",
    "hint": "Dominica",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/dm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-do",
    "title": "Umriss Dominikanische Republik",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Dominikanische Republik – 2015, Verfassungsreform.",
    "hint": "Dominikanische Republik",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/do.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-dz",
    "title": "Umriss Algerien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Älgerien – 2020, Post-Hirak-Verfassung.",
    "hint": "Älgerien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/dz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ec",
    "title": "Umriss Ecuador",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Ecuador – 2008, Aktuelle Verfassung.",
    "hint": "Ecuador",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ec.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ee",
    "title": "Umriss Estland",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Estland – 1991, Wiederherstellung der Unabhängigkeit",
    "hint": "Estland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ee.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-eg",
    "title": "Umriss Ägypten",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Ägypten – 1953, Ausrufung der Republik",
    "hint": "Ägypten",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/eg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-eh",
    "title": "Umriss Westsahara",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Westsahara – 1976, Proklamation der D.A.R.S..",
    "hint": "Westsahara",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/eh.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-er",
    "title": "Umriss Eritrea",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äthiopien – 1995, Föderale Verfassung.",
    "hint": "Eritrea",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/er.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-es",
    "title": "Umriss Spanien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Spanien – 1978, Demokratische Verfassung",
    "hint": "Spanien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/es.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-et",
    "title": "Umriss Äthiopien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äthiopien – 1995, Föderale Verfassung.",
    "hint": "Äthiopien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/et.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-fi",
    "title": "Umriss Finnland",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Finnland – 2000, Neue Verfassung.",
    "hint": "Finnland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/fi.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-fj",
    "title": "Umriss Fidschi",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Fidschi – 1970, Unabhängigkeit",
    "hint": "Fidschi",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/fj.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-fk",
    "title": "Umriss Falklandinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Falklandinseln – 2009, Verfassungsordnung.",
    "hint": "Falklandinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/fk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-fo",
    "title": "Umriss Färöer",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Färöer – 1948, Autonomiegesetz.",
    "hint": "Färöer",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/fo.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-fr",
    "title": "Umriss Frankreich",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Frankreich – 1958, Fünfte Republik",
    "hint": "Frankreich",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/fr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ga",
    "title": "Umriss Gabun",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Gabun – 1960, Unabhängigkeit",
    "hint": "Gabun",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ga.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gb",
    "title": "Umriss Vereinigtes Königreich",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Vereinigtes Königreich – 1922, Heutiger Staatsrahmen.",
    "hint": "Vereinigtes Königreich",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/gb.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gd",
    "title": "Umriss Grenada",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Grenada – 1974, Unabhängigkeit",
    "hint": "Grenada",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gd.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ge",
    "title": "Umriss Georgien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Georgien – 1991, Unabhängigkeit von der UdSSR",
    "hint": "Georgien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ge.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gf",
    "title": "Umriss Französisch-Guayana",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Französisch-Guayana – 1946, Überseedépartement.",
    "hint": "Französisch-Guayana",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gg",
    "title": "Umriss Guernsey",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Guernsey – 2005, Regierungsreform.",
    "hint": "Guernsey",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/gg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gh",
    "title": "Umriss Ghana",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Ghana – 1957, Unabhängigkeit",
    "hint": "Ghana",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/gh.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gi",
    "title": "Umriss Gibraltar",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Gibraltar – 2006, Verfassungsordnung.",
    "hint": "Gibraltar",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/gi.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gl",
    "title": "Umriss Grönland",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Grönland – 2009, Self-Government.",
    "hint": "Grönland",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gl.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gm",
    "title": "Umriss Gambia",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Gambia – 1965, Unabhängigkeit",
    "hint": "Gambia",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gn",
    "title": "Umriss Guinea",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Guinea – 1958, Unabhängigkeit",
    "hint": "Guinea",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/gn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gp",
    "title": "Umriss Guadeloupe",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Guadeloupe – 1946, Überseedépartement.",
    "hint": "Guadeloupe",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gp.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gq",
    "title": "Umriss Äquatorialguinea",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äquatorialguinea – 1968, Unabhängigkeit",
    "hint": "Äquatorialguinea",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gq.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gr",
    "title": "Umriss Griechenland",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Griechenland – 1975, Post-Diktatur-Verfassung.",
    "hint": "Griechenland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/gr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gs",
    "title": "Umriss Südgeorgien und die Südlichen Sandwichinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Südgeorgien und die Südlichen Sandwichinseln – 1985, Eigenständiges Territorium.",
    "hint": "Südgeorgien und die Südlichen Sandwichinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gs.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gt",
    "title": "Umriss Guatemala",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Guatemala – 1985, Demokratische Verfassung.",
    "hint": "Guatemala",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/gt.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gu",
    "title": "Umriss Guam",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Guam – 1950, Organic Act.",
    "hint": "Guam",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gu.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gw",
    "title": "Umriss Guinea-Bissau",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Guinea-Bissau – 1974, Unabhängigkeit",
    "hint": "Guinea-Bissau",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gy",
    "title": "Umriss Guyana",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Guyana – 1966, Unabhängigkeit",
    "hint": "Guyana",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gy.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-hk",
    "title": "Umriss Sonderverwaltungsregion Hongkong",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Hongkong – 1997, Übergabe an China.",
    "hint": "Sonderverwaltungsregion Hongkong",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/hk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-hm",
    "title": "Umriss Heard und McDonaldinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Heard und McDonaldinseln – 1947, Australische Verwaltung.",
    "hint": "Heard und McDonaldinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/hm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-hn",
    "title": "Umriss Honduras",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Honduras – 1982, Demokratisierung.",
    "hint": "Honduras",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/hn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-hr",
    "title": "Umriss Kroatien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kroatien – 1991, Unabhängigkeit von Jugoslawien",
    "hint": "Kroatien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/hr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ht",
    "title": "Umriss Haiti",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Haiti – 1987, Post-Duvalier-Verfassung.",
    "hint": "Haiti",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ht.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-id",
    "title": "Umriss Indonesien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Indonesien – 1945, Unabhängigkeit",
    "hint": "Indonesien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/id.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ie",
    "title": "Umriss Irland",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Irland – 1921, Unabhängigkeit (Freistaat)",
    "hint": "Irland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ie.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-il",
    "title": "Umriss Israel",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Israel – 1948, Staatsgründung",
    "hint": "Israel",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/il.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-im",
    "title": "Umriss Isle of Man",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Isle of Man – 1979, Tynwald-Jubiläum.",
    "hint": "Isle of Man",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/im.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-in",
    "title": "Umriss Indien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Indien – 1947, Unabhängigkeit",
    "hint": "Indien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/in.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-io",
    "title": "Umriss Britisches Territorium im Indischen Ozean",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Britisches Territorium im Indischen Ozean – 1965, Eigenes Territorium.",
    "hint": "Britisches Territorium im Indischen Ozean",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/io.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-iq",
    "title": "Umriss Irak",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Irak – 2005, Post-Saddam Verfassung",
    "hint": "Irak",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/iq.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ir",
    "title": "Umriss Iran",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Iran – 1979, Islamische Republik",
    "hint": "Iran",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ir.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-is",
    "title": "Umriss Island",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Island – 1944, Republikgründung",
    "hint": "Island",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/is.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-it",
    "title": "Umriss Italien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Italien – 1948, Republikanische Verfassung",
    "hint": "Italien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/it.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-jm",
    "title": "Umriss Jamaika",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Jamaika – 1962, Unabhängigkeit",
    "hint": "Jamaika",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/jm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-jo",
    "title": "Umriss Jordanien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Jordanien – 1946, Unabhängigkeit",
    "hint": "Jordanien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/jo.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-jp",
    "title": "Umriss Japan",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Japan – 1946, Nachkriegsverfassung",
    "hint": "Japan",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/jp.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ke",
    "title": "Umriss Kenia",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kenia – 1963, Unabhängigkeit",
    "hint": "Kenia",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ke.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-kg",
    "title": "Umriss Kirgisistan",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kirgisistan – 1991, Unabhängigkeit von der UdSSR",
    "hint": "Kirgisistan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/kg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-kh",
    "title": "Umriss Kambodscha",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kambodscha – 1953, Unabhängigkeit",
    "hint": "Kambodscha",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/kh.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ki",
    "title": "Umriss Kiribati",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kiribati – 1979, Unabhängigkeit",
    "hint": "Kiribati",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ki.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-km",
    "title": "Umriss Komoren",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Komoren – 1975, Unabhängigkeit",
    "hint": "Komoren",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/km.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-kn",
    "title": "Umriss St. Kitts und Nevis",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "St. Kitts und Nevis – 1983, Unabhängigkeit.",
    "hint": "St. Kitts und Nevis",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/kn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-kp",
    "title": "Umriss Nordkorea",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Nordkorea – 1948, Gründung der DVRK",
    "hint": "Nordkorea",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/kp.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-kr",
    "title": "Umriss Südkorea",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Südkorea – 1948, Gründung der Republik",
    "hint": "Südkorea",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/kr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-kw",
    "title": "Umriss Kuwait",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kuwait – 1961, Unabhängigkeit",
    "hint": "Kuwait",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/kw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ky",
    "title": "Umriss Kaimaninseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kaimaninseln – 2009, Verfassungsordnung.",
    "hint": "Kaimaninseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ky.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-kz",
    "title": "Umriss Kasachstan",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kasachstan – 1991, Unabhängigkeit von der UdSSR",
    "hint": "Kasachstan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/kz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-la",
    "title": "Umriss Laos",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Laos – 1949, Unabhängigkeit von Frankreich",
    "hint": "Laos",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/la.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-lb",
    "title": "Umriss Libanon",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Libanon – 1943, Unabhängigkeit von Frankreich",
    "hint": "Libanon",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/lb.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-lc",
    "title": "Umriss St. Lucia",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "St. Lucia – 1979, Unabhängigkeit",
    "hint": "St. Lucia",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/lc.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-li",
    "title": "Umriss Liechtenstein",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Liechtenstein – 2003, Verfassungsreform.",
    "hint": "Liechtenstein",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/li.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-lk",
    "title": "Umriss Sri Lanka",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Sri Lanka – 1948, Unabhängigkeit",
    "hint": "Sri Lanka",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/lk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-lr",
    "title": "Umriss Liberia",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Liberia – 1986, Post-Bürgerkrieg-Verfassung.",
    "hint": "Liberia",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/lr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ls",
    "title": "Umriss Lesotho",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Lesotho – 1966, Unabhängigkeit",
    "hint": "Lesotho",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ls.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-lt",
    "title": "Umriss Litauen",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Litauen – 1991, Wiederherstellung der Unabhängigkeit",
    "hint": "Litauen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/lt.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-lu",
    "title": "Umriss Luxemburg",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Luxemburg – 1868, Aktuelle Verfassung",
    "hint": "Luxemburg",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/lu.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-lv",
    "title": "Umriss Lettland",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Lettland – 1991, Wiederherstellung der Unabhängigkeit",
    "hint": "Lettland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/lv.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ly",
    "title": "Umriss Libyen",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Libyen – 1951, Unabhängigkeit (Systemwechsel 2011)",
    "hint": "Libyen",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ly.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ma",
    "title": "Umriss Marokko",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Marokko – 1956, Ende der Protektorate",
    "hint": "Marokko",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ma.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mc",
    "title": "Umriss Monaco",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Monaco – 1962, Verfassungsreform.",
    "hint": "Monaco",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/mc.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-md",
    "title": "Umriss Republik Moldau",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Republik Moldau – 1994, Verfassung.",
    "hint": "Republik Moldau",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/md.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-me",
    "title": "Umriss Montenegro",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Montenegro – 2006, Unabhängigkeit von Serbien",
    "hint": "Montenegro",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/me.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mf",
    "title": "Umriss St. Martin",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "St. Martin – 2007, Überseekollektiv.",
    "hint": "St. Martin",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mg",
    "title": "Umriss Madagaskar",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Madagaskar – 1960, Unabhängigkeit",
    "hint": "Madagaskar",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/mg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mk",
    "title": "Umriss Nordmazedonien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Nordmazedonien – 1992, Unabhängigkeit von Jugoslawien",
    "hint": "Nordmazedonien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/mk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ml",
    "title": "Umriss Mali",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Mali – 1960, Unabhängigkeit",
    "hint": "Mali",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ml.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mm",
    "title": "Umriss Myanmar",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Myanmar – 1948, Unabhängigkeit",
    "hint": "Myanmar",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mn",
    "title": "Umriss Mongolei",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Mongolei – 1992, Post-Einparteiensystem.",
    "hint": "Mongolei",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mo",
    "title": "Umriss Sonderverwaltungsregion Macau",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Macau – 1999, Übergabe an China.",
    "hint": "Sonderverwaltungsregion Macau",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mo.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mq",
    "title": "Umriss Martinique",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Martinique – 1946, Überseedépartement.",
    "hint": "Martinique",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mq.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mr",
    "title": "Umriss Mauretanien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Mauretanien – 1960, Unabhängigkeit",
    "hint": "Mauretanien",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ms",
    "title": "Umriss Montserrat",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Montserrat – 2010, Verfassungsordnung.",
    "hint": "Montserrat",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ms.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mt",
    "title": "Umriss Malta",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Malta – 1964, Unabhängigkeit",
    "hint": "Malta",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/mt.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mu",
    "title": "Umriss Mauritius",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Mauritius – 1968, Unabhängigkeit",
    "hint": "Mauritius",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mu.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mv",
    "title": "Umriss Malediven",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Malediven – 1965, Unabhängigkeit",
    "hint": "Malediven",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mv.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mw",
    "title": "Umriss Malawi",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Malawi – 1964, Unabhängigkeit",
    "hint": "Malawi",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/mw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mx",
    "title": "Umriss Mexiko",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Mexiko – 1917, Post-Revolution-Verfassung.",
    "hint": "Mexiko",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/mx.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-my",
    "title": "Umriss Malaysia",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Malaysia – 1957, Unabhängigkeit",
    "hint": "Malaysia",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/my.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mz",
    "title": "Umriss Mosambik",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Mosambik – 1975, Unabhängigkeit",
    "hint": "Mosambik",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-na",
    "title": "Umriss Namibia",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Namibia – 1990, Unabhängigkeit",
    "hint": "Namibia",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/na.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-nc",
    "title": "Umriss Neukaledonien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Neukaledonien – 1998, Nouméa-Abkommen.",
    "hint": "Neukaledonien",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/nc.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ne",
    "title": "Umriss Niger",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Niger – 1960, Unabhängigkeit",
    "hint": "Niger",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ne.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-nf",
    "title": "Umriss Norfolkinsel",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Norfolkinsel – 2016, Ende der Selbstverwaltung.",
    "hint": "Norfolkinsel",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/nf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ng",
    "title": "Umriss Nigeria",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Nigeria – 1960, Unabhängigkeit",
    "hint": "Nigeria",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ng.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ni",
    "title": "Umriss Nicaragua",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Nicaragua – 1987, Verfassung.",
    "hint": "Nicaragua",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ni.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-nl",
    "title": "Umriss Niederlande",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Niederlande – 1983, Totalrevision.",
    "hint": "Niederlande",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/nl.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-no",
    "title": "Umriss Norwegen",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Norwegen – 1814, Verfassung von Eidsvoll (Konstitutionelle Monarchie)",
    "hint": "Norwegen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/no.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-np",
    "title": "Umriss Nepal",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Nepal – 2008, Ausrufung der Republik",
    "hint": "Nepal",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/np.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-nr",
    "title": "Umriss Nauru",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Nauru – 1968, Unabhängigkeit.",
    "hint": "Nauru",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/nr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-nu",
    "title": "Umriss Niue",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Niue – 1974, Selbstverwaltung.",
    "hint": "Niue",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/nu.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-nz",
    "title": "Umriss Neuseeland",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Neuseeland – 1890, Erlangung des Selbstverwaltungsstatus (Dominion-Status 1907)",
    "hint": "Neuseeland",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/nz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pa",
    "title": "Umriss Panama",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Panama – 1972, Verfassung.",
    "hint": "Panama",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/pa.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pe",
    "title": "Umriss Peru",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Peru – 1993, Verfassung.",
    "hint": "Peru",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/pe.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pf",
    "title": "Umriss Französisch-Polynesien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Französisch-Polynesien – 2004, Status Überseeland.",
    "hint": "Französisch-Polynesien",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/pf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pg",
    "title": "Umriss Papua-Neuguinea",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Papua-Neuguinea – 1975, Unabhängigkeit",
    "hint": "Papua-Neuguinea",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/pg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ph",
    "title": "Umriss Philippinen",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Philippinen – 1987, Aktuelle Verfassung",
    "hint": "Philippinen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ph.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pk",
    "title": "Umriss Pakistan",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Pakistan – 1947, Unabhängigkeit",
    "hint": "Pakistan",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/pk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pl",
    "title": "Umriss Polen",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Polen – 1997, Aktuelle Verfassung",
    "hint": "Polen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/pl.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pm",
    "title": "Umriss St. Pierre und Miquelon",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "St. Pierre und Miquelon – 2003, Überseekollektiv.",
    "hint": "St. Pierre und Miquelon",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/pm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pn",
    "title": "Umriss Pitcairninseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Pitcairninseln – 2010, Verfassungsordnung.",
    "hint": "Pitcairninseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/pn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pr",
    "title": "Umriss Puerto Rico",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Puerto Rico – 1952, Verfassung.",
    "hint": "Puerto Rico",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/pr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pt",
    "title": "Umriss Portugal",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Portugal – 1976, Post-Nelkenrevolution.",
    "hint": "Portugal",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/pt.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pw",
    "title": "Umriss Palau",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Palau – 1981, Verfassung (Souveränität 1994)",
    "hint": "Palau",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/pw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-py",
    "title": "Umriss Paraguay",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Paraguay – 1992, Post-Diktatur-Verfassung.",
    "hint": "Paraguay",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/py.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-qa",
    "title": "Umriss Katar",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Katar – 1971, Unabhängigkeit",
    "hint": "Katar",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/qa.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-re",
    "title": "Umriss Réunion",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Réunion – 1946, Überseedépartement.",
    "hint": "Réunion",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/re.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ro",
    "title": "Umriss Rumänien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Rumänien – 1991, Post-Kommunismus.",
    "hint": "Rumänien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ro.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-rs",
    "title": "Umriss Serbien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Serbien – 2006, Auflösung der Union mit Montenegro",
    "hint": "Serbien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/rs.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ru",
    "title": "Umriss Russland",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Russland – 1991, Russische Föderation (Post-Sowjet)",
    "hint": "Russland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ru.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-rw",
    "title": "Umriss Ruanda",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Ruanda – 1962, Unabhängigkeit",
    "hint": "Ruanda",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/rw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sa",
    "title": "Umriss Saudi-Arabien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Saudi-Arabien – 1932, Vereinigung der Königreiche",
    "hint": "Saudi-Arabien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/sa.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sb",
    "title": "Umriss Salomonen",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Salomonen – 1978, Unabhängigkeit",
    "hint": "Salomonen",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sb.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sc",
    "title": "Umriss Seychellen",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Seychellen – 1993, Mehrparteiendemokratie.",
    "hint": "Seychellen",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sc.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sd",
    "title": "Umriss Sudan",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Sudan – 1956, Unabhängigkeit",
    "hint": "Sudan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/sd.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-se",
    "title": "Umriss Schweden",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Schweden – 1974, Regierungsform.",
    "hint": "Schweden",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/se.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sg",
    "title": "Umriss Singapur",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Singapur – 1965, Trennung von Malaysia",
    "hint": "Singapur",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sh",
    "title": "Umriss St. Helena",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "St. Helena – 2009, Verfassungsordnung.",
    "hint": "St. Helena",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sh.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-si",
    "title": "Umriss Slowenien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Slowenien – 1991, Unabhängigkeit von Jugoslawien",
    "hint": "Slowenien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/si.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sj",
    "title": "Umriss Spitzbergen und Jan Mayen",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Spitzbergen und Jan Mayen – 1925, Spitzbergen-Vertrag.",
    "hint": "Spitzbergen und Jan Mayen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/sj.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sk",
    "title": "Umriss Slowakei",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Slowakei – 1993, Teilung der Tschechoslowakei",
    "hint": "Slowakei",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/sk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sl",
    "title": "Umriss Sierra Leone",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Sierra Leone – 1961, Unabhängigkeit",
    "hint": "Sierra Leone",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sl.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sm",
    "title": "Umriss San Marino",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "San Marino – 1600, Verabschiedung der Statuten (älteste Republik)",
    "hint": "San Marino",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/sm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sn",
    "title": "Umriss Senegal",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Senegal – 1960, Unabhängigkeit",
    "hint": "Senegal",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/sn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-so",
    "title": "Umriss Somalia",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Somalia – 1960, Unabhängigkeit",
    "hint": "Somalia",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/so.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sr",
    "title": "Umriss Suriname",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Suriname – 1975, Unabhängigkeit",
    "hint": "Suriname",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ss",
    "title": "Umriss Südsudan",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Südsudan – 2011, Unabhängigkeit vom Sudan",
    "hint": "Südsudan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ss.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-st",
    "title": "Umriss São Tomé und Príncipe",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "São Tomé und Príncipe – 1990, Systemwechsel.",
    "hint": "São Tomé und Príncipe",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/st.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sv",
    "title": "Umriss El Salvador",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "El Salvador – 1983, Verfassung.",
    "hint": "El Salvador",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sv.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sx",
    "title": "Umriss Sint Maarten",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Sint Maarten – 2010, Eigenständigkeit.",
    "hint": "Sint Maarten",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sx.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sy",
    "title": "Umriss Syrien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Syrien – 1946, Unabhängigkeit von Frankreich",
    "hint": "Syrien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/sy.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sz",
    "title": "Umriss Eswatini",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Eswatini – 1968, Unabhängigkeit",
    "hint": "Eswatini",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tc",
    "title": "Umriss Turks- und Caicosinseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Turks- und Caicosinseln – 2011, Post-Krisen-Verfassung.",
    "hint": "Turks- und Caicosinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/tc.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-td",
    "title": "Umriss Tschad",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Tschad – 2022, Neue Verfassung/Übergangsrat",
    "hint": "Tschad",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/td.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tf",
    "title": "Umriss Französische Süd- und Antarktisgebiete",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Antarktis – 1961, Antarktis-Vertrag.",
    "hint": "Französische Süd- und Antarktisgebiete",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/tf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tg",
    "title": "Umriss Togo",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Togo – 1960, Unabhängigkeit",
    "hint": "Togo",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/tg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-th",
    "title": "Umriss Thailand",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Thailand – 1932, Ende der absoluten Monarchie",
    "hint": "Thailand",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/th.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tj",
    "title": "Umriss Tadschikistan",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Tadschikistan – 1991, Unabhängigkeit von der UdSSR",
    "hint": "Tadschikistan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/tj.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tk",
    "title": "Umriss Tokelau",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Tokelau – 2006, Constitution Act.",
    "hint": "Tokelau",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/tk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tl",
    "title": "Umriss Timor-Leste",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Timor-Leste – 2002, Unabhängigkeit.",
    "hint": "Timor-Leste",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/tl.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tm",
    "title": "Umriss Turkmenistan",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Turkmenistan – 1991, Unabhängigkeit von der UdSSR",
    "hint": "Turkmenistan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/tm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tn",
    "title": "Umriss Tunesien",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Tunesien – 2014, Neue Verfassung (Arabischer Frühling)",
    "hint": "Tunesien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/tn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-to",
    "title": "Umriss Tonga",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Tonga – 2010, Demokratisierung.",
    "hint": "Tonga",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/to.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tr",
    "title": "Umriss Türkei",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Türkei – 1923, Ausrufung der Republik",
    "hint": "Türkei",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/tr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tt",
    "title": "Umriss Trinidad und Tobago",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Trinidad und Tobago – 1976, Republikgründung.",
    "hint": "Trinidad und Tobago",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/tt.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tw",
    "title": "Umriss Taiwan",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Taiwan – 1991, Demokratisierung.",
    "hint": "Taiwan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/tw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tz",
    "title": "Umriss Tansania",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Tansania – 1961, Unabhängigkeit (als Tanganjika)",
    "hint": "Tansania",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/tz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-us",
    "title": "Umriss Vereinigte Staaten",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Vereinigte Staaten – 1789, Verfassungsinkrafttreten.",
    "hint": "Vereinigte Staaten",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/us.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-va",
    "title": "Umriss Vatikanstadt",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Vatikanstadt – 1929, Lateranverträge",
    "hint": "Vatikanstadt",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/va.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-vc",
    "title": "Umriss St. Vincent und die Grenadinen",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "St. Vincent und die Grenadinen – 1985, Systembruch.",
    "hint": "St. Vincent und die Grenadinen",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/vc.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ve",
    "title": "Umriss Venezuela",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Venezuela – 1999, Bolivarische Verfassung.",
    "hint": "Venezuela",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ve.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-vg",
    "title": "Umriss Britische Jungferninseln",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Britische Jungferninseln – 2007, Verfassungsordnung.",
    "hint": "Britische Jungferninseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/vg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-vn",
    "title": "Umriss Vietnam",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Vietnam – 1975, Wiedervereinigung",
    "hint": "Vietnam",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/vn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-vu",
    "title": "Umriss Vanuatu",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Vanuatu – 1980, Unabhängigkeit",
    "hint": "Vanuatu",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/vu.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-wf",
    "title": "Umriss Wallis und Futuna",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Wallis und Futuna – 1961, Überseegebiet-Status.",
    "hint": "Wallis und Futuna",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/wf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ws",
    "title": "Umriss Samoa",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Samoa – 1962, Unabhängigkeit.",
    "hint": "Samoa",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ws.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ye",
    "title": "Umriss Jemen",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Jemen – 1990, Wiedervereinigung",
    "hint": "Jemen",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ye.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-yt",
    "title": "Umriss Mayotte",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Mayotte – 2011, Departement-Status.",
    "hint": "Mayotte",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/yt.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-za",
    "title": "Umriss Südafrika",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Südafrika – 1994, Erste freie Wahlen (Ende Apartheid)",
    "hint": "Südafrika",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/za.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-zm",
    "title": "Umriss Sambia",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Sambia – 1964, Unabhängigkeit",
    "hint": "Sambia",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/zm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-zw",
    "title": "Umriss Simbabwe",
    "category": "country",
    "year": 1900,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Simbabwe – 1980, Unabhängigkeit",
    "hint": "Simbabwe",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/zw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  }
];

