// AUTO-GENERATED by scripts/generate-outline-cards.mjs
// Do not edit manually.
import { Card } from './types';

export const outlineCards: Card[] = [
  {
    "id": "outline-ad",
    "title": "Umriss Andorra",
    "category": "country",
    "year": 1993,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Andorra – Erste Verfassung (Souveränität)",
    "hint": "Andorra",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ad.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ae",
    "title": "Umriss Vereinigte Arabische Emirate",
    "category": "country",
    "year": 1971,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Vereinigte Arabische Emirate – Gründung der Föderation.",
    "hint": "Vereinigte Arabische Emirate",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ae.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-af",
    "title": "Umriss Afghanistan",
    "category": "country",
    "year": 2021,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äfghanistan – Machtübernahme der Taliban.",
    "hint": "Äfghanistan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/af.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ag",
    "title": "Umriss Antigua und Barbuda",
    "category": "country",
    "year": 1981,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äntigua und Barbuda – Unabhängigkeit vom UK.",
    "hint": "Äntigua und Barbuda",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ag.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ai",
    "title": "Umriss Anguilla",
    "category": "country",
    "year": 1982,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Änguilla – Aktuelle Verfassungsordnung.",
    "hint": "Änguilla",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ai.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-al",
    "title": "Umriss Albanien",
    "category": "country",
    "year": 1998,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Älbanien – Aktuelle Verfassung.",
    "hint": "Älbanien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/al.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-am",
    "title": "Umriss Armenien",
    "category": "country",
    "year": 2015,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Ärmenie – Wechsel zum Parlamentarismus.",
    "hint": "Ärmenien",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/am.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ao",
    "title": "Umriss Angola",
    "category": "country",
    "year": 2010,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Ängola – Aktuelle Verfassung.",
    "hint": "Ängola",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ao.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-as",
    "title": "Umriss Amerikanisch-Samoa",
    "category": "country",
    "year": 1962,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Samoa – Unabhängigkeit.",
    "hint": "Ämerikanisch-Samoa",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/as.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-at",
    "title": "Umriss Österreich",
    "category": "country",
    "year": 1945,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Österreich – Zweite Republik",
    "hint": "Österreich",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/at.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-au",
    "title": "Umriss Australien",
    "category": "country",
    "year": 1986,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äustralien – Australia Act.",
    "hint": "Äustralien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/au.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-aw",
    "title": "Umriss Aruba",
    "category": "country",
    "year": 1986,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äruba – Status Aparte.",
    "hint": "Äruba",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/aw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ax",
    "title": "Umriss Ålandinseln",
    "category": "country",
    "year": 1993,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Ålandinseln – Neue Autonomie-Akte.",
    "hint": "Ålandinseln",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ax.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-az",
    "title": "Umriss Aserbaidschan",
    "category": "country",
    "year": 1995,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äserbaidschan – Unabhängigkeitsverfassung.",
    "hint": "Äserbaidschan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/az.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ba",
    "title": "Umriss Bosnien und Herzegowina",
    "category": "country",
    "year": 1995,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bosnien und Herzegowina – Dayton-Abkommen.",
    "hint": "Bosnien und Herzegowina",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ba.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bb",
    "title": "Umriss Barbados",
    "category": "country",
    "year": 2021,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Barbados – Übergang zur Republik",
    "hint": "Barbados",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bb.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bd",
    "title": "Umriss Bangladesch",
    "category": "country",
    "year": 1971,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bangladesch – Unabhängigkeit",
    "hint": "Bangladesch",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/bd.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-be",
    "title": "Umriss Belgien",
    "category": "country",
    "year": 1831,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Belgien – Unabhängigkeit und Verfassung nach der Revolution",
    "hint": "Belgien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/be.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bf",
    "title": "Umriss Burkina Faso",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Burkina Faso – Unabhängigkeit",
    "hint": "Burkina Faso",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/bf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bg",
    "title": "Umriss Bulgarien",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bulgarien – Post-sozialistische Verfassung.",
    "hint": "Bulgarien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/bg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bh",
    "title": "Umriss Bahrain",
    "category": "country",
    "year": 1971,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bahrain – Unabhängigkeit",
    "hint": "Bahrain",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bh.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bi",
    "title": "Umriss Burundi",
    "category": "country",
    "year": 1962,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Burundi – Unabhängigkeit",
    "hint": "Burundi",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/bi.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bj",
    "title": "Umriss Benin",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Benin – Unabhängigkeit",
    "hint": "Benin",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/bj.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bl",
    "title": "Umriss St. Barthélemy",
    "category": "country",
    "year": 2007,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "St. Barthélemy – Überseekollektiv.",
    "hint": "St. Barthélemy",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bl.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bm",
    "title": "Umriss Bermuda",
    "category": "country",
    "year": 1968,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bermuda – Verfassungsordnung.",
    "hint": "Bermuda",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bn",
    "title": "Umriss Brunei Darussalam",
    "category": "country",
    "year": 1984,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Brunei Darussalam – Unabhängigkeit.",
    "hint": "Brunei Darussalam",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bo",
    "title": "Umriss Bolivien",
    "category": "country",
    "year": 2009,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bolivien – Plurinationaler Staat.",
    "hint": "Bolivien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/bo.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bq",
    "title": "Umriss Karibische Niederlande",
    "category": "country",
    "year": 1983,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Niederlande – Totalrevision.",
    "hint": "Karibische Niederlande",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bq.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-br",
    "title": "Umriss Brasilien",
    "category": "country",
    "year": 1988,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Brasilien – Aktuelle Verfassung",
    "hint": "Brasilien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/br.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bs",
    "title": "Umriss Bahamas",
    "category": "country",
    "year": 1973,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bahamas – Unabhängigkeit",
    "hint": "Bahamas",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bs.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bt",
    "title": "Umriss Bhutan",
    "category": "country",
    "year": 2008,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bhutan – Konstitutionelle Monarchie.",
    "hint": "Bhutan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bt.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bv",
    "title": "Umriss Bouvetinsel",
    "category": "country",
    "year": 1930,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Bouvetinsel – Norwegische Souveränität.",
    "hint": "Bouvetinsel",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bv.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bw",
    "title": "Umriss Botsuana",
    "category": "country",
    "year": 1966,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Botsuana – Unabhängigkeit.",
    "hint": "Botsuana",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-by",
    "title": "Umriss Belarus",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Belarus – Unabhängigkeit von der UdSSR",
    "hint": "Belarus",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/by.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-bz",
    "title": "Umriss Belize",
    "category": "country",
    "year": 1981,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Belize – Unabhängigkeit",
    "hint": "Belize",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/bz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ca",
    "title": "Umriss Kanada",
    "category": "country",
    "year": 1867,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kanada – British North America Act (Beginn der Eigenstaatlichkeit)",
    "hint": "Kanada",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ca.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cc",
    "title": "Umriss Kokosinseln",
    "category": "country",
    "year": 1984,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kokosinseln – Integration in Australien.",
    "hint": "Kokosinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/cc.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cd",
    "title": "Umriss Kongo-Kinshasa",
    "category": "country",
    "year": 2006,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kongo-Kinshasa – III. Republik.",
    "hint": "Kongo-Kinshasa",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/cd.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cf",
    "title": "Umriss Zentralafrikanische Republik",
    "category": "country",
    "year": 2023,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Zentralafrikanische Republik – Neue Verfassung.",
    "hint": "Zentralafrikanische Republik",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/cf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cg",
    "title": "Umriss Kongo-Brazzaville",
    "category": "country",
    "year": 2015,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kongo-Brazzaville – Neue Verfassung.",
    "hint": "Kongo-Brazzaville",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/cg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ch",
    "title": "Umriss Schweiz",
    "category": "country",
    "year": 1848,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Schweiz – Gründung des modernen Bundesstaates",
    "hint": "Schweiz",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ch.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ci",
    "title": "Umriss Côte d’Ivoire",
    "category": "country",
    "year": 2016,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Côte d’Ivoire – III. Republik.",
    "hint": "Côte d’Ivoire",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ci.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ck",
    "title": "Umriss Cookinseln",
    "category": "country",
    "year": 1965,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Cookinseln – Selbstverwaltung.",
    "hint": "Cookinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ck.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cl",
    "title": "Umriss Chile",
    "category": "country",
    "year": 2005,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Chile – Verfassungsreform.",
    "hint": "Chile",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/cl.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cm",
    "title": "Umriss Kamerun",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kamerun – Unabhängigkeit",
    "hint": "Kamerun",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/cm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cn",
    "title": "Umriss China",
    "category": "country",
    "year": 1982,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "China – Aktuelle Verfassung.",
    "hint": "China",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/cn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-co",
    "title": "Umriss Kolumbien",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kolumbien – Moderne Verfassung.",
    "hint": "Kolumbien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/co.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cr",
    "title": "Umriss Costa Rica",
    "category": "country",
    "year": 1949,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Costa Rica – Post-Bürgerkriegsverfassung.",
    "hint": "Costa Rica",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/cr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cu",
    "title": "Umriss Kuba",
    "category": "country",
    "year": 2019,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kuba – Neue Verfassung",
    "hint": "Kuba",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/cu.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cv",
    "title": "Umriss Cabo Verde",
    "category": "country",
    "year": 1992,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Cabo Verde – Demokratisierung.",
    "hint": "Cabo Verde",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/cv.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cw",
    "title": "Umriss Curaçao",
    "category": "country",
    "year": 2010,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Curaçao – Eigenständiges Land.",
    "hint": "Curaçao",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/cw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cx",
    "title": "Umriss Weihnachtsinsel",
    "category": "country",
    "year": 1958,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Weihnachtsinsel – Australische Verwaltung.",
    "hint": "Weihnachtsinsel",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/cx.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cy",
    "title": "Umriss Zypern",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Zypern – Unabhängigkeit",
    "hint": "Zypern",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/cy.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-cz",
    "title": "Umriss Tschechien",
    "category": "country",
    "year": 1993,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Tschechien – Teilung der Tschechoslowakei",
    "hint": "Tschechien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/cz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-de",
    "title": "Umriss Deutschland",
    "category": "country",
    "year": 1949,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Deutschland – Grundgesetz (BRD)",
    "hint": "Deutschland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/de.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-dj",
    "title": "Umriss Dschibuti",
    "category": "country",
    "year": 1977,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Dschibuti – Unabhängigkeit",
    "hint": "Dschibuti",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/dj.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-dk",
    "title": "Umriss Dänemark",
    "category": "country",
    "year": 1953,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Dänemark – Verfassungsänderung.",
    "hint": "Dänemark",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/dk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-dm",
    "title": "Umriss Dominica",
    "category": "country",
    "year": 1978,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Dominica – Unabhängigkeit",
    "hint": "Dominica",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/dm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-do",
    "title": "Umriss Dominikanische Republik",
    "category": "country",
    "year": 2015,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Dominikanische Republik – Verfassungsreform.",
    "hint": "Dominikanische Republik",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/do.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-dz",
    "title": "Umriss Algerien",
    "category": "country",
    "year": 2020,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Älgerien – Post-Hirak-Verfassung.",
    "hint": "Älgerien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/dz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ec",
    "title": "Umriss Ecuador",
    "category": "country",
    "year": 2008,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Ecuador – Aktuelle Verfassung.",
    "hint": "Ecuador",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ec.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ee",
    "title": "Umriss Estland",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Estland – Wiederherstellung der Unabhängigkeit",
    "hint": "Estland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ee.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-eg",
    "title": "Umriss Ägypten",
    "category": "country",
    "year": 1953,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Ägypten – Ausrufung der Republik",
    "hint": "Ägypten",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/eg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-eh",
    "title": "Umriss Westsahara",
    "category": "country",
    "year": 1976,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Westsahara – Proklamation der D.A.R.S..",
    "hint": "Westsahara",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/eh.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-er",
    "title": "Umriss Eritrea",
    "category": "country",
    "year": 1995,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äthiopien – Föderale Verfassung.",
    "hint": "Eritrea",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/er.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-es",
    "title": "Umriss Spanien",
    "category": "country",
    "year": 1978,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Spanien – Demokratische Verfassung",
    "hint": "Spanien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/es.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-et",
    "title": "Umriss Äthiopien",
    "category": "country",
    "year": 1995,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äthiopien – Föderale Verfassung.",
    "hint": "Äthiopien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/et.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-fi",
    "title": "Umriss Finnland",
    "category": "country",
    "year": 2000,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Finnland – Neue Verfassung.",
    "hint": "Finnland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/fi.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-fj",
    "title": "Umriss Fidschi",
    "category": "country",
    "year": 1970,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Fidschi – Unabhängigkeit",
    "hint": "Fidschi",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/fj.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-fk",
    "title": "Umriss Falklandinseln",
    "category": "country",
    "year": 2009,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Falklandinseln – Verfassungsordnung.",
    "hint": "Falklandinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/fk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-fo",
    "title": "Umriss Färöer",
    "category": "country",
    "year": 1948,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Färöer – Autonomiegesetz.",
    "hint": "Färöer",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/fo.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-fr",
    "title": "Umriss Frankreich",
    "category": "country",
    "year": 1958,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Frankreich – Fünfte Republik",
    "hint": "Frankreich",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/fr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ga",
    "title": "Umriss Gabun",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Gabun – Unabhängigkeit",
    "hint": "Gabun",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ga.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gb",
    "title": "Umriss Vereinigtes Königreich",
    "category": "country",
    "year": 1922,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Vereinigtes Königreich – Heutiger Staatsrahmen.",
    "hint": "Vereinigtes Königreich",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/gb.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gd",
    "title": "Umriss Grenada",
    "category": "country",
    "year": 1974,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Grenada – Unabhängigkeit",
    "hint": "Grenada",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gd.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ge",
    "title": "Umriss Georgien",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Georgien – Unabhängigkeit von der UdSSR",
    "hint": "Georgien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ge.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gf",
    "title": "Umriss Französisch-Guayana",
    "category": "country",
    "year": 1946,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Französisch-Guayana – Überseedépartement.",
    "hint": "Französisch-Guayana",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gg",
    "title": "Umriss Guernsey",
    "category": "country",
    "year": 2005,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Guernsey – Regierungsreform.",
    "hint": "Guernsey",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/gg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gh",
    "title": "Umriss Ghana",
    "category": "country",
    "year": 1957,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Ghana – Unabhängigkeit",
    "hint": "Ghana",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/gh.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gi",
    "title": "Umriss Gibraltar",
    "category": "country",
    "year": 2006,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Gibraltar – Verfassungsordnung.",
    "hint": "Gibraltar",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/gi.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gl",
    "title": "Umriss Grönland",
    "category": "country",
    "year": 2009,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Grönland – Self-Government.",
    "hint": "Grönland",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gl.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gm",
    "title": "Umriss Gambia",
    "category": "country",
    "year": 1965,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Gambia – Unabhängigkeit",
    "hint": "Gambia",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gn",
    "title": "Umriss Guinea",
    "category": "country",
    "year": 1958,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Guinea – Unabhängigkeit",
    "hint": "Guinea",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/gn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gp",
    "title": "Umriss Guadeloupe",
    "category": "country",
    "year": 1946,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Guadeloupe – Überseedépartement.",
    "hint": "Guadeloupe",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gp.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gq",
    "title": "Umriss Äquatorialguinea",
    "category": "country",
    "year": 1968,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Äquatorialguinea – Unabhängigkeit",
    "hint": "Äquatorialguinea",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gq.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gr",
    "title": "Umriss Griechenland",
    "category": "country",
    "year": 1975,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Griechenland – Post-Diktatur-Verfassung.",
    "hint": "Griechenland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/gr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gs",
    "title": "Umriss Südgeorgien und die Südlichen Sandwichinseln",
    "category": "country",
    "year": 1985,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Südgeorgien und die Südlichen Sandwichinseln – Eigenständiges Territorium.",
    "hint": "Südgeorgien und die Südlichen Sandwichinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gs.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gt",
    "title": "Umriss Guatemala",
    "category": "country",
    "year": 1985,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Guatemala – Demokratische Verfassung.",
    "hint": "Guatemala",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/gt.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gu",
    "title": "Umriss Guam",
    "category": "country",
    "year": 1950,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Guam – Organic Act.",
    "hint": "Guam",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gu.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gw",
    "title": "Umriss Guinea-Bissau",
    "category": "country",
    "year": 1974,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Guinea-Bissau – Unabhängigkeit",
    "hint": "Guinea-Bissau",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-gy",
    "title": "Umriss Guyana",
    "category": "country",
    "year": 1966,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Guyana – Unabhängigkeit",
    "hint": "Guyana",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/gy.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-hk",
    "title": "Umriss Sonderverwaltungsregion Hongkong",
    "category": "country",
    "year": 1997,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Hongkong – Übergabe an China.",
    "hint": "Sonderverwaltungsregion Hongkong",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/hk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-hm",
    "title": "Umriss Heard und McDonaldinseln",
    "category": "country",
    "year": 1947,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Heard und McDonaldinseln – Australische Verwaltung.",
    "hint": "Heard und McDonaldinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/hm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-hn",
    "title": "Umriss Honduras",
    "category": "country",
    "year": 1982,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Honduras – Demokratisierung.",
    "hint": "Honduras",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/hn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-hr",
    "title": "Umriss Kroatien",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kroatien – Unabhängigkeit von Jugoslawien",
    "hint": "Kroatien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/hr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ht",
    "title": "Umriss Haiti",
    "category": "country",
    "year": 1987,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Haiti – Post-Duvalier-Verfassung.",
    "hint": "Haiti",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ht.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-id",
    "title": "Umriss Indonesien",
    "category": "country",
    "year": 1945,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Indonesien – Unabhängigkeit",
    "hint": "Indonesien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/id.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ie",
    "title": "Umriss Irland",
    "category": "country",
    "year": 1921,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Irland – Unabhängigkeit (Freistaat)",
    "hint": "Irland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ie.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-il",
    "title": "Umriss Israel",
    "category": "country",
    "year": 1948,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Israel – Staatsgründung",
    "hint": "Israel",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/il.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-im",
    "title": "Umriss Isle of Man",
    "category": "country",
    "year": 1979,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Isle of Man – Tynwald-Jubiläum.",
    "hint": "Isle of Man",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/im.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-in",
    "title": "Umriss Indien",
    "category": "country",
    "year": 1947,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Indien – Unabhängigkeit",
    "hint": "Indien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/in.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-io",
    "title": "Umriss Britisches Territorium im Indischen Ozean",
    "category": "country",
    "year": 1965,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Britisches Territorium im Indischen Ozean – Eigenes Territorium.",
    "hint": "Britisches Territorium im Indischen Ozean",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/io.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-iq",
    "title": "Umriss Irak",
    "category": "country",
    "year": 2005,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Irak – Post-Saddam Verfassung",
    "hint": "Irak",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/iq.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ir",
    "title": "Umriss Iran",
    "category": "country",
    "year": 1979,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Iran – Islamische Republik",
    "hint": "Iran",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ir.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-is",
    "title": "Umriss Island",
    "category": "country",
    "year": 1944,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Island – Republikgründung",
    "hint": "Island",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/is.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-it",
    "title": "Umriss Italien",
    "category": "country",
    "year": 1948,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Italien – Republikanische Verfassung",
    "hint": "Italien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/it.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-jm",
    "title": "Umriss Jamaika",
    "category": "country",
    "year": 1962,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Jamaika – Unabhängigkeit",
    "hint": "Jamaika",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/jm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-jo",
    "title": "Umriss Jordanien",
    "category": "country",
    "year": 1946,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Jordanien – Unabhängigkeit",
    "hint": "Jordanien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/jo.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-jp",
    "title": "Umriss Japan",
    "category": "country",
    "year": 1946,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Japan – Nachkriegsverfassung",
    "hint": "Japan",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/jp.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ke",
    "title": "Umriss Kenia",
    "category": "country",
    "year": 1963,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kenia – Unabhängigkeit",
    "hint": "Kenia",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ke.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-kg",
    "title": "Umriss Kirgisistan",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kirgisistan – Unabhängigkeit von der UdSSR",
    "hint": "Kirgisistan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/kg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-kh",
    "title": "Umriss Kambodscha",
    "category": "country",
    "year": 1953,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kambodscha – Unabhängigkeit",
    "hint": "Kambodscha",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/kh.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ki",
    "title": "Umriss Kiribati",
    "category": "country",
    "year": 1979,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kiribati – Unabhängigkeit",
    "hint": "Kiribati",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ki.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-km",
    "title": "Umriss Komoren",
    "category": "country",
    "year": 1975,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Komoren – Unabhängigkeit",
    "hint": "Komoren",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/km.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-kn",
    "title": "Umriss St. Kitts und Nevis",
    "category": "country",
    "year": 1983,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "St. Kitts und Nevis – Unabhängigkeit.",
    "hint": "St. Kitts und Nevis",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/kn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-kp",
    "title": "Umriss Nordkorea",
    "category": "country",
    "year": 1948,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Nordkorea – Gründung der DVRK",
    "hint": "Nordkorea",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/kp.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-kr",
    "title": "Umriss Südkorea",
    "category": "country",
    "year": 1948,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Südkorea – Gründung der Republik",
    "hint": "Südkorea",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/kr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-kw",
    "title": "Umriss Kuwait",
    "category": "country",
    "year": 1961,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kuwait – Unabhängigkeit",
    "hint": "Kuwait",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/kw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ky",
    "title": "Umriss Kaimaninseln",
    "category": "country",
    "year": 2009,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kaimaninseln – Verfassungsordnung.",
    "hint": "Kaimaninseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ky.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-kz",
    "title": "Umriss Kasachstan",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Kasachstan – Unabhängigkeit von der UdSSR",
    "hint": "Kasachstan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/kz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-la",
    "title": "Umriss Laos",
    "category": "country",
    "year": 1949,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Laos – Unabhängigkeit von Frankreich",
    "hint": "Laos",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/la.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-lb",
    "title": "Umriss Libanon",
    "category": "country",
    "year": 1943,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Libanon – Unabhängigkeit von Frankreich",
    "hint": "Libanon",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/lb.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-lc",
    "title": "Umriss St. Lucia",
    "category": "country",
    "year": 1979,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "St. Lucia – Unabhängigkeit",
    "hint": "St. Lucia",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/lc.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-li",
    "title": "Umriss Liechtenstein",
    "category": "country",
    "year": 2003,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Liechtenstein – Verfassungsreform.",
    "hint": "Liechtenstein",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/li.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-lk",
    "title": "Umriss Sri Lanka",
    "category": "country",
    "year": 1948,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Sri Lanka – Unabhängigkeit",
    "hint": "Sri Lanka",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/lk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-lr",
    "title": "Umriss Liberia",
    "category": "country",
    "year": 1986,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Liberia – Post-Bürgerkrieg-Verfassung.",
    "hint": "Liberia",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/lr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ls",
    "title": "Umriss Lesotho",
    "category": "country",
    "year": 1966,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Lesotho – Unabhängigkeit",
    "hint": "Lesotho",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ls.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-lt",
    "title": "Umriss Litauen",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Litauen – Wiederherstellung der Unabhängigkeit",
    "hint": "Litauen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/lt.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-lu",
    "title": "Umriss Luxemburg",
    "category": "country",
    "year": 1868,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Luxemburg – Aktuelle Verfassung",
    "hint": "Luxemburg",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/lu.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-lv",
    "title": "Umriss Lettland",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Lettland – Wiederherstellung der Unabhängigkeit",
    "hint": "Lettland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/lv.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ly",
    "title": "Umriss Libyen",
    "category": "country",
    "year": 1951,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Libyen – Unabhängigkeit (Systemwechsel 2011)",
    "hint": "Libyen",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ly.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ma",
    "title": "Umriss Marokko",
    "category": "country",
    "year": 1956,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Marokko – Ende der Protektorate",
    "hint": "Marokko",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ma.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mc",
    "title": "Umriss Monaco",
    "category": "country",
    "year": 1962,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Monaco – Verfassungsreform.",
    "hint": "Monaco",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/mc.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-md",
    "title": "Umriss Republik Moldau",
    "category": "country",
    "year": 1994,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Republik Moldau – Verfassung.",
    "hint": "Republik Moldau",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/md.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-me",
    "title": "Umriss Montenegro",
    "category": "country",
    "year": 2006,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Montenegro – Unabhängigkeit von Serbien",
    "hint": "Montenegro",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/me.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mf",
    "title": "Umriss St. Martin",
    "category": "country",
    "year": 2007,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "St. Martin – Überseekollektiv.",
    "hint": "St. Martin",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mg",
    "title": "Umriss Madagaskar",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Madagaskar – Unabhängigkeit",
    "hint": "Madagaskar",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/mg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mk",
    "title": "Umriss Nordmazedonien",
    "category": "country",
    "year": 1992,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Nordmazedonien – Unabhängigkeit von Jugoslawien",
    "hint": "Nordmazedonien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/mk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ml",
    "title": "Umriss Mali",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Mali – Unabhängigkeit",
    "hint": "Mali",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ml.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mm",
    "title": "Umriss Myanmar",
    "category": "country",
    "year": 1948,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Myanmar – Unabhängigkeit",
    "hint": "Myanmar",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mn",
    "title": "Umriss Mongolei",
    "category": "country",
    "year": 1992,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Mongolei – Post-Einparteiensystem.",
    "hint": "Mongolei",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mo",
    "title": "Umriss Sonderverwaltungsregion Macau",
    "category": "country",
    "year": 1999,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Macau – Übergabe an China.",
    "hint": "Sonderverwaltungsregion Macau",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mo.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mq",
    "title": "Umriss Martinique",
    "category": "country",
    "year": 1946,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Martinique – Überseedépartement.",
    "hint": "Martinique",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mq.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mr",
    "title": "Umriss Mauretanien",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Mauretanien – Unabhängigkeit",
    "hint": "Mauretanien",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ms",
    "title": "Umriss Montserrat",
    "category": "country",
    "year": 2010,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Montserrat – Verfassungsordnung.",
    "hint": "Montserrat",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ms.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mt",
    "title": "Umriss Malta",
    "category": "country",
    "year": 1964,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Malta – Unabhängigkeit",
    "hint": "Malta",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/mt.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mu",
    "title": "Umriss Mauritius",
    "category": "country",
    "year": 1968,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Mauritius – Unabhängigkeit",
    "hint": "Mauritius",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mu.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mv",
    "title": "Umriss Malediven",
    "category": "country",
    "year": 1965,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Malediven – Unabhängigkeit",
    "hint": "Malediven",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mv.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mw",
    "title": "Umriss Malawi",
    "category": "country",
    "year": 1964,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Malawi – Unabhängigkeit",
    "hint": "Malawi",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/mw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mx",
    "title": "Umriss Mexiko",
    "category": "country",
    "year": 1917,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Mexiko – Post-Revolution-Verfassung.",
    "hint": "Mexiko",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/mx.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-my",
    "title": "Umriss Malaysia",
    "category": "country",
    "year": 1957,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Malaysia – Unabhängigkeit",
    "hint": "Malaysia",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/my.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-mz",
    "title": "Umriss Mosambik",
    "category": "country",
    "year": 1975,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Mosambik – Unabhängigkeit",
    "hint": "Mosambik",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/mz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-na",
    "title": "Umriss Namibia",
    "category": "country",
    "year": 1990,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Namibia – Unabhängigkeit",
    "hint": "Namibia",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/na.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-nc",
    "title": "Umriss Neukaledonien",
    "category": "country",
    "year": 1998,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Neukaledonien – Nouméa-Abkommen.",
    "hint": "Neukaledonien",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/nc.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ne",
    "title": "Umriss Niger",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Niger – Unabhängigkeit",
    "hint": "Niger",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ne.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-nf",
    "title": "Umriss Norfolkinsel",
    "category": "country",
    "year": 2016,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Norfolkinsel – Ende der Selbstverwaltung.",
    "hint": "Norfolkinsel",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/nf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ng",
    "title": "Umriss Nigeria",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Nigeria – Unabhängigkeit",
    "hint": "Nigeria",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ng.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ni",
    "title": "Umriss Nicaragua",
    "category": "country",
    "year": 1987,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Nicaragua – Verfassung.",
    "hint": "Nicaragua",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ni.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-nl",
    "title": "Umriss Niederlande",
    "category": "country",
    "year": 1983,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Niederlande – Totalrevision.",
    "hint": "Niederlande",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/nl.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-no",
    "title": "Umriss Norwegen",
    "category": "country",
    "year": 1814,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Norwegen – Verfassung von Eidsvoll (Konstitutionelle Monarchie)",
    "hint": "Norwegen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/no.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-np",
    "title": "Umriss Nepal",
    "category": "country",
    "year": 2008,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Nepal – Ausrufung der Republik",
    "hint": "Nepal",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/np.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-nr",
    "title": "Umriss Nauru",
    "category": "country",
    "year": 1968,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Nauru – Unabhängigkeit.",
    "hint": "Nauru",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/nr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-nu",
    "title": "Umriss Niue",
    "category": "country",
    "year": 1974,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Niue – Selbstverwaltung.",
    "hint": "Niue",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/nu.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-nz",
    "title": "Umriss Neuseeland",
    "category": "country",
    "year": 1890,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Neuseeland – Erlangung des Selbstverwaltungsstatus (Dominion-Status 1907)",
    "hint": "Neuseeland",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/nz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pa",
    "title": "Umriss Panama",
    "category": "country",
    "year": 1972,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Panama – Verfassung.",
    "hint": "Panama",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/pa.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pe",
    "title": "Umriss Peru",
    "category": "country",
    "year": 1993,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Peru – Verfassung.",
    "hint": "Peru",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/pe.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pf",
    "title": "Umriss Französisch-Polynesien",
    "category": "country",
    "year": 2004,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Französisch-Polynesien – Status Überseeland.",
    "hint": "Französisch-Polynesien",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/pf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pg",
    "title": "Umriss Papua-Neuguinea",
    "category": "country",
    "year": 1975,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Papua-Neuguinea – Unabhängigkeit",
    "hint": "Papua-Neuguinea",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/pg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ph",
    "title": "Umriss Philippinen",
    "category": "country",
    "year": 1987,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Philippinen – Aktuelle Verfassung",
    "hint": "Philippinen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ph.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pk",
    "title": "Umriss Pakistan",
    "category": "country",
    "year": 1947,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Pakistan – Unabhängigkeit",
    "hint": "Pakistan",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/pk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pl",
    "title": "Umriss Polen",
    "category": "country",
    "year": 1997,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Polen – Aktuelle Verfassung",
    "hint": "Polen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/pl.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pm",
    "title": "Umriss St. Pierre und Miquelon",
    "category": "country",
    "year": 2003,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "St. Pierre und Miquelon – Überseekollektiv.",
    "hint": "St. Pierre und Miquelon",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/pm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pn",
    "title": "Umriss Pitcairninseln",
    "category": "country",
    "year": 2010,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Pitcairninseln – Verfassungsordnung.",
    "hint": "Pitcairninseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/pn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pr",
    "title": "Umriss Puerto Rico",
    "category": "country",
    "year": 1952,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Puerto Rico – Verfassung.",
    "hint": "Puerto Rico",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/pr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pt",
    "title": "Umriss Portugal",
    "category": "country",
    "year": 1976,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Portugal – Post-Nelkenrevolution.",
    "hint": "Portugal",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/pt.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-pw",
    "title": "Umriss Palau",
    "category": "country",
    "year": 1981,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Palau – Verfassung (Souveränität 1994)",
    "hint": "Palau",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/pw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-py",
    "title": "Umriss Paraguay",
    "category": "country",
    "year": 1992,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Paraguay – Post-Diktatur-Verfassung.",
    "hint": "Paraguay",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/py.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-qa",
    "title": "Umriss Katar",
    "category": "country",
    "year": 1971,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Katar – Unabhängigkeit",
    "hint": "Katar",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/qa.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-re",
    "title": "Umriss Réunion",
    "category": "country",
    "year": 1946,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Réunion – Überseedépartement.",
    "hint": "Réunion",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/re.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ro",
    "title": "Umriss Rumänien",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Rumänien – Post-Kommunismus.",
    "hint": "Rumänien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ro.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-rs",
    "title": "Umriss Serbien",
    "category": "country",
    "year": 2006,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Serbien – Auflösung der Union mit Montenegro",
    "hint": "Serbien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/rs.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ru",
    "title": "Umriss Russland",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Russland – Russische Föderation (Post-Sowjet)",
    "hint": "Russland",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/ru.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-rw",
    "title": "Umriss Ruanda",
    "category": "country",
    "year": 1962,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Ruanda – Unabhängigkeit",
    "hint": "Ruanda",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/rw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sa",
    "title": "Umriss Saudi-Arabien",
    "category": "country",
    "year": 1932,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Saudi-Arabien – Vereinigung der Königreiche",
    "hint": "Saudi-Arabien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/sa.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sb",
    "title": "Umriss Salomonen",
    "category": "country",
    "year": 1978,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Salomonen – Unabhängigkeit",
    "hint": "Salomonen",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sb.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sc",
    "title": "Umriss Seychellen",
    "category": "country",
    "year": 1993,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Seychellen – Mehrparteiendemokratie.",
    "hint": "Seychellen",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sc.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sd",
    "title": "Umriss Sudan",
    "category": "country",
    "year": 1956,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Sudan – Unabhängigkeit",
    "hint": "Sudan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/sd.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-se",
    "title": "Umriss Schweden",
    "category": "country",
    "year": 1974,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Schweden – Regierungsform.",
    "hint": "Schweden",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/se.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sg",
    "title": "Umriss Singapur",
    "category": "country",
    "year": 1965,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Singapur – Trennung von Malaysia",
    "hint": "Singapur",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sh",
    "title": "Umriss St. Helena",
    "category": "country",
    "year": 2009,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "St. Helena – Verfassungsordnung.",
    "hint": "St. Helena",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sh.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-si",
    "title": "Umriss Slowenien",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Slowenien – Unabhängigkeit von Jugoslawien",
    "hint": "Slowenien",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/si.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sj",
    "title": "Umriss Spitzbergen und Jan Mayen",
    "category": "country",
    "year": 1925,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Spitzbergen und Jan Mayen – Spitzbergen-Vertrag.",
    "hint": "Spitzbergen und Jan Mayen",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/sj.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sk",
    "title": "Umriss Slowakei",
    "category": "country",
    "year": 1993,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Slowakei – Teilung der Tschechoslowakei",
    "hint": "Slowakei",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/sk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sl",
    "title": "Umriss Sierra Leone",
    "category": "country",
    "year": 1961,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Sierra Leone – Unabhängigkeit",
    "hint": "Sierra Leone",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sl.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sm",
    "title": "Umriss San Marino",
    "category": "country",
    "year": 1600,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "San Marino – Verabschiedung der Statuten (älteste Republik)",
    "hint": "San Marino",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/sm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sn",
    "title": "Umriss Senegal",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Senegal – Unabhängigkeit",
    "hint": "Senegal",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/sn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-so",
    "title": "Umriss Somalia",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Somalia – Unabhängigkeit",
    "hint": "Somalia",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/so.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sr",
    "title": "Umriss Suriname",
    "category": "country",
    "year": 1975,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Suriname – Unabhängigkeit",
    "hint": "Suriname",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ss",
    "title": "Umriss Südsudan",
    "category": "country",
    "year": 2011,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Südsudan – Unabhängigkeit vom Sudan",
    "hint": "Südsudan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ss.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-st",
    "title": "Umriss São Tomé und Príncipe",
    "category": "country",
    "year": 1990,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "São Tomé und Príncipe – Systemwechsel.",
    "hint": "São Tomé und Príncipe",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/st.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sv",
    "title": "Umriss El Salvador",
    "category": "country",
    "year": 1983,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "El Salvador – Verfassung.",
    "hint": "El Salvador",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sv.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sx",
    "title": "Umriss Sint Maarten",
    "category": "country",
    "year": 2010,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Sint Maarten – Eigenständigkeit.",
    "hint": "Sint Maarten",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sx.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sy",
    "title": "Umriss Syrien",
    "category": "country",
    "year": 1946,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Syrien – Unabhängigkeit von Frankreich",
    "hint": "Syrien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/sy.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-sz",
    "title": "Umriss Eswatini",
    "category": "country",
    "year": 1968,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Eswatini – Unabhängigkeit",
    "hint": "Eswatini",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/sz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tc",
    "title": "Umriss Turks- und Caicosinseln",
    "category": "country",
    "year": 2011,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Turks- und Caicosinseln – Post-Krisen-Verfassung.",
    "hint": "Turks- und Caicosinseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/tc.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-td",
    "title": "Umriss Tschad",
    "category": "country",
    "year": 2022,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Tschad – Neue Verfassung/Übergangsrat",
    "hint": "Tschad",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/td.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tf",
    "title": "Umriss Französische Süd- und Antarktisgebiete",
    "category": "country",
    "year": 1961,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Antarktis – Antarktis-Vertrag.",
    "hint": "Französische Süd- und Antarktisgebiete",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/tf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tg",
    "title": "Umriss Togo",
    "category": "country",
    "year": 1960,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Togo – Unabhängigkeit",
    "hint": "Togo",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/tg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-th",
    "title": "Umriss Thailand",
    "category": "country",
    "year": 1932,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Thailand – Ende der absoluten Monarchie",
    "hint": "Thailand",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/th.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tj",
    "title": "Umriss Tadschikistan",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Tadschikistan – Unabhängigkeit von der UdSSR",
    "hint": "Tadschikistan",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/tj.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tk",
    "title": "Umriss Tokelau",
    "category": "country",
    "year": 2006,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Tokelau – Constitution Act.",
    "hint": "Tokelau",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/tk.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tl",
    "title": "Umriss Timor-Leste",
    "category": "country",
    "year": 2002,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Timor-Leste – Unabhängigkeit.",
    "hint": "Timor-Leste",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/tl.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tm",
    "title": "Umriss Turkmenistan",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Turkmenistan – Unabhängigkeit von der UdSSR",
    "hint": "Turkmenistan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/tm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tn",
    "title": "Umriss Tunesien",
    "category": "country",
    "year": 2014,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Tunesien – Neue Verfassung (Arabischer Frühling)",
    "hint": "Tunesien",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/tn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-to",
    "title": "Umriss Tonga",
    "category": "country",
    "year": 2010,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Tonga – Demokratisierung.",
    "hint": "Tonga",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/to.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tr",
    "title": "Umriss Türkei",
    "category": "country",
    "year": 1923,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Türkei – Ausrufung der Republik",
    "hint": "Türkei",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/tr.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tt",
    "title": "Umriss Trinidad und Tobago",
    "category": "country",
    "year": 1976,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Trinidad und Tobago – Republikgründung.",
    "hint": "Trinidad und Tobago",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/tt.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tw",
    "title": "Umriss Taiwan",
    "category": "country",
    "year": 1991,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Taiwan – Demokratisierung.",
    "hint": "Taiwan",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/tw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-tz",
    "title": "Umriss Tansania",
    "category": "country",
    "year": 1961,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Tansania – Unabhängigkeit (als Tanganjika)",
    "hint": "Tansania",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/tz.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-us",
    "title": "Umriss Vereinigte Staaten",
    "category": "country",
    "year": 1789,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Vereinigte Staaten – Verfassungsinkrafttreten.",
    "hint": "Vereinigte Staaten",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/us.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-va",
    "title": "Umriss Vatikanstadt",
    "category": "country",
    "year": 1929,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Vatikanstadt – Lateranverträge",
    "hint": "Vatikanstadt",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/va.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-vc",
    "title": "Umriss St. Vincent und die Grenadinen",
    "category": "country",
    "year": 1985,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "St. Vincent und die Grenadinen – Systembruch.",
    "hint": "St. Vincent und die Grenadinen",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/vc.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ve",
    "title": "Umriss Venezuela",
    "category": "country",
    "year": 1999,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Venezuela – Bolivarische Verfassung.",
    "hint": "Venezuela",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ve.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-vg",
    "title": "Umriss Britische Jungferninseln",
    "category": "country",
    "year": 2007,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Britische Jungferninseln – Verfassungsordnung.",
    "hint": "Britische Jungferninseln",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/vg.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-vn",
    "title": "Umriss Vietnam",
    "category": "country",
    "year": 1975,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Vietnam – Wiedervereinigung",
    "hint": "Vietnam",
    "difficulty": "leicht",
    "sources": {
      "image": "/assets/country-outlines/vn.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-vu",
    "title": "Umriss Vanuatu",
    "category": "country",
    "year": 1980,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Vanuatu – Unabhängigkeit",
    "hint": "Vanuatu",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/vu.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-wf",
    "title": "Umriss Wallis und Futuna",
    "category": "country",
    "year": 1961,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Wallis und Futuna – Überseegebiet-Status.",
    "hint": "Wallis und Futuna",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/wf.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ws",
    "title": "Umriss Samoa",
    "category": "country",
    "year": 1962,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Samoa – Unabhängigkeit.",
    "hint": "Samoa",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/ws.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-ye",
    "title": "Umriss Jemen",
    "category": "country",
    "year": 1990,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Jemen – Wiedervereinigung",
    "hint": "Jemen",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/ye.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-yt",
    "title": "Umriss Mayotte",
    "category": "country",
    "year": 2011,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Mayotte – Departement-Status.",
    "hint": "Mayotte",
    "difficulty": "schwer",
    "sources": {
      "image": "/assets/country-outlines/yt.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-za",
    "title": "Umriss Südafrika",
    "category": "country",
    "year": 1994,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Südafrika – Erste freie Wahlen (Ende Apartheid)",
    "hint": "Südafrika",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/za.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-zm",
    "title": "Umriss Sambia",
    "category": "country",
    "year": 1964,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Sambia – Unabhängigkeit",
    "hint": "Sambia",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/zm.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  },
  {
    "id": "outline-zw",
    "title": "Umriss Simbabwe",
    "category": "country",
    "year": 1980,
    "cue": "Zu welchem Land gehört dieser Umriss und wann wurde es gegründet?",
    "answer": "Simbabwe – Unabhängigkeit",
    "hint": "Simbabwe",
    "difficulty": "mittel",
    "sources": {
      "image": "/assets/country-outlines/zw.png",
      "text": "mapsicon by djaiss (CC BY 4.0)"
    }
  }
];

