export type PartnerKannCategory = 'wissen' | 'geschick' | 'sinne' | 'talent';

export type PartnerKannTask = {
  id: string;
  category: PartnerKannCategory;
  text: string;
};

export const partnerKannCategoryLabels: Record<PartnerKannCategory, string> = {
  wissen: 'Wissen & Merken',
  geschick: 'Geschick & Körper',
  sinne: 'Sinne',
  talent: 'Talent & Auftritt',
};

export const partnerKannCategoryIcons: Record<PartnerKannCategory, string> = {
  wissen: '🧠',
  geschick: '🤸',
  sinne: '👃',
  talent: '🎭',
};

export const partnerKannCategories: PartnerKannCategory[] = ['wissen', 'geschick', 'sinne', 'talent'];

export const partnerKannTasks: PartnerKannTask[] = [
  // ─── Wissen & Merken ───
  { id: 'wissen-1', category: 'wissen', text: 'Wie viele deutsche Bundesländer kann er/sie in 30 Sekunden nennen, ohne eines zu wiederholen?' },
  { id: 'wissen-2', category: 'wissen', text: 'Wie viele Mitgliedsstaaten der Europäischen Union kann er/sie in 60 Sekunden aufzählen?' },
  { id: 'wissen-3', category: 'wissen', text: 'Wie viele Nachbarländer Deutschlands kann er/sie in 20 Sekunden fehlerfrei aufzählen?' },
  { id: 'wissen-4', category: 'wissen', text: 'Wie viele deutsche Flüsse kann er/sie in 45 Sekunden nennen?' },
  { id: 'wissen-5', category: 'wissen', text: 'Wie viele Weltmeere kann er/sie in 15 Sekunden aufzählen?' },
  { id: 'wissen-6', category: 'wissen', text: 'Wie viele Kontinente kann er/sie in 10 Sekunden nennen?' },
  { id: 'wissen-7', category: 'wissen', text: 'Wie viele Hauptstädte Südamerikas kann er/sie in 60 Sekunden richtig einem von fünf genannten Ländern zuordnen?' },
  { id: 'wissen-8', category: 'wissen', text: 'Wie viele Wüsten der Welt kann er/sie in 40 Sekunden aufzählen?' },
  { id: 'wissen-9', category: 'wissen', text: 'Wie viele Inseln im Mittelmeer kann er/sie in 30 Sekunden nennen?' },
  { id: 'wissen-10', category: 'wissen', text: 'Wie viele deutsche Städte mit mehr als 500.000 Einwohnern kann er/sie in 45 Sekunden aufzählen?' },
  { id: 'wissen-11', category: 'wissen', text: 'Wie viele Automarken kann er/sie in 30 Sekunden nennen?' },
  { id: 'wissen-12', category: 'wissen', text: 'Wie viele aktuelle Vereine der Fußball-Bundesliga kann er/sie in 45 Sekunden aufzählen?' },
  { id: 'wissen-13', category: 'wissen', text: 'Wie viele Vornamen mit dem Anfangsbuchstaben „S" fallen ihm/ihr in 30 Sekunden ein?' },
  { id: 'wissen-14', category: 'wissen', text: 'Wie viele Planeten des Sonnensystems kann er/sie in der richtigen Reihenfolge von der Sonne aus in 20 Sekunden aufsagen?' },
  { id: 'wissen-15', category: 'wissen', text: 'Wie viele Tierarten, die typischerweise in einem Zoo leben, fallen ihm/ihr in 30 Sekunden ein?' },
  { id: 'wissen-16', category: 'wissen', text: 'Wie viele in Deutschland heimische Vogelarten kann er/sie in 30 Sekunden nennen?' },
  { id: 'wissen-17', category: 'wissen', text: 'Wie viele Käsesorten kann er/sie in 30 Sekunden aufzählen?' },
  { id: 'wissen-18', category: 'wissen', text: 'Wie viele Biermarken kann er/sie in 30 Sekunden nennen?' },
  { id: 'wissen-19', category: 'wissen', text: 'Wie viele Obstsorten kann er/sie in 30 Sekunden aufzählen?' },
  { id: 'wissen-20', category: 'wissen', text: 'Wie viele Gemüsesorten kann er/sie in 30 Sekunden aufzählen?' },
  { id: 'wissen-21', category: 'wissen', text: 'Wie lange braucht er/sie, um das Alphabet rückwärts (von Z bis A) fehlerfrei aufzusagen (in Sekunden)?' },
  { id: 'wissen-22', category: 'wissen', text: 'Wie viele Länder, deren Flagge nur aus zwei Farben besteht, kann er/sie in 30 Sekunden nennen?' },
  { id: 'wissen-23', category: 'wissen', text: 'Wie viele Wörter, die mit demselben vorgegebenen Buchstaben beginnen, fallen ihm/ihr innerhalb von 30 Sekunden ein?' },
  { id: 'wissen-24', category: 'wissen', text: 'Wie viele englische Wörter, die mit einem vorgegebenen Buchstaben beginnen, fallen ihm/ihr in 30 Sekunden ein?' },
  { id: 'wissen-25', category: 'wissen', text: 'Wie viele Wörter, die sich auf ein vorgegebenes Wort reimen, fallen ihm/ihr in 30 Sekunden ein?' },
  { id: 'wissen-26', category: 'wissen', text: 'Wie viele zusammengesetzte Wörter mit dem Grundwort „Haus" fallen ihm/ihr in 30 Sekunden ein?' },
  { id: 'wissen-27', category: 'wissen', text: 'Wie viele von 15 vorgelesenen Einkaufslisten-Artikeln kann er/sie danach korrekt wiederholen?' },
  { id: 'wissen-28', category: 'wissen', text: 'Wie viele von 10 vorgelesenen zweistelligen Zahlen kann er/sie danach in der richtigen Reihenfolge wiederholen?' },
  { id: 'wissen-29', category: 'wissen', text: 'Wie viele von 12 auf einem Tablett gezeigten Alltagsgegenständen kann er/sie nach 30 Sekunden Anschauen aufzählen, nachdem das Tablett weggenommen wurde?' },
  { id: 'wissen-30', category: 'wissen', text: 'Wie viele von 8 vorgelesenen Ländernamen kann er/sie danach in der richtigen Reihenfolge wiederholen?' },
  { id: 'wissen-31', category: 'wissen', text: 'Wie viele Ziffern einer einmal vorgelesenen 10-stelligen Zahl kann er/sie danach in der richtigen Reihenfolge wiederholen?' },
  { id: 'wissen-32', category: 'wissen', text: 'Wie viele von 10 vorgelesenen Tiernamen kann er/sie nach einer Minute Ablenkung noch korrekt nennen?' },
  { id: 'wissen-33', category: 'wissen', text: 'Wie viele von 8 vorgelesenen Abbiegungen (links/rechts) einer fiktiven Wegbeschreibung kann er/sie danach in der richtigen Reihenfolge wiederholen?' },
  { id: 'wissen-34', category: 'wissen', text: 'Wie viele von 6 für 10 Sekunden gezeigten Spielkarten kann er/sie danach mit Wert und Farbe korrekt benennen?' },
  { id: 'wissen-35', category: 'wissen', text: 'Wie viele von 10 vorgelesenen Wortpaaren kann er/sie richtig ergänzen, wenn ihm/ihr danach nur das erste Wort jedes Paares genannt wird?' },
  { id: 'wissen-36', category: 'wissen', text: 'Wie viele von 5 vorgelesenen Geburtsdaten fiktiver Personen kann er/sie danach korrekt wiederholen?' },
  { id: 'wissen-37', category: 'wissen', text: 'Wie viele einfache Kopfrechenaufgaben (Addition zweistelliger Zahlen) kann er/sie in 60 Sekunden richtig lösen?' },
  { id: 'wissen-38', category: 'wissen', text: 'Wie viele Aufgaben aus dem kleinen Einmaleins kann er/sie in 60 Sekunden richtig lösen?' },
  { id: 'wissen-39', category: 'wissen', text: 'Wie viele Subtraktionsaufgaben mit zweistelligen Zahlen kann er/sie in 45 Sekunden richtig lösen?' },
  { id: 'wissen-40', category: 'wissen', text: 'Wie viele Prozentrechnungen (zum Beispiel 20 % von 150) kann er/sie in 60 Sekunden richtig lösen?' },
  { id: 'wissen-41', category: 'wissen', text: 'Wie viele Quadratzahlen von 11² bis 20² kann er/sie in 60 Sekunden richtig nennen?' },
  { id: 'wissen-42', category: 'wissen', text: 'Wie schnell kann er/sie von 100 in 7er-Schritten rückwärts bis unter 10 zählen, ohne einen Fehler zu machen (in Sekunden)?' },
  { id: 'wissen-43', category: 'wissen', text: 'Wie oft in Folge kann er/sie eine ihm/ihr zugerufene Zahl zwischen 1 und 50 richtig als Primzahl oder keine Primzahl einordnen, bevor der erste Fehler passiert?' },
  { id: 'wissen-44', category: 'wissen', text: 'Wie weit kann er/sie die Nachkommastellen von Pi (3,14...) fehlerfrei aufsagen?' },
  { id: 'wissen-45', category: 'wissen', text: 'Wie oft in Folge kann er/sie ein zugerufenes Land korrekt der richtigen Hauptstadt zuordnen, bevor der erste Fehler passiert?' },
  { id: 'wissen-46', category: 'wissen', text: 'Wie hoch kann er/sie auf Englisch in 20 Sekunden zählen, ohne eine Zahl auszulassen?' },
  { id: 'wissen-47', category: 'wissen', text: 'Wie viele deutsche Nationalspieler (aktuell oder ehemalig) kann er/sie in 30 Sekunden nennen?' },
  { id: 'wissen-48', category: 'wissen', text: 'Wie viele Elemente des Periodensystems kann er/sie in 60 Sekunden korrekt nennen?' },
  { id: 'wissen-49', category: 'wissen', text: 'Wie viele Wörter, die auf „-tion" enden, kann er/sie in 30 Sekunden nennen?' },
  { id: 'wissen-50', category: 'wissen', text: 'Wie viele Wörter mit einem Doppelbuchstaben (z. B. „Kaffee") kann er/sie in 30 Sekunden nennen?' },
  { id: 'wissen-51', category: 'wissen', text: 'Wie viele Länder, die ans Mittelmeer grenzen, kann er/sie in 30 Sekunden nennen?' },
  { id: 'wissen-52', category: 'wissen', text: 'Wie viele Hauptstädte Europas kann er/sie in 45 Sekunden richtig nennen?' },
  { id: 'wissen-53', category: 'wissen', text: 'Wie viele Wörter, die rückwärts gelesen wieder ein Wort ergeben (Palindrome, z. B. „Anna"), fallen ihm/ihr in 45 Sekunden ein?' },
  { id: 'wissen-54', category: 'wissen', text: 'Wie viele Redewendungen mit einem Tier darin fallen ihm/ihr in 45 Sekunden ein?' },
  { id: 'wissen-55', category: 'wissen', text: 'Wie viele Wochentage kann er/sie rückwärts, von Sonntag bis Montag, in 10 Sekunden fehlerfrei aufsagen?' },
  { id: 'wissen-56', category: 'wissen', text: 'Wie viele Wörter mit einem doppelten Vokal (z. B. „Boot") fallen ihm/ihr in 30 Sekunden ein?' },
  { id: 'wissen-57', category: 'wissen', text: 'Wie hoch kann er/sie in 3er-Schritten in 20 Sekunden zählen, ohne einen Fehler zu machen?' },
  { id: 'wissen-58', category: 'wissen', text: 'Wie viele zusammengesetzte Wörter mit dem Grundwort „Sonne" fallen ihm/ihr in 30 Sekunden ein?' },
  { id: 'wissen-59', category: 'wissen', text: 'Wie viele Monate mit genau 31 Tagen kann er/sie in 20 Sekunden richtig nennen?' },
  { id: 'wissen-60', category: 'wissen', text: 'Wie viele Wörter, die aus genau drei Buchstaben bestehen, fallen ihm/ihr in 30 Sekunden ein?' },

  // ─── Geschick & Körper ───
  { id: 'geschick-1', category: 'geschick', text: 'Wie lange kann er/sie ein Buch flach auf dem Kopf balancieren, während er/sie langsam durch den Raum geht, ohne dass es herunterfällt (in Sekunden)?' },
  { id: 'geschick-2', category: 'geschick', text: 'Wie viele Kniebeugen kann er/sie in 30 Sekunden korrekt ausführen?' },
  { id: 'geschick-3', category: 'geschick', text: 'Wie viele Liegestütze kann er/sie in 30 Sekunden schaffen?' },
  { id: 'geschick-4', category: 'geschick', text: 'Wie lange kann er/sie im Unterarmstütz durchhalten, ohne die Hüfte absinken zu lassen (in Sekunden)?' },
  { id: 'geschick-5', category: 'geschick', text: 'Wie lange kann er/sie im Wandsitz mit rechtwinklig gebeugten Knien an der Wand durchhalten (in Sekunden)?' },
  { id: 'geschick-6', category: 'geschick', text: 'Wie viele Münzen kann er/sie zu einem einzigen Turm aufeinanderstapeln, bevor er umfällt?' },
  { id: 'geschick-7', category: 'geschick', text: 'Wie viele Bauklötze kann er/sie zu einem Turm stapeln, bevor er umfällt?' },
  { id: 'geschick-8', category: 'geschick', text: 'Wie weit kann er/sie einen zusammengeknüllten Papierball im Stehen in einen Mülleimer werfen (in Metern, ab dem die meisten Würfe noch treffen)?' },
  { id: 'geschick-9', category: 'geschick', text: 'Wie oft kann er/sie in 60 Sekunden einen aufgeblasenen Luftballon in die Luft schlagen, ohne dass er den Boden berührt?' },
  { id: 'geschick-10', category: 'geschick', text: 'Wie oft kann er/sie bei 10 Würfen aus einem Meter Entfernung einen Ring aus Pappe über den Hals einer Flasche werfen?' },
  { id: 'geschick-11', category: 'geschick', text: 'Wie oft kann er/sie bei 10 Würfen aus einem Meter Entfernung mit einem zusammengeknüllten Stück Papier einen Becher treffen?' },
  { id: 'geschick-12', category: 'geschick', text: 'Wie lange kann er/sie einen Stift senkrecht auf einer Fingerspitze balancieren, ohne dass er umfällt (in Sekunden)?' },
  { id: 'geschick-13', category: 'geschick', text: 'Wie viele Perlen kann er/sie in 60 Sekunden einzeln auf eine Schnur auffädeln?' },
  { id: 'geschick-14', category: 'geschick', text: 'Wie viele Wäscheklammern kann er/sie in 60 Sekunden an den Rand einer Schüssel klemmen?' },
  { id: 'geschick-15', category: 'geschick', text: 'Wie viele Dominosteine kann er/sie in 60 Sekunden aufrecht hintereinander aufstellen, ohne dass die Reihe vorzeitig umfällt?' },
  { id: 'geschick-16', category: 'geschick', text: 'Wie schnell kann er/sie 10 Wäscheklammern an eine gespannte Schnur klemmen (in Sekunden)?' },
  { id: 'geschick-17', category: 'geschick', text: 'Wie schnell kann er/sie ein Kartenspiel mit 32 Karten von Hand einmal komplett mischen (in Sekunden)?' },
  { id: 'geschick-18', category: 'geschick', text: 'Wie oft kann er/sie in 30 Sekunden einen Tischtennisball auf einem Buch hochspringen lassen, ohne dass er herunterfällt?' },
  { id: 'geschick-19', category: 'geschick', text: 'Wie lange kann er/sie einen Wasserball mit ausgestrecktem Arm über dem Kopf halten, ohne den Arm abzusenken (in Sekunden)?' },
  { id: 'geschick-20', category: 'geschick', text: 'Wie viele Socken kann er/sie in 60 Sekunden aus einem Wäschekorb ziehen und nach Farbe sortiert auf zwei Stapel legen?' },
  { id: 'geschick-21', category: 'geschick', text: 'Wie weit kann er/sie einen Luftballon mit einem einzigen Schlag der flachen Hand wegschlagen, bevor er den Boden berührt (in Metern)?' },
  { id: 'geschick-22', category: 'geschick', text: 'Wie hoch kann er/sie beim Strecksprung mit einer Hand an die Wand reichen, gemessen als Differenz zur Reichweite im Stehen (in Zentimetern)?' },
  { id: 'geschick-23', category: 'geschick', text: 'Wie weit kann er/sie aus dem Stand nach vorne springen (in Zentimetern)?' },
  { id: 'geschick-24', category: 'geschick', text: 'Wie lange kann er/sie eine Münze auf einem Löffel balancieren, während er/sie zehn Schritte geht, ohne dass sie herunterfällt (in Sekunden)?' },
  { id: 'geschick-25', category: 'geschick', text: 'Wie lange kann er/sie auf einem Bein hüpfend eine zwei Meter lange Strecke zurücklegen, ohne den anderen Fuß abzusetzen (in Sekunden)?' },
  { id: 'geschick-26', category: 'geschick', text: 'Wie viele Strohhalme kann er/sie in 30 Sekunden einzeln aus einem Bündel ziehen, ohne dass ein zweiter mit herauskommt?' },
  { id: 'geschick-27', category: 'geschick', text: 'Wie viele Büroklammern kann er/sie in 60 Sekunden zu einer durchgehenden Kette zusammenstecken?' },
  { id: 'geschick-28', category: 'geschick', text: 'Wie schnell kann er/sie 6 Becher zu einer Pyramide aufstapeln und anschließend wieder zu einem einzigen Stapel zusammensetzen (in Sekunden)?' },
  { id: 'geschick-29', category: 'geschick', text: 'Wie viele Erbsen kann er/sie in 30 Sekunden einzeln mit Zeigefinger und Daumen aufheben und in eine Schüssel legen?' },
  { id: 'geschick-30', category: 'geschick', text: 'Wie oft kann er/sie bei 10 Versuchen eine Münze aus 50 Zentimetern Höhe in ein schmales Glas fallen lassen?' },
  { id: 'geschick-31', category: 'geschick', text: 'Wie schnell kann er/sie eine Rolle Toilettenpapier zehnmal um ein Tischbein wickeln (in Sekunden)?' },
  { id: 'geschick-32', category: 'geschick', text: 'Wie weit entfernt kann er/sie noch eine zusammengerollte Socke sicher in einen Wäschekorb werfen (in Metern, ab dem die meisten Würfe noch treffen)?' },
  { id: 'geschick-33', category: 'geschick', text: 'Wie lange kann er/sie ein Kissen zwischen Kopf und Schulter eingeklemmt halten, während er/sie zehn Schritte geht, ohne dass es herunterfällt (in Sekunden)?' },
  { id: 'geschick-34', category: 'geschick', text: 'Wie oft kann er/sie in 30 Sekunden mit Daumen und kleinem Finger derselben Hand abwechselnd so schnell wie möglich aneinandertippen?' },
  { id: 'geschick-35', category: 'geschick', text: 'Wie lange kann er/sie beide Arme seitlich auf Schulterhöhe ausgestreckt halten, ohne sie absinken zu lassen (in Sekunden)?' },
  { id: 'geschick-36', category: 'geschick', text: 'Wie schnell kann er/sie ein fallen gelassenes Lineal zwischen zwei Fingern auffangen, gemessen an der Zentimeter-Markierung, an der die Finger zugreifen?' },
  { id: 'geschick-37', category: 'geschick', text: 'Wie schnell kann er/sie fünf einfache Knoten hintereinander in eine Schnur binden (in Sekunden)?' },
  { id: 'geschick-38', category: 'geschick', text: 'Wie viele Etagen kann er/sie in 3 Minuten von einem Kartenhaus aus Spielkarten bauen, bevor es einstürzt?' },
  { id: 'geschick-39', category: 'geschick', text: 'Wie weit kann er/sie einen Tischtennisball allein durch Pusten über einen Tisch bewegen (in Zentimetern)?' },
  { id: 'geschick-40', category: 'geschick', text: 'Wie lange kann er/sie eine leere Klopapierrolle auf dem ausgestreckten Zeigefinger drehen lassen, ohne dass sie herunterfällt (in Sekunden)?' },
  { id: 'geschick-41', category: 'geschick', text: 'Wie oft kann er/sie in 60 Sekunden eine Büroklammer auf dem Handrücken hochwerfen und wieder auffangen, ohne dass sie herunterfällt?' },
  { id: 'geschick-42', category: 'geschick', text: 'Wie lange kann er/sie mit geschlossenen Augen auf einem Bein stehen, ohne den anderen Fuß abzusetzen (in Sekunden)?' },
  { id: 'geschick-43', category: 'geschick', text: 'Wie viele Gummibänder kann er/sie in 30 Sekunden über die vier Finger einer Hand ziehen, ohne den Daumen zu benutzen?' },
  { id: 'geschick-44', category: 'geschick', text: 'Wie weit kann er/sie ein zerknülltes Papierkügelchen mit einem gespannten Gummiband über den Tisch schießen (in Zentimetern)?' },
  { id: 'geschick-45', category: 'geschick', text: 'Wie viele Runden kann er/sie in 30 Sekunden einen Stift von einem Finger zum nächsten rollen lassen, ohne dass er herunterfällt?' },
  { id: 'geschick-46', category: 'geschick', text: 'Wie schnell kann er/sie 5 T-Shirts ordentlich zusammenlegen (in Sekunden)?' },
  { id: 'geschick-47', category: 'geschick', text: 'Wie viele Schritte kann er/sie mit einem randvoll gefüllten Wasserglas in der Hand gehen, ohne dass etwas verschüttet wird?' },
  { id: 'geschick-48', category: 'geschick', text: 'Wie oft kann er/sie in die Hände klatschen, bevor er/sie einen hochgeworfenen Tischtennisball mit derselben Hand wieder auffängt?' },
  { id: 'geschick-49', category: 'geschick', text: 'Wie oft kann er/sie in 30 Sekunden eine Münze von der Tischkante in ein Glas schnipsen?' },
  { id: 'geschick-50', category: 'geschick', text: 'Wie oft kann er/sie in 30 Sekunden eine Spielkarte aus der Hand fächerartig aufblättern und wieder zu einem Stapel zusammenschieben (volle Zyklen)?' },
  { id: 'geschick-51', category: 'geschick', text: 'Wie lange kann er/sie auf einem Bein stehen, während er/sie gleichzeitig mit geschlossenen Augen beide Arme kreisen lässt, ohne den Fuß abzusetzen (in Sekunden)?' },
  { id: 'geschick-52', category: 'geschick', text: 'Wie oft kann er/sie in 30 Sekunden abwechselnd mit dem rechten und dem linken Zeigefinger die Nasenspitze berühren?' },
  { id: 'geschick-53', category: 'geschick', text: 'Wie viele Storchenschritte (großer Schritt mit hoch angezogenem Knie) kann er/sie in 20 Sekunden auf der Stelle machen?' },
  { id: 'geschick-54', category: 'geschick', text: 'Wie lange kann er/sie mit ausgestreckten Armen ein unsichtbares Tablett balancieren, ohne die Arme absinken zu lassen (in Sekunden)?' },
  { id: 'geschick-55', category: 'geschick', text: 'Wie oft kann er/sie in 30 Sekunden in die Hocke gehen und wieder aufstehen, ohne die Hände zu Hilfe zu nehmen?' },
  { id: 'geschick-56', category: 'geschick', text: 'Wie lange kann er/sie im Zehenstand balancieren, ohne die Fersen abzusetzen (in Sekunden)?' },
  { id: 'geschick-57', category: 'geschick', text: 'Wie oft kann er/sie in 20 Sekunden mit dem ausgestreckten Arm eine Acht in die Luft zeichnen, ohne den Rhythmus zu verlieren?' },
  { id: 'geschick-58', category: 'geschick', text: 'Wie viele Ausfallschritte, abwechselnd mit links und rechts, kann er/sie in 30 Sekunden korrekt ausführen?' },
  { id: 'geschick-59', category: 'geschick', text: 'Wie oft gelingt es ihm/ihr bei 5 Versuchen, mit verschränkten Armen aus der Hocke aufzustehen, ohne die Arme zu lösen?' },
  { id: 'geschick-60', category: 'geschick', text: 'Wie lange kann er/sie rückwärtsgehen, ohne sich umzudrehen oder das Gleichgewicht zu verlieren (in Sekunden, bis maximal 30)?' },

  // ─── Sinne ───
  { id: 'sinne-1', category: 'sinne', text: 'Wie viele von 6 Gewürzen kann er/sie mit verbundenen Augen allein am Geruch richtig benennen?' },
  { id: 'sinne-2', category: 'sinne', text: 'Wie viele von 8 Süßigkeiten kann er/sie mit geschlossenen Augen allein durch Ertasten richtig erkennen?' },
  { id: 'sinne-3', category: 'sinne', text: 'Wie viele von 6 Getränken kann er/sie mit verbundenen Augen allein am Geschmack richtig benennen?' },
  { id: 'sinne-4', category: 'sinne', text: 'Wie viele von 5 unterschiedlich langen Bändern kann er/sie mit geschlossenen Augen allein durch Ertasten richtig von kurz bis lang sortieren?' },
  { id: 'sinne-5', category: 'sinne', text: 'Wie viele von 7 Musiktiteln kann er/sie an den ersten drei Sekunden richtig erkennen?' },
  { id: 'sinne-6', category: 'sinne', text: 'Wie viele von 5 Kräutern kann er/sie mit verbundenen Augen allein am Duft richtig unterscheiden?' },
  { id: 'sinne-7', category: 'sinne', text: 'Wie viele von 4 Kaffeesorten kann er/sie mit verbundenen Augen allein am Geruch richtig erkennen?' },
  { id: 'sinne-8', category: 'sinne', text: 'Wie viele von 6 Obstsorten kann er/sie mit verbundenen Augen allein am Geruch richtig benennen?' },
  { id: 'sinne-9', category: 'sinne', text: 'Wie viele von 5 Duftölen kann er/sie mit verbundenen Augen den richtigen Fläschchen zuordnen?' },
  { id: 'sinne-10', category: 'sinne', text: 'Wie viele von 6 Gemüsesorten kann er/sie blind verkostet richtig erkennen?' },
  { id: 'sinne-11', category: 'sinne', text: 'Wie viele von 8 Chipssorten kann er/sie mit verbundenen Augen allein am Geschmack richtig benennen?' },
  { id: 'sinne-12', category: 'sinne', text: 'Wie viele von 5 Käsesorten kann er/sie blind verkostet richtig erkennen?' },
  { id: 'sinne-13', category: 'sinne', text: 'Wie viele von 6 Fruchtsäften kann er/sie mit verbundenen Augen allein am Geschmack richtig benennen?' },
  { id: 'sinne-14', category: 'sinne', text: 'Wie viele von 5 Schokoladensorten kann er/sie blind verkostet richtig unterscheiden?' },
  { id: 'sinne-15', category: 'sinne', text: 'Wie viele von 4 Essigsorten kann er/sie mit verbundenen Augen allein am Geschmack unterscheiden?' },
  { id: 'sinne-16', category: 'sinne', text: 'Wie viele von 6 Brotsorten kann er/sie blind verkostet richtig benennen?' },
  { id: 'sinne-17', category: 'sinne', text: 'Wie viele von 5 Honigsorten kann er/sie mit verbundenen Augen allein am Geschmack richtig erkennen?' },
  { id: 'sinne-18', category: 'sinne', text: 'Wie viele von 5 Teesorten kann er/sie blind verkostet richtig erkennen?' },
  { id: 'sinne-19', category: 'sinne', text: 'Wie viele von 6 Nusssorten kann er/sie mit verbundenen Augen allein am Geschmack richtig benennen?' },
  { id: 'sinne-20', category: 'sinne', text: 'Wie viele von 8 Stoffarten kann er/sie mit verbundenen Augen allein durch Ertasten richtig benennen?' },
  { id: 'sinne-21', category: 'sinne', text: 'Wie viele von 6 Haushaltsgegenständen kann er/sie mit verbundenen Augen allein durch Ertasten richtig erkennen?' },
  { id: 'sinne-22', category: 'sinne', text: 'Wie viele von 5 Obstsorten kann er/sie mit verbundenen Augen allein durch Ertasten richtig erkennen?' },
  { id: 'sinne-23', category: 'sinne', text: 'Wie viele von 6 Münzen kann er/sie mit geschlossenen Augen allein durch Ertasten richtig dem Wert nach sortieren?' },
  { id: 'sinne-24', category: 'sinne', text: 'Wie viele von 5 unterschiedlich schweren, gleich großen Päckchen kann er/sie mit geschlossenen Augen allein durch Wiegen in der Hand richtig von leicht bis schwer sortieren?' },
  { id: 'sinne-25', category: 'sinne', text: 'Wie viele von 5 unterschiedlich hohen Gegenständen kann er/sie mit geschlossenen Augen allein durch Ertasten richtig von niedrig bis hoch sortieren?' },
  { id: 'sinne-26', category: 'sinne', text: 'Wie viele von 5 Materialien (z. B. Holz, Stein, Metall, Stoff, Plastik) kann er/sie mit verbundenen Augen allein durch Ertasten richtig benennen?' },
  { id: 'sinne-27', category: 'sinne', text: 'Wie viele von 6 unterschiedlich großen Knöpfen kann er/sie mit geschlossenen Augen allein durch Ertasten der Größe nach in die richtige Reihenfolge legen?' },
  { id: 'sinne-28', category: 'sinne', text: 'Wie oft kann er/sie mit verbundenen Augen bei 5 Versuchen richtig ertasten, welche von zwei handwarmen Wasserschalen die wärmere ist?' },
  { id: 'sinne-29', category: 'sinne', text: 'Wie viele von 6 Alltagsgeräuschen kann er/sie mit verbundenen Augen allein am Klang richtig erkennen?' },
  { id: 'sinne-30', category: 'sinne', text: 'Wie viele von 5 Tierlauten kann er/sie mit geschlossenen Augen richtig benennen?' },
  { id: 'sinne-31', category: 'sinne', text: 'Wie viele von 5 Stimmen aus der Gruppe kann er/sie mit verbundenen Augen allein am Klang richtig erkennen?' },
  { id: 'sinne-32', category: 'sinne', text: 'Wie oft kann er/sie mit geschlossenen Augen bei 8 Versuchen die richtige Richtung eines Fingerschnippens im Raum erkennen?' },
  { id: 'sinne-33', category: 'sinne', text: 'Wie viele Klatschgeräusche in einer Serie von bis zu 20 kann er/sie mit verbundenen Augen fehlerfrei mitzählen, bevor er/sie sich zum ersten Mal verzählt?' },
  { id: 'sinne-34', category: 'sinne', text: 'Wie viele von 10 auf einem Tablett gezeigten Gegenständen kann er/sie sich nach 10 Sekunden Betrachtung merken und danach richtig aufzählen?' },
  { id: 'sinne-35', category: 'sinne', text: 'Wie viele von 8 Unterschieden kann er/sie in 60 Sekunden zwischen zwei fast identischen Bildern finden?' },
  { id: 'sinne-36', category: 'sinne', text: 'Wie viele von 6 Blautönen kann er/sie richtig von hell nach dunkel sortieren?' },
  { id: 'sinne-37', category: 'sinne', text: 'Wie viele von bis zu 12 auf dem Tisch ausgebreiteten Gegenständen kann er/sie nach nur einer Sekunde Hinsehen richtig zählen?' },
  { id: 'sinne-38', category: 'sinne', text: 'Wie oft trifft er/sie bei 5 Versuchen mit geschlossenen Augen die exakte Anzahl ertasteter Bonbons in der Hand (jeweils bis zu 20 Stück)?' },
  { id: 'sinne-39', category: 'sinne', text: 'Wie viele von 5 unterschiedlich gesüßten Wasserproben kann er/sie mit verbundenen Augen in der richtigen Süße-Reihenfolge anordnen?' },
  { id: 'sinne-40', category: 'sinne', text: 'Wie viele von 6 Ölsorten kann er/sie blind verkostet richtig unterscheiden?' },
  { id: 'sinne-41', category: 'sinne', text: 'Wie viele von 5 Senfsorten kann er/sie mit verbundenen Augen allein am Geschmack richtig erkennen?' },
  { id: 'sinne-42', category: 'sinne', text: 'Wie viele von 6 Kekssorten kann er/sie blind verkostet richtig benennen?' },
  { id: 'sinne-43', category: 'sinne', text: 'Wie schnell kann er/sie mit verbundenen Augen 5 Gewürze allein am Geruch den richtigen Beschriftungen zuordnen (Zeit in Sekunden)?' },
  { id: 'sinne-44', category: 'sinne', text: 'Wie schnell kann er/sie mit geschlossenen Augen 6 Alltagsgegenstände in einer Tasche allein durch Ertasten richtig identifizieren (Zeit in Sekunden)?' },
  { id: 'sinne-45', category: 'sinne', text: 'Wie schnell kann er/sie mit verbundenen Augen 8 Spielkarten allein durch Ertasten nach Vorder- und Rückseite richtig sortieren (Zeit in Sekunden)?' },
  { id: 'sinne-46', category: 'sinne', text: 'Wie hoch kann er/sie mit verbundenen Augen den Wasserstand in einem Glas allein am Einschenk-Geräusch richtig schätzen (Abweichung in Millilitern)?' },
  { id: 'sinne-47', category: 'sinne', text: 'Wie viele von 5 Zitrusfrüchten kann er/sie mit verbundenen Augen allein am Geruch richtig unterscheiden?' },
  { id: 'sinne-48', category: 'sinne', text: 'Wie viele von 6 Gewürzmischungen kann er/sie blind verkostet richtig benennen?' },
  { id: 'sinne-49', category: 'sinne', text: 'Wie viele von 5 Textilproben (z. B. Seide, Wolle, Baumwolle) kann er/sie mit geschlossenen Augen allein durch Ertasten richtig benennen?' },
  { id: 'sinne-50', category: 'sinne', text: 'Wie viele von 5 unterschiedlich temperierten, aber ungefährlichen Gegenständen (z. B. Wasserflaschen) kann er/sie mit geschlossenen Augen allein durch Ertasten der Temperatur nach richtig von kühl bis warm sortieren?' },
  { id: 'sinne-51', category: 'sinne', text: 'Wie viele unterschiedliche Umgebungsgeräusche kann er/sie in 30 Sekunden mit geschlossenen Augen erkennen und laut benennen?' },
  { id: 'sinne-52', category: 'sinne', text: 'Wie nah kommt er/sie mit geschlossenen Augen an die tatsächliche Anzahl der gerade anwesenden Mitspieler, wenn er/sie sie nur an den Stimmen abzählt?' },
  { id: 'sinne-53', category: 'sinne', text: 'Wie oft erkennt er/sie bei 8 Versuchen mit geschlossenen Augen richtig, aus welcher Richtung gerade in die Hände geklatscht wird?' },
  { id: 'sinne-54', category: 'sinne', text: 'Wie genau kann er/sie mit geschlossenen Augen einschätzen, wie viel Zeit seit dem Startsignal vergangen ist, wenn man ihn/sie nach genau 45 Sekunden fragt (Abweichung in Sekunden)?' },
  { id: 'sinne-55', category: 'sinne', text: 'Wie oft erkennt er/sie bei 8 Versuchen mit geschlossenen Augen richtig, ob er/sie gerade mit einem oder mit zwei Fingern am Arm berührt wird?' },
  { id: 'sinne-56', category: 'sinne', text: 'Wie viele Schritte kann er/sie mit geschlossenen Augen möglichst geradeaus gehen, bevor er/sie merklich von der Linie abweicht?' },
  { id: 'sinne-57', category: 'sinne', text: 'Wie oft erkennt er/sie bei 6 Versuchen mit geschlossenen Augen allein am Tonfall, ob ein vorgelesener Satz als Frage oder als Aussage gemeint war?' },
  { id: 'sinne-58', category: 'sinne', text: 'Wie oft erkennt er/sie bei 6 Versuchen mit geschlossenen Augen, welche von zwei Personen gerade seine/ihre Hand berührt hat?' },
  { id: 'sinne-59', category: 'sinne', text: 'Wie genau kann er/sie mit geschlossenen Augen die Entfernung zu einer sprechenden Person schätzen (Abweichung in Schritten)?' },
  { id: 'sinne-60', category: 'sinne', text: 'Wie oft erkennt er/sie bei 8 Versuchen mit geschlossenen Augen allein am Klang des Fingerschnippens, welches Gruppenmitglied gerade geschnippt hat?' },

  // ─── Talent & Auftritt ───
  { id: 'talent-1', category: 'talent', text: 'Wie lange kann er/sie einen einzelnen Ton ohne Luftholen halten (in Sekunden)?' },
  { id: 'talent-2', category: 'talent', text: 'Wie oft kann er/sie einen vorgegebenen Zungenbrecher in 30 Sekunden fehlerfrei hintereinander sagen?' },
  { id: 'talent-3', category: 'talent', text: 'Wie lange kann er/sie ein rollendes R ohne Unterbrechung rollen (in Sekunden)?' },
  { id: 'talent-4', category: 'talent', text: 'Wie viele Töne einer bekannten Melodie kann er/sie so pfeifen, dass die Gruppe sie richtig erkennt (Treffer von 10 vorgegebenen Tönen)?' },
  { id: 'talent-5', category: 'talent', text: 'Wie viele Töne einer bekannten Melodie kann er/sie nur summend, ohne den Text zu singen, so vorsummen, dass die Gruppe sie richtig erkennt (Treffer von 10 vorgegebenen Tönen)?' },
  { id: 'talent-6', category: 'talent', text: 'Wie oft kann er/sie in 20 Sekunden zwischen einem sehr hohen und einem sehr tiefen Ton hin und her wechseln?' },
  { id: 'talent-7', category: 'talent', text: 'Wie viele von 10 vorgegebenen Wörtern kann er/sie flüsternd so aussprechen, dass die Gruppe sie aus 5 Metern Entfernung richtig versteht?' },
  { id: 'talent-8', category: 'talent', text: 'Wie lange kann er/sie frei zu einem vorgegebenen Thema sprechen, ohne eine Pause von mehr als 3 Sekunden zu machen (in Sekunden bis zur ersten längeren Pause)?' },
  { id: 'talent-9', category: 'talent', text: 'Wie viele einfache vorgegebene Wörter kann er/sie in 30 Sekunden rückwärts buchstabiert korrekt aussprechen?' },
  { id: 'talent-10', category: 'talent', text: 'Wie viele Wörter einer Fremdsprache kann er/sie in 30 Sekunden korrekt aufsagen?' },
  { id: 'talent-11', category: 'talent', text: 'Wie viele Gegenstände im Raum kann er/sie in 30 Sekunden in einer Fremdsprache korrekt benennen?' },
  { id: 'talent-12', category: 'talent', text: 'Wie viele Reime auf ein vorgegebenes Wort kann er/sie in 30 Sekunden finden?' },
  { id: 'talent-13', category: 'talent', text: 'Wie viele Synonyme für ein vorgegebenes Wort kann er/sie in 30 Sekunden nennen?' },
  { id: 'talent-14', category: 'talent', text: 'Wie viele Tiergeräusche kann er/sie so vormachen, dass die Gruppe sie richtig errät (Treffer von 10 vorgegebenen Tieren)?' },
  { id: 'talent-15', category: 'talent', text: 'Wie viele Berufe kann er/sie ohne Worte so pantomimisch darstellen, dass die Gruppe sie richtig errät (Treffer von 10 vorgegebenen Berufen)?' },
  { id: 'talent-16', category: 'talent', text: 'Wie viele von 5 vorgegebenen Emotionen kann er/sie nur mit der Mimik so darstellen, dass die Gruppe sie richtig errät?' },
  { id: 'talent-17', category: 'talent', text: 'Wie viele Prominente kann er/sie stumm so nachahmen, dass die Gruppe sie richtig errät (Treffer von 8 vorgegebenen Personen)?' },
  { id: 'talent-18', category: 'talent', text: 'Wie viele Filmtitel kann er/sie pantomimisch so vorspielen, dass die Gruppe sie richtig errät (Treffer von 8 vorgegebenen Titeln)?' },
  { id: 'talent-19', category: 'talent', text: 'Wie viele unterschiedliche Akzente kann er/sie beim Sprechen desselben Satzes so vorführen, dass die Gruppe sie richtig dem passenden Land zuordnet (Treffer von 5 vorgegebenen Akzenten)?' },
  { id: 'talent-20', category: 'talent', text: 'Wie viele Sportarten kann er/sie pantomimisch so darstellen, dass die Gruppe sie richtig errät (Treffer von 8 vorgegebenen Sportarten)?' },
  { id: 'talent-21', category: 'talent', text: 'Wie oft kann er/sie einen vorgeklatschten Rhythmus aus 8 Schlägen fehlerfrei nachklatschen, bevor ein Fehler passiert?' },
  { id: 'talent-22', category: 'talent', text: 'Wie viele unterschiedliche Rhythmus-Muster aus einer vorbereiteten Liste kann er/sie in 60 Sekunden korrekt nachklatschen?' },
  { id: 'talent-23', category: 'talent', text: 'Wie oft kann er/sie bei 5 Versuchen einen vorgesungenen Ton so treffen, dass die Gruppe ihn als richtig getroffen bewertet?' },
  { id: 'talent-24', category: 'talent', text: 'Wie oft kann er/sie in 30 Sekunden im exakten Takt eines vorgegebenen Songs mitklatschen, ohne den Takt zu verlieren (Anzahl Taktschläge in Folge)?' },
  { id: 'talent-25', category: 'talent', text: 'Wie hoch kann er/sie im Stand springen und dabei mit der Hand eine Markierung an der Wand berühren (in Zentimetern)?' },
  { id: 'talent-26', category: 'talent', text: 'Wie weit kann er/sie sich mit durchgestreckten Beinen nach vorne beugen, gemessen am Abstand der Fingerspitzen zum Boden (in Zentimetern)?' },
  { id: 'talent-27', category: 'talent', text: 'Wie hoch kann er/sie das Bein seitlich heben, gemessen an der Höhe des Fußes über dem Boden (in Zentimetern)?' },
  { id: 'talent-28', category: 'talent', text: 'Wie weit kann er/sie die Beine bei einem Spagat-Versuch spreizen, gemessen am Abstand des Beckens zum Boden (in Zentimetern)?' },
  { id: 'talent-29', category: 'talent', text: 'Wie oft kann er/sie sich in 30 Sekunden um die eigene Achse drehen, ohne stehenzubleiben oder das Gleichgewicht zu verlieren?' },
  { id: 'talent-30', category: 'talent', text: 'Wie lange kann er/sie auf einem Bein balancieren und dabei gleichzeitig einen vorgegebenen Text fehlerfrei aufsagen (in Sekunden bis zum ersten Fehler oder Absetzen des Fußes)?' },
  { id: 'talent-31', category: 'talent', text: 'Wie oft kann er/sie in 20 Sekunden einen bestimmten Tanzschritt wiederholen?' },
  { id: 'talent-32', category: 'talent', text: 'Wie viele Moonwalk-Schritte kann er/sie hintereinander machen, ohne aus dem Rhythmus zu kommen?' },
  { id: 'talent-33', category: 'talent', text: 'Wie hoch kann er/sie beim Show-Kick das Bein nach vorne strecken, gemessen an der Höhe des Fußes über dem Boden (in Zentimetern)?' },
  { id: 'talent-34', category: 'talent', text: 'Wie lange kann er/sie eine Pose aus einem bekannten Musikvideo oder Film bewegungslos halten (in Sekunden)?' },
  { id: 'talent-35', category: 'talent', text: 'Wie oft kann er/sie in 20 Sekunden zwischen zwei vorgegebenen Gesichtsausdrücken hin und her wechseln?' },
  { id: 'talent-36', category: 'talent', text: 'Wie oft kann er/sie in 20 Sekunden nur eine Augenbraue einzeln heben und wieder senken?' },
  { id: 'talent-37', category: 'talent', text: 'Wie oft kann er/sie in 20 Sekunden mit nur einem Auge zwinkern, ohne dass das andere Auge mitmacht?' },
  { id: 'talent-38', category: 'talent', text: 'Wie viele unterschiedliche Grimassen kann er/sie in 30 Sekunden hintereinander zeigen, die die Gruppe jeweils als klar unterschiedlich anerkennt?' },
  { id: 'talent-39', category: 'talent', text: 'Wie lange kann er/sie ein Pokerface halten, während die Gruppe versucht, ihn/sie zum Lachen zu bringen (in Sekunden bis zum ersten Lachen)?' },
  { id: 'talent-40', category: 'talent', text: 'Wie oft kann er/sie denselben Satz mit jeweils anderer Betonung so sagen, dass die Gruppe jedes Mal die richtige Emotion errät (Treffer von maximal 5 Varianten)?' },
  { id: 'talent-41', category: 'talent', text: 'Wie viele Songs kann er/sie nur summend, ohne den Text zu singen, so vorsummen, dass die Gruppe sie richtig errät (Treffer von 8 vorgegebenen Songs)?' },
  { id: 'talent-42', category: 'talent', text: 'Wie viele Zeilen eines vorgegebenen Liedtexts kann er/sie in 30 Sekunden korrekt mitsingen?' },
  { id: 'talent-43', category: 'talent', text: 'Wie viele Instrumente kann er/sie nur mit dem Mund so imitieren, dass die Gruppe sie richtig errät (Treffer von 6 vorgegebenen Instrumenten)?' },
  { id: 'talent-44', category: 'talent', text: 'Wie oft kann er/sie einen Luftballon in 60 Sekunden nur mit Kopf, Schultern oder Knien in der Luft halten, bevor er den Boden berührt (Anzahl Berührungen)?' },
  { id: 'talent-45', category: 'talent', text: 'Wie viele Bälle oder zusammengeknüllte Socken kann er/sie mindestens 10 Sekunden am Stück gleichzeitig jonglieren?' },
  { id: 'talent-46', category: 'talent', text: 'Wie oft kann er/sie in 30 Sekunden einen Stift wie einen Baton um die Finger drehen, ohne ihn fallen zu lassen?' },
  { id: 'talent-47', category: 'talent', text: 'Wie schnell kann er/sie einen vorgegebenen Zungenbrecher dreimal hintereinander fehlerfrei aufsagen (Zeit in Sekunden)?' },
  { id: 'talent-48', category: 'talent', text: 'Wie schnell kann er/sie eine vorgegebene Abfolge aus 5 festgelegten Tanzschritten einmal komplett fehlerfrei vorführen (Zeit in Sekunden)?' },
  { id: 'talent-49', category: 'talent', text: 'Wie oft kann er/sie in 30 Sekunden hintereinander "Hallo" in einer jeweils anderen Sprache so sagen, dass die Gruppe die Sprache richtig erkennt?' },
  { id: 'talent-50', category: 'talent', text: 'Wie viele Ziffern einer vorgelesenen Zahlenfolge kann er/sie sich merken und anschließend in der richtigen Reihenfolge fehlerfrei aufsagen?' },
  { id: 'talent-51', category: 'talent', text: 'Wie viele Tierarten kann er/sie in 30 Sekunden nur durch Nachahmen ihrer Bewegung, ohne Geräusche, so darstellen, dass die Gruppe sie errät (Treffer von 8 vorgegebenen Tieren)?' },
  { id: 'talent-52', category: 'talent', text: 'Wie lange kann er/sie im Flüsterton sprechen, ohne unfreiwillig lauter zu werden (in Sekunden)?' },
  { id: 'talent-53', category: 'talent', text: 'Wie viele Länder kann er/sie in 30 Sekunden nur durch eine typische Geste oder Pose darstellen, sodass die Gruppe sie errät (Treffer von 6 vorgegebenen Ländern)?' },
  { id: 'talent-54', category: 'talent', text: 'Wie oft kann er/sie in 20 Sekunden zwischen einer hohen Fistelstimme und einer tiefen Stimme wechseln, ohne aus dem Takt zu kommen?' },
  { id: 'talent-55', category: 'talent', text: 'Wie viele Berufe kann er/sie nur durch ein typisches Geräusch, ohne Wörter, so darstellen, dass die Gruppe sie errät (Treffer von 8 vorgegebenen Berufen)?' },
  { id: 'talent-56', category: 'talent', text: 'Wie lange kann er/sie eine frei erfundene Geschichte zu einem vorgegebenen Stichwort ohne Stocken erzählen (in Sekunden bis zur ersten Pause über 3 Sekunden)?' },
  { id: 'talent-57', category: 'talent', text: 'Wie viele Wetterlagen kann er/sie nur mit Körper und Mimik so darstellen, dass die Gruppe sie errät (Treffer von 6 vorgegebenen Wetterlagen)?' },
  { id: 'talent-58', category: 'talent', text: 'Wie oft kann er/sie in 20 Sekunden denselben Satz mit jeweils anderem Akzent sagen, den die Gruppe richtig erkennt (Treffer von maximal 5 Varianten)?' },
  { id: 'talent-59', category: 'talent', text: 'Wie lange kann er/sie eine erfundene Nachrichtensendung im Stil eines Nachrichtensprechers vortragen, ohne zu lachen (in Sekunden)?' },
  { id: 'talent-60', category: 'talent', text: 'Wie viele Emotionen kann er/sie allein durch die Art zu gehen so darstellen, dass die Gruppe sie richtig errät (Treffer von 6 vorgegebenen Emotionen)?' },
];

export type PartnerKannTimerConfig =
  | { mode: 'countdown'; seconds: number }
  | { mode: 'stopwatch' };

/**
 * Liest ein Zeitlimit aus dem Aufgabentext heraus, z.B. "in 30 Sekunden"
 * oder "in 3 Minuten" → Countdown. Aufgaben, bei denen stattdessen die
 * erzielte Dauer selbst das Ergebnis ist (z.B. "... halten (in Sekunden)?"),
 * bekommen stattdessen eine Stoppuhr zum Mitzählen.
 */
export function getPartnerKannTimerConfig(text: string): PartnerKannTimerConfig | null {
  const countdownMatch = text.match(/(\d+)\s*(Sekunden|Minuten)/i);
  if (countdownMatch) {
    const value = parseInt(countdownMatch[1], 10);
    const seconds = /minuten/i.test(countdownMatch[2]) ? value * 60 : value;
    if (seconds > 0 && seconds <= 600) return { mode: 'countdown', seconds };
  }
  if (/sekunden/i.test(text)) return { mode: 'stopwatch' };
  return null;
}
