// AUTO-GENERATED by scripts/sync-playlist.mjs
// Do not edit manually.
import { Card } from './types';

export const playlistCards: Card[] = [
  {
    "id": "song-3-uhr-nachts-2022",
    "title": "3 Uhr Nachts",
    "category": "music",
    "year": 2022,
    "cue": "Song anhören und einordnen.",
    "answer": "Mehnersmoos, DJ Arschlochficker — 2022, 3 Uhr Nachts.",
    "hint": "Mehnersmoos, DJ Arschlochficker",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4zfQShUtVvysHKDDw08sMd"
    },
    "genres": [
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-bir-2023",
    "title": "Bir",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Mehnersmoos — 2023, Bir.",
    "hint": "Mehnersmoos",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/7JRFLBP9RgMvBjoZDLHWVV"
    },
    "genres": [
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-brennerautobahn-2022",
    "title": "Brennerautobahn",
    "category": "music",
    "year": 2022,
    "cue": "Song anhören und einordnen.",
    "answer": "Roy Bianco & Die Abbrunzati Boys — 2022, Brennerautobahn.",
    "hint": "Roy Bianco & Die Abbrunzati Boys",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/3dTTBt5Qtf6xzPOrBlG2tu"
    },
    "genres": [
      "schlagerparty",
      "poprock"
    ]
  },
  {
    "id": "song-hawaii-toast-song-2009",
    "title": "Hawaii Toast Song",
    "category": "music",
    "year": 2009,
    "cue": "Song anhören und einordnen.",
    "answer": "Alexander Marcus — 2009, Hawaii Toast Song.",
    "hint": "Alexander Marcus",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4Ka43W7pxLv41B2c5R1UAy"
    },
    "genres": [
      "schlagerparty",
      "poprock"
    ]
  },
  {
    "id": "song-familienfeier-2024",
    "title": "Familienfeier",
    "category": "music",
    "year": 2024,
    "cue": "Song anhören und einordnen.",
    "answer": "K.I.Z — 2024, Familienfeier.",
    "hint": "K.I.Z",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/3XEnnhbQRI8DlhvpXo9E2X"
    },
    "genres": [
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-velocita-2024",
    "title": "Velocità",
    "category": "music",
    "year": 2024,
    "cue": "Song anhören und einordnen.",
    "answer": "Roy Bianco & Die Abbrunzati Boys — 2024, Velocità.",
    "hint": "Roy Bianco & Die Abbrunzati Boys",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0tDIFv7I1dqYewsaGlzLUx"
    },
    "genres": [
      "schlagerparty",
      "poprock"
    ]
  },
  {
    "id": "song-bella-napoli-2022",
    "title": "Bella Napoli",
    "category": "music",
    "year": 2022,
    "cue": "Song anhören und einordnen.",
    "answer": "Roy Bianco & Die Abbrunzati Boys — 2022, Bella Napoli.",
    "hint": "Roy Bianco & Die Abbrunzati Boys",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1W14FFFgsM0m6DUt3Tf6NP"
    },
    "genres": [
      "schlagerparty",
      "poprock"
    ]
  },
  {
    "id": "song-in-the-end-2000",
    "title": "In the End",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Linkin Park — 2000, In the End.",
    "hint": "Linkin Park",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/60a0Rd6pjrkxjPbaKzXjfq"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-numb-2003",
    "title": "Numb",
    "category": "music",
    "year": 2003,
    "cue": "Song anhören und einordnen.",
    "answer": "Linkin Park — 2003, Numb.",
    "hint": "Linkin Park",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2nLtzopw4rPReszdYBJU6h"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-crawling-2000",
    "title": "Crawling",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Linkin Park — 2000, Crawling.",
    "hint": "Linkin Park",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/57BrRMwf9LrcmuOsyGilwr"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-the-emptiness-machine-2024",
    "title": "The Emptiness Machine",
    "category": "music",
    "year": 2024,
    "cue": "Song anhören und einordnen.",
    "answer": "Linkin Park — 2024, The Emptiness Machine.",
    "hint": "Linkin Park",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1EDPVGbyPKJPeGqATwXZvN"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-livin-on-a-prayer-1986",
    "title": "Livin' On A Prayer",
    "category": "music",
    "year": 1986,
    "cue": "Song anhören und einordnen.",
    "answer": "Bon Jovi — 1986, Livin' On A Prayer.",
    "hint": "Bon Jovi",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0ee1DiZF94NSqqpG0XHUzH"
    },
    "genres": [
      "metal",
      "poprock"
    ]
  },
  {
    "id": "song-always-1994",
    "title": "Always",
    "category": "music",
    "year": 1994,
    "cue": "Song anhören und einordnen.",
    "answer": "Bon Jovi — 1994, Always.",
    "hint": "Bon Jovi",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2RChe0r2cMoyOvuKobZy44"
    },
    "genres": [
      "metal",
      "poprock"
    ]
  },
  {
    "id": "song-enter-sandman-remastered-2021-2021",
    "title": "Enter Sandman - Remastered 2021",
    "category": "music",
    "year": 2021,
    "cue": "Song anhören und einordnen.",
    "answer": "Metallica — 2021, Enter Sandman - Remastered 2021.",
    "hint": "Metallica",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/3DwQ7AH3xGD9h65ezslm6q"
    },
    "genres": [
      "metal",
      "poprock"
    ]
  },
  {
    "id": "song-master-of-puppets-1986",
    "title": "Master Of Puppets",
    "category": "music",
    "year": 1986,
    "cue": "Song anhören und einordnen.",
    "answer": "Metallica — 1986, Master Of Puppets.",
    "hint": "Metallica",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2MuWTIM3b0YEAskbeeFE1i"
    },
    "genres": [
      "metal",
      "poprock"
    ]
  },
  {
    "id": "song-sad-but-true-remastered-2021-2021",
    "title": "Sad But True - Remastered 2021",
    "category": "music",
    "year": 2021,
    "cue": "Song anhören und einordnen.",
    "answer": "Metallica — 2021, Sad But True - Remastered 2021.",
    "hint": "Metallica",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5ltXoDLlI0rFZAmOXbAp5T"
    },
    "genres": [
      "metal",
      "poprock"
    ]
  },
  {
    "id": "song-seek-destroy-remastered-1983",
    "title": "Seek & Destroy - Remastered",
    "category": "music",
    "year": 1983,
    "cue": "Song anhören und einordnen.",
    "answer": "Metallica — 1983, Seek & Destroy - Remastered.",
    "hint": "Metallica",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/28WmNsclKsrVmdv3tDmoYU"
    },
    "genres": [
      "metal",
      "poprock"
    ]
  },
  {
    "id": "song-last-resort-2000",
    "title": "Last Resort",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Papa Roach — 2000, Last Resort.",
    "hint": "Papa Roach",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5W8YXBz9MTIDyrpYaCg2Ky"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-teenage-dirtbag-1999",
    "title": "Teenage Dirtbag",
    "category": "music",
    "year": 1999,
    "cue": "Song anhören und einordnen.",
    "answer": "Wheatus — 1999, Teenage Dirtbag.",
    "hint": "Wheatus",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/25FTMokYEbEWHEdss5JLZS"
    },
    "genres": [
      "poprock"
    ]
  },
  {
    "id": "song-paradise-city-1987",
    "title": "Paradise City",
    "category": "music",
    "year": 1987,
    "cue": "Song anhören und einordnen.",
    "answer": "Guns N' Roses — 1987, Paradise City.",
    "hint": "Guns N' Roses",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6eN1f9KNmiWEhpE2RhQqB5"
    },
    "genres": [
      "metal",
      "poprock"
    ]
  },
  {
    "id": "song-dont-stop-believin-2022-remaster-1981",
    "title": "Don't Stop Believin' (2022 Remaster)",
    "category": "music",
    "year": 1981,
    "cue": "Song anhören und einordnen.",
    "answer": "Journey — 1981, Don't Stop Believin' (2022 Remaster).",
    "hint": "Journey",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5RKQ5NdjSh2QzD4MaunT91"
    },
    "genres": [
      "poprock"
    ]
  },
  {
    "id": "song-take-a-look-around-2000",
    "title": "Take A Look Around",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Limp Bizkit — 2000, Take A Look Around.",
    "hint": "Limp Bizkit",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2avKuMN2QXkaG9vvHa2JLt"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-all-the-small-things-1999",
    "title": "All The Small Things",
    "category": "music",
    "year": 1999,
    "cue": "Song anhören und einordnen.",
    "answer": "blink-182 — 1999, All The Small Things.",
    "hint": "blink-182",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2m1hi0nfMR9vdGC8UcrnwU"
    },
    "genres": [
      "poprock"
    ]
  },
  {
    "id": "song-butterfly-1999",
    "title": "Butterfly",
    "category": "music",
    "year": 1999,
    "cue": "Song anhören und einordnen.",
    "answer": "Crazy Town — 1999, Butterfly.",
    "hint": "Crazy Town",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6GQ3WTaNHMFlVmN4burGat"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-californication-1999",
    "title": "Californication",
    "category": "music",
    "year": 1999,
    "cue": "Song anhören und einordnen.",
    "answer": "Red Hot Chili Peppers — 1999, Californication.",
    "hint": "Red Hot Chili Peppers",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/48UPSzbZjgc449aqz8bxox"
    },
    "genres": [
      "poprock"
    ]
  },
  {
    "id": "song-chop-suey-2001",
    "title": "Chop Suey!",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "System Of A Down — 2001, Chop Suey!.",
    "hint": "System Of A Down",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2DlHlPMa4M17kufBvI2lEN"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-the-bad-touch-1999",
    "title": "The Bad Touch",
    "category": "music",
    "year": 1999,
    "cue": "Song anhören und einordnen.",
    "answer": "Bloodhound Gang — 1999, The Bad Touch.",
    "hint": "Bloodhound Gang",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5EYdTPdJD74r9EVZBztqGG"
    },
    "genres": [
      "poprock"
    ]
  },
  {
    "id": "song-bring-me-to-life-2003",
    "title": "Bring Me To Life",
    "category": "music",
    "year": 2003,
    "cue": "Song anhören und einordnen.",
    "answer": "Evanescence — 2003, Bring Me To Life.",
    "hint": "Evanescence",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0COqiPhxzoWICwFCS4eZcp"
    },
    "genres": [
      "metal",
      "poprock"
    ]
  },
  {
    "id": "song-knockin-on-heavens-door-1991",
    "title": "Knockin' On Heaven's Door",
    "category": "music",
    "year": 1991,
    "cue": "Song anhören und einordnen.",
    "answer": "Guns N' Roses — 1991, Knockin' On Heaven's Door.",
    "hint": "Guns N' Roses",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4JiEyzf0Md7KEFFGWDDdCr"
    },
    "genres": [
      "metal",
      "poprock"
    ]
  },
  {
    "id": "song-byob-2005",
    "title": "B.Y.O.B.",
    "category": "music",
    "year": 2005,
    "cue": "Song anhören und einordnen.",
    "answer": "System Of A Down — 2005, B.Y.O.B..",
    "hint": "System Of A Down",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0EYOdF5FCkgOJJla8DI2Md"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-the-middle-2001",
    "title": "The Middle",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "Jimmy Eat World — 2001, The Middle.",
    "hint": "Jimmy Eat World",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6GG73Jik4jUlQCkKg9JuGO"
    },
    "genres": [
      "poprock"
    ]
  },
  {
    "id": "song-the-next-episode-1999",
    "title": "The Next Episode",
    "category": "music",
    "year": 1999,
    "cue": "Song anhören und einordnen.",
    "answer": "Dr. Dre, Snoop Dogg — 1999, The Next Episode.",
    "hint": "Dr. Dre, Snoop Dogg",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4LwU4Vp6od3Sb08CsP99GC"
    },
    "genres": [
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-reimemonster-feat-ferris-mc-1999",
    "title": "Reimemonster (feat. Ferris MC)",
    "category": "music",
    "year": 1999,
    "cue": "Song anhören und einordnen.",
    "answer": "Afrob, Ferris MC — 1999, Reimemonster (feat. Ferris MC).",
    "hint": "Afrob, Ferris MC",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0pgx8fWphTTM9Kv5KjWpXy"
    },
    "genres": [
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-weck-mich-auf-2001",
    "title": "Weck mich auf",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "Samy Deluxe — 2001, Weck mich auf.",
    "hint": "Samy Deluxe",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/47VRtROAdociHgtuVZNoBL"
    },
    "genres": [
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-bon-voyage-feat-nina-2000",
    "title": "Bon voyage (feat. Nina)",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Deichkind, Nina Tenge — 2000, Bon voyage (feat. Nina).",
    "hint": "Deichkind, Nina Tenge",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0ys1g8PTTs6ADeDp2h1xpd"
    },
    "genres": [
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-turlich-turlich-sicher-dicker-2000",
    "title": "Türlich, Türlich (Sicher, Dicker)",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Das Bo — 2000, Türlich, Türlich (Sicher, Dicker).",
    "hint": "Das Bo",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0zv3f19rNhmZhNmNA2xJsF"
    },
    "genres": [
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-oopsi-did-it-again-2000",
    "title": "Oops!...I Did It Again",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Britney Spears — 2000, Oops!...I Did It Again.",
    "hint": "Britney Spears",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6naxalmIoLFWR0siv8dnQQ"
    },
    "genres": [
      "poprock"
    ]
  },
  {
    "id": "song-thats-the-way-it-is-2019",
    "title": "That's the Way It Is",
    "category": "music",
    "year": 2019,
    "cue": "Song anhören und einordnen.",
    "answer": "Céline Dion — 2019, That's the Way It Is.",
    "hint": "Céline Dion",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5s4catxeZsaWFnOrvrXZHf"
    },
    "genres": [
      "poprock"
    ]
  },
  {
    "id": "song-believe-1998",
    "title": "Believe",
    "category": "music",
    "year": 1998,
    "cue": "Song anhören und einordnen.",
    "answer": "Cher — 1998, Believe.",
    "hint": "Cher",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2goLsvvODILDzeeiT4dAoR"
    },
    "genres": [
      "poprock"
    ]
  },
  {
    "id": "song-blau-bluht-der-enzian-2018",
    "title": "Blau blüht der Enzian",
    "category": "music",
    "year": 2018,
    "cue": "Song anhören und einordnen.",
    "answer": "Heino — 2018, Blau blüht der Enzian.",
    "hint": "Heino",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/7LHEQq3Xy7brogiqnXsT4L"
    },
    "genres": [
      "schlagerparty",
      "poprock"
    ]
  },
  {
    "id": "song-junge-2007",
    "title": "Junge",
    "category": "music",
    "year": 2007,
    "cue": "Song anhören und einordnen.",
    "answer": "Die Ärzte — 2007, Junge.",
    "hint": "Die Ärzte",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/10waMsh44ojvTwXAIy213n"
    },
    "genres": [
      "poprock"
    ]
  },
  {
    "id": "song-deine-schuld-2003",
    "title": "Deine Schuld",
    "category": "music",
    "year": 2003,
    "cue": "Song anhören und einordnen.",
    "answer": "Die Ärzte — 2003, Deine Schuld.",
    "hint": "Die Ärzte",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0oEp3d8au0a3Qp78F2QxtB"
    },
    "genres": [
      "poprock"
    ]
  },
  {
    "id": "song-tilidin-2019",
    "title": "Tilidin",
    "category": "music",
    "year": 2019,
    "cue": "Song anhören und einordnen.",
    "answer": "Capital Bra, Samra — 2019, Tilidin.",
    "hint": "Capital Bra, Samra",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0Dlcu2fgHklOnajVu2dUNU"
    },
    "genres": [
      "hiphop",
      "poprock"
    ]
  },
  {
    "id": "song-hypa-hypa-2021",
    "title": "Hypa Hypa",
    "category": "music",
    "year": 2021,
    "cue": "Song anhören und einordnen.",
    "answer": "Electric Callboy — 2021, Hypa Hypa.",
    "hint": "Electric Callboy",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2qOmcSjOQEDIJKosonn75a"
    },
    "genres": [
      "metal",
      "poprock"
    ]
  }
];
