// AUTO-GENERATED by scripts/sync-playlist.mjs
// Do not edit manually.
import { Card } from './types';

export const playlistCards: Card[] = [
  {
    "id": "song-3-uhr-nachts-2022",
    "title": "3 Uhr Nachts",
    "category": "music",
    "year": 2022,
    "cue": "Song anhören und einordnen.",
    "answer": "Mehnersmoos, DJ Arschlochficker — 2022, 3 Uhr Nachts.",
    "hint": "Mehnersmoos, DJ Arschlochficker",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4zfQShUtVvysHKDDw08sMd"
    }
  },
  {
    "id": "song-bir-2023",
    "title": "Bir",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Mehnersmoos — 2023, Bir.",
    "hint": "Mehnersmoos",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/7JRFLBP9RgMvBjoZDLHWVV"
    }
  },
  {
    "id": "song-brennerautobahn-2022",
    "title": "Brennerautobahn",
    "category": "music",
    "year": 2022,
    "cue": "Song anhören und einordnen.",
    "answer": "Roy Bianco & Die Abbrunzati Boys — 2022, Brennerautobahn.",
    "hint": "Roy Bianco & Die Abbrunzati Boys",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/3dTTBt5Qtf6xzPOrBlG2tu"
    }
  },
  {
    "id": "song-hawaii-toast-song-2009",
    "title": "Hawaii Toast Song",
    "category": "music",
    "year": 2009,
    "cue": "Song anhören und einordnen.",
    "answer": "Alexander Marcus — 2009, Hawaii Toast Song.",
    "hint": "Alexander Marcus",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4Ka43W7pxLv41B2c5R1UAy"
    }
  },
  {
    "id": "song-familienfeier-2024",
    "title": "Familienfeier",
    "category": "music",
    "year": 2024,
    "cue": "Song anhören und einordnen.",
    "answer": "K.I.Z — 2024, Familienfeier.",
    "hint": "K.I.Z",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/3XEnnhbQRI8DlhvpXo9E2X"
    }
  },
  {
    "id": "song-velocita-2024",
    "title": "Velocità",
    "category": "music",
    "year": 2024,
    "cue": "Song anhören und einordnen.",
    "answer": "Roy Bianco & Die Abbrunzati Boys — 2024, Velocità.",
    "hint": "Roy Bianco & Die Abbrunzati Boys",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0tDIFv7I1dqYewsaGlzLUx"
    }
  },
  {
    "id": "song-bella-napoli-2022",
    "title": "Bella Napoli",
    "category": "music",
    "year": 2022,
    "cue": "Song anhören und einordnen.",
    "answer": "Roy Bianco & Die Abbrunzati Boys — 2022, Bella Napoli.",
    "hint": "Roy Bianco & Die Abbrunzati Boys",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1W14FFFgsM0m6DUt3Tf6NP"
    }
  },
  {
    "id": "song-in-the-end-2000",
    "title": "In the End",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Linkin Park — 2000, In the End.",
    "hint": "Linkin Park",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/60a0Rd6pjrkxjPbaKzXjfq"
    }
  },
  {
    "id": "song-numb-2003",
    "title": "Numb",
    "category": "music",
    "year": 2003,
    "cue": "Song anhören und einordnen.",
    "answer": "Linkin Park — 2003, Numb.",
    "hint": "Linkin Park",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2nLtzopw4rPReszdYBJU6h"
    }
  },
  {
    "id": "song-crawling-2000",
    "title": "Crawling",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Linkin Park — 2000, Crawling.",
    "hint": "Linkin Park",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/57BrRMwf9LrcmuOsyGilwr"
    }
  },
  {
    "id": "song-the-emptiness-machine-2024",
    "title": "The Emptiness Machine",
    "category": "music",
    "year": 2024,
    "cue": "Song anhören und einordnen.",
    "answer": "Linkin Park — 2024, The Emptiness Machine.",
    "hint": "Linkin Park",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1EDPVGbyPKJPeGqATwXZvN"
    }
  },
  {
    "id": "song-livin-on-a-prayer-1986",
    "title": "Livin' On A Prayer",
    "category": "music",
    "year": 1986,
    "cue": "Song anhören und einordnen.",
    "answer": "Bon Jovi — 1986, Livin' On A Prayer.",
    "hint": "Bon Jovi",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0ee1DiZF94NSqqpG0XHUzH"
    }
  },
  {
    "id": "song-always-1994",
    "title": "Always",
    "category": "music",
    "year": 1994,
    "cue": "Song anhören und einordnen.",
    "answer": "Bon Jovi — 1994, Always.",
    "hint": "Bon Jovi",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2RChe0r2cMoyOvuKobZy44"
    }
  },
  {
    "id": "song-enter-sandman-remastered-2021-2021",
    "title": "Enter Sandman - Remastered 2021",
    "category": "music",
    "year": 2021,
    "cue": "Song anhören und einordnen.",
    "answer": "Metallica — 2021, Enter Sandman - Remastered 2021.",
    "hint": "Metallica",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/3DwQ7AH3xGD9h65ezslm6q"
    }
  },
  {
    "id": "song-master-of-puppets-1986",
    "title": "Master Of Puppets",
    "category": "music",
    "year": 1986,
    "cue": "Song anhören und einordnen.",
    "answer": "Metallica — 1986, Master Of Puppets.",
    "hint": "Metallica",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2MuWTIM3b0YEAskbeeFE1i"
    }
  },
  {
    "id": "song-sad-but-true-remastered-2021-2021",
    "title": "Sad But True - Remastered 2021",
    "category": "music",
    "year": 2021,
    "cue": "Song anhören und einordnen.",
    "answer": "Metallica — 2021, Sad But True - Remastered 2021.",
    "hint": "Metallica",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5ltXoDLlI0rFZAmOXbAp5T"
    }
  },
  {
    "id": "song-seek-destroy-remastered-1983",
    "title": "Seek & Destroy - Remastered",
    "category": "music",
    "year": 1983,
    "cue": "Song anhören und einordnen.",
    "answer": "Metallica — 1983, Seek & Destroy - Remastered.",
    "hint": "Metallica",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/28WmNsclKsrVmdv3tDmoYU"
    }
  }
];
