// AUTO-GENERATED by scripts/sync-playlist.mjs
// Do not edit manually.
import { Card } from './types';

export type PlaylistInfo = { id: string; name: string };
export const playlistInfo: PlaylistInfo[] = [
  {
    "id": "1K766ohE2LA7b7ghtTm7mP",
    "name": "Felx-2000er"
  }
];

export const playlistCards: Card[] = [
  {
    "id": "song-incomplete-2005",
    "title": "Incomplete",
    "category": "music",
    "year": 2005,
    "cue": "Song anhören und einordnen.",
    "answer": "Backstreet Boys — 2005, Incomplete.",
    "hint": "Backstreet Boys",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/0CnD7Hiw6pae6rLsZw5q5W"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-just-like-a-pill-2001",
    "title": "Just Like a Pill",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "P!nk — 2001, Just Like a Pill.",
    "hint": "P!nk",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/1BpV8IGf4XsRRJf4Xuui9q"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-teenage-dirtbag-1999",
    "title": "Teenage Dirtbag",
    "category": "music",
    "year": 1999,
    "cue": "Song anhören und einordnen.",
    "answer": "Wheatus — 1999, Teenage Dirtbag.",
    "hint": "Wheatus",
    "difficulty": "schwer",
    "sources": {
      "spotify": "https://open.spotify.com/track/25FTMokYEbEWHEdss5JLZS"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-murder-on-the-dancefloor-2007",
    "title": "Murder On The Dancefloor",
    "category": "music",
    "year": 2007,
    "cue": "Song anhören und einordnen.",
    "answer": "Sophie Ellis-Bextor — 2007, Murder On The Dancefloor.",
    "hint": "Sophie Ellis-Bextor",
    "difficulty": "schwer",
    "sources": {
      "spotify": "https://open.spotify.com/track/3yjjFp94TOENrJJgvmxAoE"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-unwritten-2004",
    "title": "Unwritten",
    "category": "music",
    "year": 2004,
    "cue": "Song anhören und einordnen.",
    "answer": "Natasha Bedingfield — 2004, Unwritten.",
    "hint": "Natasha Bedingfield",
    "difficulty": "schwer",
    "sources": {
      "spotify": "https://open.spotify.com/track/3U5JVgI2x4rDyHGObzJfNf"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-bye-bye-bye-2000",
    "title": "Bye Bye Bye",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "*NSYNC — 2000, Bye Bye Bye.",
    "hint": "*NSYNC",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/4r8lRYnoOGdEi6YyI5OC1o"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-wake-me-up-when-september-ends-2004",
    "title": "Wake Me up When September Ends",
    "category": "music",
    "year": 2004,
    "cue": "Song anhören und einordnen.",
    "answer": "Green Day — 2004, Wake Me up When September Ends.",
    "hint": "Green Day",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/3ZffCQKLFLUvYM59XKLbVm"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-im-with-you-2002",
    "title": "I'm with You",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "Avril Lavigne — 2002, I'm with You.",
    "hint": "Avril Lavigne",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/1jlG3KJ3gdYmhfuySFfpO1"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-bad-day-2005",
    "title": "Bad Day",
    "category": "music",
    "year": 2005,
    "cue": "Song anhören und einordnen.",
    "answer": "Daniel Powter — 2005, Bad Day.",
    "hint": "Daniel Powter",
    "difficulty": "schwer",
    "sources": {
      "spotify": "https://open.spotify.com/track/0mUyMawtxj1CJ76kn9gIZK"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-hero-2001",
    "title": "Hero",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "Enrique Iglesias — 2001, Hero.",
    "hint": "Enrique Iglesias",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/1PAgmT6YqGhd6zT9kN9gIo"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-feel-2002",
    "title": "Feel",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "Robbie Williams — 2002, Feel.",
    "hint": "Robbie Williams",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2Ms33RTRCT6gArrpcrPxmo"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-chicago-remastered-2014-2006",
    "title": "Chicago - Remastered 2014",
    "category": "music",
    "year": 2006,
    "cue": "Song anhören und einordnen.",
    "answer": "Clueso — 2006, Chicago - Remastered 2014.",
    "hint": "Clueso",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5oPSBJ5WQNwRL9ICtohYfo"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-goodbye-my-lover-2005",
    "title": "Goodbye My Lover",
    "category": "music",
    "year": 2005,
    "cue": "Song anhören und einordnen.",
    "answer": "James Blunt — 2005, Goodbye My Lover.",
    "hint": "James Blunt",
    "difficulty": "schwer",
    "sources": {
      "spotify": "https://open.spotify.com/track/6gxycjJNMgmAyfzUXBN80P"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-sk8er-boi-2002",
    "title": "Sk8er Boi",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "Avril Lavigne — 2002, Sk8er Boi.",
    "hint": "Avril Lavigne",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/00Mb3DuaIH1kjrwOku9CGU"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-du-tragst-keine-liebe-in-dir-1999",
    "title": "Du trägst keine Liebe in dir",
    "category": "music",
    "year": 1999,
    "cue": "Song anhören und einordnen.",
    "answer": "Echt — 1999, Du trägst keine Liebe in dir.",
    "hint": "Echt",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/21aT5lIYHjyBIFrXNbNY5U"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-big-yellow-taxi-2002",
    "title": "Big Yellow Taxi",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "Counting Crows, Vanessa Carlton — 2002, Big Yellow Taxi.",
    "hint": "Counting Crows, Vanessa Carlton",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5fztgDIt1Nq32VHJrAHq0Y"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-boulevard-of-broken-dreams-2004",
    "title": "Boulevard of Broken Dreams",
    "category": "music",
    "year": 2004,
    "cue": "Song anhören und einordnen.",
    "answer": "Green Day — 2004, Boulevard of Broken Dreams.",
    "hint": "Green Day",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/1hwJKpe0BPUsq6UUrwBWTw"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-drops-of-jupiter-tell-me-2001",
    "title": "Drops of Jupiter (Tell Me)",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "Train — 2001, Drops of Jupiter (Tell Me).",
    "hint": "Train",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2hKdd3qO7cWr2Jo0Bcs0MA"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-complicated-2002",
    "title": "Complicated",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "Avril Lavigne — 2002, Complicated.",
    "hint": "Avril Lavigne",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/5xEM5hIgJ1jjgcEBfpkt2F"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-mr-brightside-2004",
    "title": "Mr. Brightside",
    "category": "music",
    "year": 2004,
    "cue": "Song anhören und einordnen.",
    "answer": "The Killers — 2004, Mr. Brightside.",
    "hint": "The Killers",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/003vvx7Niy0yvhvHt4a68B"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-chasing-cars-2006",
    "title": "Chasing Cars",
    "category": "music",
    "year": 2006,
    "cue": "Song anhören und einordnen.",
    "answer": "Snow Patrol — 2006, Chasing Cars.",
    "hint": "Snow Patrol",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0rpIH5otu7ykvZPdcQuRPh"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-butterfly-1999",
    "title": "Butterfly",
    "category": "music",
    "year": 1999,
    "cue": "Song anhören und einordnen.",
    "answer": "Crazy Town — 1999, Butterfly.",
    "hint": "Crazy Town",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6GQ3WTaNHMFlVmN4burGat"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-im-like-a-bird-2000",
    "title": "I'm Like A Bird",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Nelly Furtado — 2000, I'm Like A Bird.",
    "hint": "Nelly Furtado",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/2aGw77pZqli064JiPuXYRi"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-somewhere-only-we-know-2004",
    "title": "Somewhere Only We Know",
    "category": "music",
    "year": 2004,
    "cue": "Song anhören und einordnen.",
    "answer": "Keane — 2004, Somewhere Only We Know.",
    "hint": "Keane",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1SKPmfSYaPsETbRHaiA18G"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-in-the-shadows-2003",
    "title": "In the Shadows",
    "category": "music",
    "year": 2003,
    "cue": "Song anhören und einordnen.",
    "answer": "The Rasmus — 2003, In the Shadows.",
    "hint": "The Rasmus",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1fr92Vupmcs2vgLMFVQ7rd"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-never-be-the-same-again-1999",
    "title": "Never Be The Same Again",
    "category": "music",
    "year": 1999,
    "cue": "Song anhören und einordnen.",
    "answer": "Melanie C, Lisa \"Left Eye\" Lopes — 1999, Never Be The Same Again.",
    "hint": "Melanie C, Lisa \"Left Eye\" Lopes",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/79EAVfOpzgfHx3IE2BVFQv"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-weinst-du-1999",
    "title": "Weinst du",
    "category": "music",
    "year": 1999,
    "cue": "Song anhören und einordnen.",
    "answer": "Echt — 1999, Weinst du.",
    "hint": "Echt",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2RjnnOuAvosOSAZhZQ50kO"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-somethin-stupid-2001",
    "title": "Somethin' Stupid",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "Robbie Williams, Nicole Kidman — 2001, Somethin' Stupid.",
    "hint": "Robbie Williams, Nicole Kidman",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4kSKacywUJHdhyst4PL6pl"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-cant-stop-2002",
    "title": "Can't Stop",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "Red Hot Chili Peppers — 2002, Can't Stop.",
    "hint": "Red Hot Chili Peppers",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/3ZOEytgrvLwQaqXreDs2Jx"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-its-my-life-2000",
    "title": "It's My Life",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Bon Jovi — 2000, It's My Life.",
    "hint": "Bon Jovi",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0v1XpBHnsbkCn7iJ9Ucr1l"
    },
    "genres": [
      "metal",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-are-you-gonna-be-my-girl-2003",
    "title": "Are You Gonna Be My Girl",
    "category": "music",
    "year": 2003,
    "cue": "Song anhören und einordnen.",
    "answer": "Jet — 2003, Are You Gonna Be My Girl.",
    "hint": "Jet",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/72zZfHPYx43shcP3eKkYi5"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-who-let-the-dogs-out-2000",
    "title": "Who Let The Dogs Out",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Baha Men — 2000, Who Let The Dogs Out.",
    "hint": "Baha Men",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1H5tvpoApNDxvxDexoaAUo"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-white-flag-2003",
    "title": "White Flag",
    "category": "music",
    "year": 2003,
    "cue": "Song anhören und einordnen.",
    "answer": "Dido — 2003, White Flag.",
    "hint": "Dido",
    "difficulty": "schwer",
    "sources": {
      "spotify": "https://open.spotify.com/track/6si71supnBUhddjR2FJc2L"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-fireflies-2009",
    "title": "Fireflies",
    "category": "music",
    "year": 2009,
    "cue": "Song anhören und einordnen.",
    "answer": "Owl City — 2009, Fireflies.",
    "hint": "Owl City",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/3DamFFqW32WihKkTVlwTYQ"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-behind-these-hazel-eyes-2004",
    "title": "Behind These Hazel Eyes",
    "category": "music",
    "year": 2004,
    "cue": "Song anhören und einordnen.",
    "answer": "Kelly Clarkson — 2004, Behind These Hazel Eyes.",
    "hint": "Kelly Clarkson",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/0AKAxdNkwq9ZxRdW1DN9zW"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-whole-again-2003",
    "title": "Whole Again",
    "category": "music",
    "year": 2003,
    "cue": "Song anhören und einordnen.",
    "answer": "Atomic Kitten — 2003, Whole Again.",
    "hint": "Atomic Kitten",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4WGTwyHPMvB3HWiEO9R0wb"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-dreamer-2001",
    "title": "Dreamer",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "Ozzy Osbourne — 2001, Dreamer.",
    "hint": "Ozzy Osbourne",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/78PKCefXwDLbl4FVO1Pjzh"
    },
    "genres": [
      "metal",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-cant-fight-the-moonlight-2001",
    "title": "Can't Fight The Moonlight",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "LeAnn Rimes — 2001, Can't Fight The Moonlight.",
    "hint": "LeAnn Rimes",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2AogRMqARWyUP7VQ3gmSoY"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-this-love-2002",
    "title": "This Love",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "Maroon 5 — 2002, This Love.",
    "hint": "Maroon 5",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/6ECp64rv50XVz93WvxXMGF"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-dragostea-din-tei-2004",
    "title": "Dragostea din tei",
    "category": "music",
    "year": 2004,
    "cue": "Song anhören und einordnen.",
    "answer": "O-Zone — 2004, Dragostea din tei.",
    "hint": "O-Zone",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/52Zr0sinhWTCRrQhRRY4EP"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-a-thousand-miles-2002",
    "title": "A Thousand Miles",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "Vanessa Carlton — 2002, A Thousand Miles.",
    "hint": "Vanessa Carlton",
    "difficulty": "schwer",
    "sources": {
      "spotify": "https://open.spotify.com/track/4w1lzcaoZ1IC2K5TwjalRP"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-numb-2003",
    "title": "Numb",
    "category": "music",
    "year": 2003,
    "cue": "Song anhören und einordnen.",
    "answer": "Linkin Park — 2003, Numb.",
    "hint": "Linkin Park",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/2nLtzopw4rPReszdYBJU6h"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-der-weg-remastered-2016-2002",
    "title": "Der Weg - Remastered 2016",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "Herbert Grönemeyer — 2002, Der Weg - Remastered 2016.",
    "hint": "Herbert Grönemeyer",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/7py0pONdy9D0DxNnT3elik"
    },
    "genres": [
      "schlagerparty",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-pure-shores-2000",
    "title": "Pure Shores",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "All Saints — 2000, Pure Shores.",
    "hint": "All Saints",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6ZLGthToczpvnL5Eoy6yrY"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-just-more-2002",
    "title": "Just More",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "Wonderwall — 2002, Just More.",
    "hint": "Wonderwall",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1AR0pzjw2WvAHlcst59nwT"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-fix-you-2005",
    "title": "Fix You",
    "category": "music",
    "year": 2005,
    "cue": "Song anhören und einordnen.",
    "answer": "Coldplay — 2005, Fix You.",
    "hint": "Coldplay",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/7LVHVU3tWfcxj5aiPFEW4Q"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-underneath-your-clothes-2001",
    "title": "Underneath Your Clothes",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "Shakira — 2001, Underneath Your Clothes.",
    "hint": "Shakira",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/15f8Cv8RXUlOOCIf2oaceN"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-mundian-to-bach-ke-2003",
    "title": "Mundian To Bach Ke",
    "category": "music",
    "year": 2003,
    "cue": "Song anhören und einordnen.",
    "answer": "Panjabi MC — 2003, Mundian To Bach Ke.",
    "hint": "Panjabi MC",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2LxAeJ9KUj1GRS9oeHgQ3i"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-by-the-way-2002",
    "title": "By the Way",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "Red Hot Chili Peppers — 2002, By the Way.",
    "hint": "Red Hot Chili Peppers",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/1f2V8U1BiWaC9aJWmpOARe"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-how-you-remind-me-2001",
    "title": "How You Remind Me",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "Nickelback — 2001, How You Remind Me.",
    "hint": "Nickelback",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/0gmbgwZ8iqyMPmXefof8Yf"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-keinen-zentimeter-remastered-2014-2008",
    "title": "Keinen Zentimeter - Remastered 2014",
    "category": "music",
    "year": 2008,
    "cue": "Song anhören und einordnen.",
    "answer": "Clueso — 2008, Keinen Zentimeter - Remastered 2014.",
    "hint": "Clueso",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5v64DycnnkiEtJXiuObYhO"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-how-to-save-a-life-2005",
    "title": "How to Save a Life",
    "category": "music",
    "year": 2005,
    "cue": "Song anhören und einordnen.",
    "answer": "The Fray — 2005, How to Save a Life.",
    "hint": "The Fray",
    "difficulty": "schwer",
    "sources": {
      "spotify": "https://open.spotify.com/track/5fVZC9GiM4e8vu99W0Xf6J"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-in-the-end-2000",
    "title": "In the End",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Linkin Park — 2000, In the End.",
    "hint": "Linkin Park",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/60a0Rd6pjrkxjPbaKzXjfq"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-lied-1-stuck-vom-himmel-2007",
    "title": "Lied 1 - Stück vom Himmel",
    "category": "music",
    "year": 2007,
    "cue": "Song anhören und einordnen.",
    "answer": "Herbert Grönemeyer — 2007, Lied 1 - Stück vom Himmel.",
    "hint": "Herbert Grönemeyer",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5MDgIJMfN3VsxVBLjpDPIP"
    },
    "genres": [
      "schlagerparty",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-durch-den-monsun-radio-mix-2005",
    "title": "Durch den Monsun - Radio Mix",
    "category": "music",
    "year": 2005,
    "cue": "Song anhören und einordnen.",
    "answer": "Tokio Hotel — 2005, Durch den Monsun - Radio Mix.",
    "hint": "Tokio Hotel",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5OiC3eltQO7gXvOZMbrTn3"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-galvanize-2005",
    "title": "Galvanize",
    "category": "music",
    "year": 2005,
    "cue": "Song anhören und einordnen.",
    "answer": "The Chemical Brothers — 2005, Galvanize.",
    "hint": "The Chemical Brothers",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4bz7uB4edifWKJXSDxwHcs"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-hey-there-delilah-2005",
    "title": "Hey There Delilah",
    "category": "music",
    "year": 2005,
    "cue": "Song anhören und einordnen.",
    "answer": "Plain White T's — 2005, Hey There Delilah.",
    "hint": "Plain White T's",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4RCWB3V8V0dignt99LZ8vH"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-freunde-bleiben-2005",
    "title": "Freunde bleiben",
    "category": "music",
    "year": 2005,
    "cue": "Song anhören und einordnen.",
    "answer": "Revolverheld — 2005, Freunde bleiben.",
    "hint": "Revolverheld",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4bzmkrtJDog1RpvWAibK2n"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-who-knew-edit-2006",
    "title": "Who Knew - Edit",
    "category": "music",
    "year": 2006,
    "cue": "Song anhören und einordnen.",
    "answer": "P!nk — 2006, Who Knew - Edit.",
    "hint": "P!nk",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/2hns6Dv29Yrg68AVTJiAyA"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-beautiful-2002",
    "title": "Beautiful",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "Christina Aguilera — 2002, Beautiful.",
    "hint": "Christina Aguilera",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/3TCauNPqFiniaYHBvEVoHG"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-nur-ein-wort-2005",
    "title": "Nur ein Wort",
    "category": "music",
    "year": 2005,
    "cue": "Song anhören und einordnen.",
    "answer": "Wir sind Helden — 2005, Nur ein Wort.",
    "hint": "Wir sind Helden",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4hYinIaRxdaoEFSQni6K6I"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-everywhere-2001",
    "title": "Everywhere",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "Michelle Branch — 2001, Everywhere.",
    "hint": "Michelle Branch",
    "difficulty": "schwer",
    "sources": {
      "spotify": "https://open.spotify.com/track/1u0l8zWpQeMYStFkc2mLD7"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-kids-2007",
    "title": "Kids",
    "category": "music",
    "year": 2007,
    "cue": "Song anhören und einordnen.",
    "answer": "MGMT — 2007, Kids.",
    "hint": "MGMT",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1jJci4qxiYcOHhQR247rEU"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-here-without-you-2002",
    "title": "Here Without You",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "3 Doors Down — 2002, Here Without You.",
    "hint": "3 Doors Down",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/3NLrRZoMF0Lx6zTlYqeIo4"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-all-the-things-she-said-2002",
    "title": "All The Things She Said",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "t.A.T.u. — 2002, All The Things She Said.",
    "hint": "t.A.T.u.",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4bJygwUKrRgq1stlNXcgMg"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-aurelie-2003",
    "title": "Aurélie",
    "category": "music",
    "year": 2003,
    "cue": "Song anhören und einordnen.",
    "answer": "Wir sind Helden — 2003, Aurélie.",
    "hint": "Wir sind Helden",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6vugYRjEYHJ3nsGP5kScpf"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-she-will-be-loved-radio-mix-2002",
    "title": "She Will Be Loved - Radio Mix",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "Maroon 5 — 2002, She Will Be Loved - Radio Mix.",
    "hint": "Maroon 5",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/4llK75pXNWZz6KAho2Gp16"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-relax-take-it-easy-2007",
    "title": "Relax, Take It Easy",
    "category": "music",
    "year": 2007,
    "cue": "Song anhören und einordnen.",
    "answer": "MIKA — 2007, Relax, Take It Easy.",
    "hint": "MIKA",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1kmhdq0RfZFdfSLaTsiTVi"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-the-scientist-2002",
    "title": "The Scientist",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "Coldplay — 2002, The Scientist.",
    "hint": "Coldplay",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/75JFxkI2RXiU7L9VXzMkle"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-soulmate-2007",
    "title": "Soulmate",
    "category": "music",
    "year": 2007,
    "cue": "Song anhören und einordnen.",
    "answer": "Natasha Bedingfield — 2007, Soulmate.",
    "hint": "Natasha Bedingfield",
    "difficulty": "schwer",
    "sources": {
      "spotify": "https://open.spotify.com/track/3DuHOCe1dbf3XKF8uoc5oM"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-only-time-2000",
    "title": "Only Time",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Enya — 2000, Only Time.",
    "hint": "Enya",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6FLwmdmW77N1Pxb1aWsZmO"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-dancing-in-the-moonlight-2000",
    "title": "Dancing in the Moonlight",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Toploader — 2000, Dancing in the Moonlight.",
    "hint": "Toploader",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0w07a1vsKahQMM0RnPXHVT"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-hot-n-cold-2008",
    "title": "Hot N Cold",
    "category": "music",
    "year": 2008,
    "cue": "Song anhören und einordnen.",
    "answer": "Katy Perry — 2008, Hot N Cold.",
    "hint": "Katy Perry",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/0iGckQFyv6svOfAbAY9aWJ"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-girl-4-a-day-2002",
    "title": "Girl 4 A Day",
    "category": "music",
    "year": 2002,
    "cue": "Song anhören und einordnen.",
    "answer": "band ohne namen, Milka — 2002, Girl 4 A Day.",
    "hint": "band ohne namen, Milka",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4EfIj3ryeMpmZNJq4xbTQf"
    },
    "genres": [
      "poprock",
      "hiphop"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-where-is-the-love-2003",
    "title": "Where Is The Love?",
    "category": "music",
    "year": 2003,
    "cue": "Song anhören und einordnen.",
    "answer": "Black Eyed Peas — 2003, Where Is The Love?.",
    "hint": "Black Eyed Peas",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/0xmjwnQ3FNE6HuWCt2nHdZ"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-thank-you-1999",
    "title": "Thank You",
    "category": "music",
    "year": 1999,
    "cue": "Song anhören und einordnen.",
    "answer": "Dido — 1999, Thank You.",
    "hint": "Dido",
    "difficulty": "schwer",
    "sources": {
      "spotify": "https://open.spotify.com/track/3yUcJwYu7fXAfqMj9krY6l"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-leave-get-out-2004",
    "title": "Leave (Get Out)",
    "category": "music",
    "year": 2004,
    "cue": "Song anhören und einordnen.",
    "answer": "JoJo — 2004, Leave (Get Out).",
    "hint": "JoJo",
    "difficulty": "schwer",
    "sources": {
      "spotify": "https://open.spotify.com/track/1KvoW6HPuW7Mu9i55XaibE"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-since-u-been-gone-2004",
    "title": "Since U Been Gone",
    "category": "music",
    "year": 2004,
    "cue": "Song anhören und einordnen.",
    "answer": "Kelly Clarkson — 2004, Since U Been Gone.",
    "hint": "Kelly Clarkson",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/6JY1IdkZGeIcPegKxjSKeb"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-perfekte-welle-2004",
    "title": "Perfekte Welle",
    "category": "music",
    "year": 2004,
    "cue": "Song anhören und einordnen.",
    "answer": "Juli — 2004, Perfekte Welle.",
    "hint": "Juli",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2LV5joNDrsyuXEh4FBARVK"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-valerie-feat-amy-winehouse-version-revisited-2007",
    "title": "Valerie (feat. Amy Winehouse) - Version Revisited",
    "category": "music",
    "year": 2007,
    "cue": "Song anhören und einordnen.",
    "answer": "Mark Ronson, Amy Winehouse — 2007, Valerie (feat. Amy Winehouse) - Version Revisited.",
    "hint": "Mark Ronson, Amy Winehouse",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6kopmMZiyLmw7h66uXcXR7"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-all-rise-2004",
    "title": "All Rise",
    "category": "music",
    "year": 2004,
    "cue": "Song anhören und einordnen.",
    "answer": "Blue — 2004, All Rise.",
    "hint": "Blue",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0OJtYfqiz0Xn53o2TnySQC"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-the-tide-is-high-radio-mix-2003",
    "title": "The Tide Is High - Radio Mix",
    "category": "music",
    "year": 2003,
    "cue": "Song anhören und einordnen.",
    "answer": "Atomic Kitten — 2003, The Tide Is High - Radio Mix.",
    "hint": "Atomic Kitten",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5WuVWOngcRkMOx9RRLCvui"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-symphonie-2004",
    "title": "Symphonie",
    "category": "music",
    "year": 2004,
    "cue": "Song anhören und einordnen.",
    "answer": "Silbermond — 2004, Symphonie.",
    "hint": "Silbermond",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/7mOD9NFyZhC8PtW4joWDWT"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-lasse-redn-2007",
    "title": "Lasse redn",
    "category": "music",
    "year": 2007,
    "cue": "Song anhören und einordnen.",
    "answer": "Die Ärzte — 2007, Lasse redn.",
    "hint": "Die Ärzte",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6vJ4egoPoiPKUyohVOfVHC"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-get-the-party-started-2001",
    "title": "Get the Party Started",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "P!nk — 2001, Get the Party Started.",
    "hint": "P!nk",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/02jcEwywffn3Tsb48fXmlW"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-she-hates-me-2001",
    "title": "She Hates Me",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "Puddle Of Mudd — 2001, She Hates Me.",
    "hint": "Puddle Of Mudd",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/16DhvbuyvJob4Q9GHNYu2n"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-whenever-wherever-2001",
    "title": "Whenever, Wherever",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "Shakira — 2001, Whenever, Wherever.",
    "hint": "Shakira",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/2lnzGkdtDj5mtlcOW2yRtG"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-im-outta-love-radio-edit-1999",
    "title": "I'm Outta Love - Radio Edit",
    "category": "music",
    "year": 1999,
    "cue": "Song anhören und einordnen.",
    "answer": "Anastacia — 1999, I'm Outta Love - Radio Edit.",
    "hint": "Anastacia",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/583xVl0Sbj93uU4ceixgU8"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-suddenly-i-see-2005",
    "title": "Suddenly I See",
    "category": "music",
    "year": 2005,
    "cue": "Song anhören und einordnen.",
    "answer": "KT Tunstall — 2005, Suddenly I See.",
    "hint": "KT Tunstall",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5p9XWUdvbUzmPCukOmwoU3"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-viva-la-vida-2008",
    "title": "Viva La Vida",
    "category": "music",
    "year": 2008,
    "cue": "Song anhören und einordnen.",
    "answer": "Coldplay — 2008, Viva La Vida.",
    "hint": "Coldplay",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/5S6pYZD8WH3OQapDHTDM9M"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-mit-dir-chilln-2005",
    "title": "Mit dir chilln",
    "category": "music",
    "year": 2005,
    "cue": "Song anhören und einordnen.",
    "answer": "Revolverheld — 2005, Mit dir chilln.",
    "hint": "Revolverheld",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/7bjM0YAWS0goSo8pSokkvA"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-overload-2000",
    "title": "Overload",
    "category": "music",
    "year": 2000,
    "cue": "Song anhören und einordnen.",
    "answer": "Sugababes — 2000, Overload.",
    "hint": "Sugababes",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/7orBBkQgdmanhPCD0FyHHZ"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-absolutely-everybody-2004",
    "title": "Absolutely Everybody",
    "category": "music",
    "year": 2004,
    "cue": "Song anhören und einordnen.",
    "answer": "Vanessa Amorosi — 2004, Absolutely Everybody.",
    "hint": "Vanessa Amorosi",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/283898Lgbl6LidapOraXiN"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-make-you-feel-my-love-2008",
    "title": "Make You Feel My Love",
    "category": "music",
    "year": 2008,
    "cue": "Song anhören und einordnen.",
    "answer": "Adele — 2008, Make You Feel My Love.",
    "hint": "Adele",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/273QnyCvJB65rScHJ1nPZb"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-junge-2007",
    "title": "Junge",
    "category": "music",
    "year": 2007,
    "cue": "Song anhören und einordnen.",
    "answer": "Die Ärzte — 2007, Junge.",
    "hint": "Die Ärzte",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/10waMsh44ojvTwXAIy213n"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-haus-am-see-2008",
    "title": "Haus am See",
    "category": "music",
    "year": 2008,
    "cue": "Song anhören und einordnen.",
    "answer": "Peter Fox — 2008, Haus am See.",
    "hint": "Peter Fox",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/7A4KdLy1DXOOC5fhIdDuHz"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-apologize-2007",
    "title": "Apologize",
    "category": "music",
    "year": 2007,
    "cue": "Song anhören und einordnen.",
    "answer": "Timbaland, OneRepublic — 2007, Apologize.",
    "hint": "Timbaland, OneRepublic",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6ucR4KfvsBFWCMVFDvyKKl"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-dont-stop-movin-2001",
    "title": "Don't Stop Movin'",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "S Club — 2001, Don't Stop Movin'.",
    "hint": "S Club",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4dzreTCcGVgeF1vCcd22AC"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-regen-und-meer-2004",
    "title": "Regen und Meer",
    "category": "music",
    "year": 2004,
    "cue": "Song anhören und einordnen.",
    "answer": "Juli — 2004, Regen und Meer.",
    "hint": "Juli",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6fIGXxeU3C230sAm07WJxY"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-clint-eastwood-2001",
    "title": "Clint Eastwood",
    "category": "music",
    "year": 2001,
    "cue": "Song anhören und einordnen.",
    "answer": "Gorillaz, Del The Funky Homosapien — 2001, Clint Eastwood.",
    "hint": "Gorillaz, Del The Funky Homosapien",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1RKUoGiLEbcXN4GY4spQDx"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-in-the-end-2023",
    "title": "In the End",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Linkin Park — 2023, In the End.",
    "hint": "Linkin Park",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/6BXLec9ha9VDjCki0hUz2M"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-temperature-2023",
    "title": "Temperature",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Sean Paul — 2023, Temperature.",
    "hint": "Sean Paul",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/3aaRRjtfKcEOZ0Prn80OhB"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-lasciala-andare-2023",
    "title": "Lasciala andare",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Irene Grandi — 2023, Lasciala andare.",
    "hint": "Irene Grandi",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/3spBSmnzy7eKOAvNIKStf4"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-black-and-yellow-2023",
    "title": "Black and Yellow",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Wiz Khalifa — 2023, Black and Yellow.",
    "hint": "Wiz Khalifa",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5xvmB1OoJHXz8LsZPMhZ3G"
    },
    "genres": [
      "hiphop",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-numb-2023",
    "title": "Numb",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Linkin Park — 2023, Numb.",
    "hint": "Linkin Park",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/0Z5MCE3Sp2mRwlcBgWglqV"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-american-idiot-2023",
    "title": "American Idiot",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Green Day — 2023, American Idiot.",
    "hint": "Green Day",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/6ELGTnvFyupaMLtxSYrrCG"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-remember-the-name-2023",
    "title": "Remember the Name",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Fort Minor, Styles Of Beyond — 2023, Remember the Name.",
    "hint": "Fort Minor, Styles Of Beyond",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/22OsteZ4vFCDUY5KdtvVzR"
    },
    "genres": [
      "hiphop",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-jar-of-hearts-2023",
    "title": "Jar of Hearts",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Christina Perri — 2023, Jar of Hearts.",
    "hint": "Christina Perri",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1heLEv7PekeuSueH9r1LaD"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-bambolina-e-barracuda-2023",
    "title": "Bambolina e barracuda",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Ligabue — 2023, Bambolina e barracuda.",
    "hint": "Ligabue",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6KMUWQdSdgWbUt8QGEaRIN"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-airplanes-2023",
    "title": "Airplanes",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "B.o.B, Hayley Williams — 2023, Airplanes.",
    "hint": "B.o.B, Hayley Williams",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/72fQWKhM1YBwWppS8Tmpw5"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-titanium-2023",
    "title": "Titanium",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "David Guetta, Sia — 2023, Titanium.",
    "hint": "David Guetta, Sia",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0fN73V9Bj7U8JtmB2ZgFRg"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-whistle-2023",
    "title": "Whistle",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Flo Rida — 2023, Whistle.",
    "hint": "Flo Rida",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5ocfddG4faAWhwV8Fo3vUS"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-grenade-2023",
    "title": "Grenade",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Bruno Mars — 2023, Grenade.",
    "hint": "Bruno Mars",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0ICvakG2UnHeDlykb4cosq"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-want-to-want-me-2023",
    "title": "Want to Want Me",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Jason Derulo — 2023, Want to Want Me.",
    "hint": "Jason Derulo",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2sCsXgl4Egmam4efHRCWwP"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-rather-be-2023",
    "title": "Rather Be",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Clean Bandit, Jess Glynne — 2023, Rather Be.",
    "hint": "Clean Bandit, Jess Glynne",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/7LEXI7W7VUQBXjpxTnQ9re"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-bruci-la-citta-2023",
    "title": "Bruci la città",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Irene Grandi — 2023, Bruci la città.",
    "hint": "Irene Grandi",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2IYQFYlN7oY4a8loz0Iukq"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-i-cry-2023",
    "title": "I Cry",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Flo Rida — 2023, I Cry.",
    "hint": "Flo Rida",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1EExAIJOvmpFhpSVmO3n7p"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-whatcha-say-2023",
    "title": "Whatcha Say",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Jason Derulo — 2023, Whatcha Say.",
    "hint": "Jason Derulo",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2Q1eddqQet2NDCIvL5vzG1"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-memories-2023",
    "title": "Memories",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "David Guetta, Kid Cudi — 2023, Memories.",
    "hint": "David Guetta, Kid Cudi",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2AwnwslG1kz5mWMCC2XcUC"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-just-the-way-you-are-2023",
    "title": "Just the Way You Are",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Bruno Mars — 2023, Just the Way You Are.",
    "hint": "Bruno Mars",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6cAlfKuViKB9kYQU42usVi"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-im-yours-2023",
    "title": "I’m Yours",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Jason Mraz — 2023, I’m Yours.",
    "hint": "Jason Mraz",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5eRx8r6X5ATv4ZWjkJh0p1"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-wake-me-up-when-september-ends-2023",
    "title": "Wake Me Up When September Ends",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Green Day — 2023, Wake Me Up When September Ends.",
    "hint": "Green Day",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/2oAEWwATeqMPv8OSSkAbVH"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-clint-eastwood-2023",
    "title": "Clint Eastwood",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Gorillaz — 2023, Clint Eastwood.",
    "hint": "Gorillaz",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/1SISahQ9QSV1H8v4Kxng5I"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-get-busy-2023",
    "title": "Get Busy",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Sean Paul — 2023, Get Busy.",
    "hint": "Sean Paul",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2MgAKv8pRg5oQ2OjQRJRnC"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-it-girl-2023",
    "title": "It Girl",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Jason Derulo — 2023, It Girl.",
    "hint": "Jason Derulo",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/3tXCD3OSug0TxmP6OxvXeN"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-sexy-bitch-extended-2023",
    "title": "Sexy Bitch - Extended",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "David Guetta, Akon — 2023, Sexy Bitch - Extended.",
    "hint": "David Guetta, Akon",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/44XqHeiTrgraUp5xN0qTaw"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-how-you-remind-me-2023",
    "title": "How You Remind Me",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Nickelback — 2023, How You Remind Me.",
    "hint": "Nickelback",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/6ISrksefcVK74b8EpZF840"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-laffy-taffy-2023",
    "title": "Laffy Taffy",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "D4L — 2023, Laffy Taffy.",
    "hint": "D4L",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/3lb2RGpr5eaRcDx2qMVg4s"
    },
    "genres": [
      "hiphop",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-holiday-boulevard-of-broken-dreams-2023",
    "title": "Holiday / Boulevard of Broken Dreams",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Green Day — 2023, Holiday / Boulevard of Broken Dreams.",
    "hint": "Green Day",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/6tv0G7ut8ZJaFr8TexNoMx"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-dani-california-2023",
    "title": "Dani California",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Red Hot Chili Peppers — 2023, Dani California.",
    "hint": "Red Hot Chili Peppers",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/1gfIFAX1IY5EXyxK29Lyln"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-viva-la-vida-2023",
    "title": "Viva La Vida",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Coldplay — 2023, Viva La Vida.",
    "hint": "Coldplay",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/5EIuYTnDNdvEiBe2bd17jQ"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-sweet-but-psycho-2023",
    "title": "Sweet but Psycho",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Ava Max — 2023, Sweet but Psycho.",
    "hint": "Ava Max",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/53hniUNL15gVxnl7XV1qdV"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-good-feeling-2023",
    "title": "Good Feeling",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Flo Rida — 2023, Good Feeling.",
    "hint": "Flo Rida",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5yS49vhGk1hJEelQtYngEv"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-replay-2023",
    "title": "Replay",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Iyaz — 2023, Replay.",
    "hint": "Iyaz",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/2Py4Oh8CRFuI0oUm6jafL9"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-all-summer-long-2023",
    "title": "All Summer Long",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Kid Rock — 2023, All Summer Long.",
    "hint": "Kid Rock",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6KJFPYolclwccbI4PlbJaF"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-opposite-of-adults-2023",
    "title": "Opposite of Adults",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Chiddy Bang — 2023, Opposite of Adults.",
    "hint": "Chiddy Bang",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/3akO1paFpjYKercqfXeNZ2"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-stereo-hearts-2023",
    "title": "Stereo Hearts",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Gym Class Heroes, Adam Levine — 2023, Stereo Hearts.",
    "hint": "Gym Class Heroes, Adam Levine",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6ALHX6JrjZ10PEO5cGtCmF"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-roll-up-2023",
    "title": "Roll Up",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Wiz Khalifa — 2023, Roll Up.",
    "hint": "Wiz Khalifa",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6ehCzdwYGwUw8OE5TnUCah"
    },
    "genres": [
      "hiphop",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-locked-out-of-heaven-2023",
    "title": "Locked Out of Heaven",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Bruno Mars — 2023, Locked Out of Heaven.",
    "hint": "Bruno Mars",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1Kk56C9SHQzSdyZlLAwqLE"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-what-ive-done-2023",
    "title": "What I've Done",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Linkin Park — 2023, What I've Done.",
    "hint": "Linkin Park",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/59DdDEQ0dmuXsI00OJSk6x"
    },
    "genres": [
      "metal",
      "hiphop",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-cant-stop-2023",
    "title": "Can’t Stop",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Red Hot Chili Peppers — 2023, Can’t Stop.",
    "hint": "Red Hot Chili Peppers",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/6cAvyVIyljhbInVZRfspoJ"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-so-good-2023",
    "title": "So Good",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "B.o.B — 2023, So Good.",
    "hint": "B.o.B",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0RCKFXBZfOgp5CMDI4uJYG"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-a-sky-full-of-stars-2023",
    "title": "A Sky Full of Stars",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Coldplay — 2023, A Sky Full of Stars.",
    "hint": "Coldplay",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/71W4AEIZa7uq4EP9Y2eopk"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-bent-2023",
    "title": "Bent",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Matchbox Twenty — 2023, Bent.",
    "hint": "Matchbox Twenty",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6AOhDP6plSLmvVW3s6XkIi"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-i-wish-2023",
    "title": "I Wish",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Carl Thomas — 2023, I Wish.",
    "hint": "Carl Thomas",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6N6hEO1niVWRD7pqdkfAhx"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-yellow-2023",
    "title": "Yellow",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Coldplay — 2023, Yellow.",
    "hint": "Coldplay",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/4KFqMbI0qY6yzSg6GNTsfe"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-never-let-you-go-2023",
    "title": "Never Let You Go",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Third Eye Blind — 2023, Never Let You Go.",
    "hint": "Third Eye Blind",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/6ZuneWHtW7RnW3IH2S50uz"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-dance-with-me-2023",
    "title": "Dance with Me",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Debelah Morgan — 2023, Dance with Me.",
    "hint": "Debelah Morgan",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4tZ5lS9MnmNmIwWUwXcjlQ"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-breathe-2023",
    "title": "Breathe",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Faith Hill — 2023, Breathe.",
    "hint": "Faith Hill",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/1Hq0a9H77DgC7arX0wxDos"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-otherside-2023",
    "title": "Otherside",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Red Hot Chili Peppers — 2023, Otherside.",
    "hint": "Red Hot Chili Peppers",
    "difficulty": "leicht",
    "sources": {
      "spotify": "https://open.spotify.com/track/0c067hI4TS2rmTukcRVlFY"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-hot-boyz-2023",
    "title": "Hot Boyz",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Missy Elliott — 2023, Hot Boyz.",
    "hint": "Missy Elliott",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/5x5M9qua1FxfciF0pH9EnI"
    },
    "genres": [
      "hiphop",
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-the-way-you-love-me-2023",
    "title": "The Way You Love Me",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Faith Hill — 2023, The Way You Love Me.",
    "hint": "Faith Hill",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/4pcwQGF7bDlrXdjWpoUlYI"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-io-voglio-vivere-2023",
    "title": "Io voglio vivere",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "Nomadi — 2023, Io voglio vivere.",
    "hint": "Nomadi",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/0BpK5LhfZy0bD4pJm1jo0M"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  },
  {
    "id": "song-breathless-2023",
    "title": "Breathless",
    "category": "music",
    "year": 2023,
    "cue": "Song anhören und einordnen.",
    "answer": "The Corrs — 2023, Breathless.",
    "hint": "The Corrs",
    "difficulty": "mittel",
    "sources": {
      "spotify": "https://open.spotify.com/track/62zh7hMYM7m8xc6igXDW76"
    },
    "genres": [
      "poprock"
    ],
    "playlists": [
      "1K766ohE2LA7b7ghtTm7mP"
    ]
  }
];
