#!/usr/bin/env python3
"""Comprehensive distractors for filmSerienCards 001-200"""
import re

distractors = {
    'filmeserien-001-der-pate': ['Robert De Niro.', 'Marlon Brando.', 'Marlon Brando Jr.'],
    'filmeserien-002-der-pate-2': ['Martin Scorsese.', 'Steven Spielberg.', 'Brian De Palma.'],
    'filmeserien-003-goodfellas': ['Steven Spielberg.', 'Francis Ford Coppola.', 'Brian De Palma.'],
    'filmeserien-004-schindlers-liste': ['Ein blauer Mantel.', 'Ein weißer Mantel.', 'Ein schwarzer Mantel.'],
    'filmeserien-005-shawshank': ['Ein Seilseil.', 'Ein Sprengstoff.', 'Ein Gewehr.'],
    'filmeserien-006-fight-club': ['Du kämpfst allein.', 'Jedermann spricht über den Fight Club.', 'Niemand kämpft im Fight Club.'],
    'filmeserien-007-matrix': ['Die blaue Pille.', 'Die grüne Pille.', 'Die schwarze Pille.'],
    'filmeserien-008-lotr': ['Ian McKellen.', 'Viggo Mortensen.', 'Sean Astin.'],
    'filmeserien-009-lotr-gollum': ['Peter Jackson.', 'Martin Freeman.', 'Benedict Cumberbatch.'],
    'filmeserien-010-hp-stein': ['Hans Zimmer.', 'Henry Jackman.', 'James Newton Howard.'],
    'filmeserien-011-hp-dumbledore': ['Ian McKellen und Michael Gambon.', 'Richard Harris und Daniel Radcliffe.', 'Richard Harris und Ian McKellen.'],
    'filmeserien-012-star-wars-iv': ['Alderaan.', 'Mustafar.', 'Coruscant.'],
    'filmeserien-013-star-wars-v': ['Palpatine.', 'Yoda.', 'Obi-Wan Kenobi.'],
    'filmeserien-014-star-wars-vi': ['Jawas.', 'Sandpeople.', 'Tusken Raider.'],
    'filmeserien-015-star-wars-vii': ['Finn.', 'Poe Dameron.', 'Kylo Ren.'],
    'filmeserien-016-rogue-one': ['Ein Lichtschwert.', 'Die Falken.', 'Eine Raumstation.'],
    'filmeserien-017-marvel-ironman': ['Chris Evans.', 'Mark Ruffalo.', 'Chris Hemsworth.'],
    'filmeserien-018-marvel-avengers': ['Ava DuVernay.', 'Kenneth Branagh.', 'Matthew Vaughn.'],
    'filmeserien-019-marvel-endgame': ['"I am Thanos."', '"This is the way."', '"Avengers, assemble!"'],
    'filmeserien-020-marvel-thanos': ['Acht.', 'Sieben.', 'Fünf.'],
    'filmeserien-021-marvel-loki': ['Time Ministry.', 'Temporal Agency.', 'Chronological Bureau.'],
    'filmeserien-022-barbie': ['Margot Robbie.', 'Ryan Gosling.', 'Will Ferrell.'],
    'filmeserien-023-oppenheimer': ['Cillian Murphy.', 'Robert Downey Jr.', 'Christopher Nolan.'],
    'filmeserien-024-dune-1': ['Timothée Chalamet.', 'Oscar Isaac.', 'Zendaya.'],
    'filmeserien-025-dune-2': ['David Lynch.', 'Denis Villeneuve.', 'George Lucas.'],
    'filmeserien-026-inception': ['Leonardo DiCaprio.', 'Ellen Page.', 'Marion Cotillard.'],
    'filmeserien-027-interstellar': ['Matthew McConaughey.', 'Anne Hathaway.', 'Jessica Chastain.'],
    'filmeserien-028-tenet': ['John David Washington.', 'Robert Pattinson.', 'Elizabeth Debicki.'],
    'filmeserien-029-the-prestige': ['Christian Bale.', 'Hugh Jackman.', 'Michael Caine.'],
    'filmeserien-030-memento': ['Guy Pearce.', 'Carrie-Anne Moss.', 'Joe Pantoliano.'],
    'filmeserien-031-se7en': ['Brad Pitt.', 'Morgan Freeman.', 'Gwyneth Paltrow.'],
    'filmeserien-032-silence-of-lambs': ['Jodie Foster.', 'Scott Glenn.', 'Paul Reiser.'],
    'filmeserien-033-darthvader': ['George Lucas.', 'Richard Marquardt.', 'David Prowse.'],
    'filmeserien-034-jedi-luke': ['Yoda.', 'Leia.', 'Han Solo.'],
    'filmeserien-035-alien': ['Sigourney Weaver.', 'Michael Biehn.', 'Lance Henriksen.'],
    'filmeserien-036-terminator': ['Arnold Schwarzenegger.', 'Linda Hamilton.', 'Michael Biehn.'],
    'filmeserien-037-back-to-future': ['Michael J. Fox.', 'Christopher Lloyd.', 'Lea Thompson.'],
    'filmeserien-038-ghostbusters': ['Bill Murray.', 'Dan Aykroyd.', 'Harold Ramis.'],
    'filmeserien-039-jaws': ['Roy Scheider.', 'Richard Dreyfuss.', 'Robert Shaw.'],
    'filmeserien-040-jurassic-park': ['Sam Neill.', 'Laura Dern.', 'Jeff Goldblum.'],
    'filmeserien-041-titanic': ['Leonardo DiCaprio.', 'Kate Winslet.', 'Billy Zane.'],
    'filmeserien-042-avatar': ['Sam Worthington.', 'Zoe Saldana.', 'Sigourney Weaver.'],
    'filmeserien-043-forest-gump': ['Tom Hanks.', 'Gary Sinise.', 'Sally Field.'],
    'filmeserien-044-pulp-fiction': ['John Travolta.', 'Samuel L. Jackson.', 'Uma Thurman.'],
    'filmeserien-045-reservoir-dogs': ['Tim Roth.', 'Steve Buscemi.', 'Harvey Keitel.'],
    'filmeserien-046-kill-bill': ['Uma Thurman.', 'David Carradine.', 'Lucy Liu.'],
    'filmeserien-047-inglourious': ['Brad Pitt.', 'Christoph Waltz.', 'Michael Fassbender.'],
    'filmeserien-048-django': ['Leonardo DiCaprio.', 'Christoph Waltz.', 'Kerry Washington.'],
    'filmeserien-049-hateful-eight': ['Kurt Russell.', 'Jennifer Jason Leigh.', 'Samuel L. Jackson.'],
    'filmeserien-050-dark-knight': ['Christian Bale.', 'Heath Ledger.', 'Aaron Eckhart.'],
    'filmeserien-051-dark-knight-rises': ['Anne Hathaway.', 'Tom Hardy.', 'Joseph Gordon-Levitt.'],
    'filmeserien-052-batman-begins': ['Michael Caine.', 'Liam Neeson.', 'Katie Holmes.'],
    'filmeserien-053-man-of-steel': ['Henry Cavill.', 'Amy Adams.', 'Michael Shannon.'],
    'filmeserien-054-wonder-woman': ['Gal Gadot.', 'Chris Pine.', 'Danny Huston.'],
    'filmeserien-055-aquaman': ['Jason Momoa.', 'Amber Heard.', 'Patrick Wilson.'],
    'filmeserien-056-flash': ['Ezra Miller.', 'Gal Gadot.', 'Ben Affleck.'],
    'filmeserien-057-shazam': ['Zachary Levi.', 'Jack Dylan Grazer.', 'Mark Strong.'],
    'filmeserien-058-black-panther': ['Chadwick Boseman.', 'Lupita Nyongo.', 'Michael B. Jordan.'],
    'filmeserien-059-captain-america': ['Chris Evans.', 'Sebastian Stan.', 'Scarlett Johansson.'],
    'filmeserien-060-thor': ['Chris Hemsworth.', 'Tom Hiddleston.', 'Natalie Portman.'],
    'filmeserien-061-ant-man': ['Paul Rudd.', 'Evangeline Lilly.', 'Michael Douglas.'],
    'filmeserien-062-doc-strange': ['Benedict Cumberbatch.', 'Rachel McAdams.', 'Chiwetel Ejiofor.'],
    'filmeserien-063-guardians': ['Chris Pratt.', 'Denzel Washington.', 'Zoe Saldana.'],
    'filmeserien-064-black-widow': ['Scarlett Johansson.', 'David Harbour.', 'Florence Pugh.'],
    'filmeserien-065-eternals': ['Gemma Chan.', 'Richard Madden.', 'Salma Hayek.'],
    'filmeserien-066-spider-man': ['Tobey Maguire.', 'Andrew Garfield.', 'Tom Holland.'],
    'filmeserien-067-spider-man-far': ['Jake Gyllenhaal.', 'Michael Keaton.', 'Robert Downey Jr.'],
    'filmeserien-068-spider-man-nwh': ['Zendaya.', 'Marisa Tomei.', 'Jon Favreau.'],
    'filmeserien-069-x-men-first': ['James McAvoy.', 'Michael Fassbender.', 'Jennifer Lawrence.'],
    'filmeserien-070-x-men-dark': ['Ian McKellen.', 'Patrick Stewart.', 'Halle Berry.'],
    'filmeserien-071-fantastic-four': ['Miles Teller.', 'Kate Mara.', 'Michael B. Jordan.'],
    'filmeserien-072-deadpool': ['Ryan Reynolds.', 'Morena Baccarin.', 'Ed Skrein.'],
    'filmeserien-073-blade': ['Wesley Snipes.', 'Stephen Dorff.', 'Kris Kristofferson.'],
    'filmeserien-074-hellboy': ['Ron Perlman.', 'John Hurt.', 'Selma Blair.'],
    'filmeserien-075-constantine': ['Keanu Reeves.', 'Rachel Weisz.', 'Shia LaBeouf.'],
    'filmeserien-076-v-vendetta': ['Natalie Portman.', 'Hugo Weaving.', 'Stephen Rea.'],
    'filmeserien-077-watchmen': ['Malin Åkerman.', 'Billy Crudup.', 'Matthew Goode.'],
    'filmeserien-078-300': ['Gerard Butler.', 'Lena Headey.', 'Dominic West.'],
    'filmeserien-079-sin-city': ['Bruce Willis.', 'Jessica Alba.', 'Devon Aoki.'],
    'filmeserien-080-blade-runner': ['Harrison Ford.', 'Rutger Hauer.', 'Sean Young.'],
    'filmeserien-081-2001': ['Keir Dullea.', 'Gary Lockwood.', 'Mag 9000.'],
    'filmeserien-082-metropolis': ['Brigitte Helm.', 'Alfred Abel.', 'Gustav Fröhlich.'],
    'filmeserien-083-fifth-element': ['Bruce Willis.', 'Milla Jovovich.', 'Gary Oldman.'],
    'filmeserien-084-minority-report': ['Tom Cruise.', 'Colin Farrell.', 'Samantha Morton.'],
    'filmeserien-085-total-recall': ['Arnold Schwarzenegger.', 'Rachel Ticotin.', 'Sharon Stone.'],
    'filmeserien-086-running-man': ['Jesse Ventura.', 'Maria Conchita Alonso.', 'Dweyne The Rock Johnson.'],
    'filmeserien-087-predator': ['Carl Weathers.', 'Elpidia Carrillo.', 'Jesse Ventura.'],
    'filmeserien-088-commando': ['Rae Dawn Chong.', 'Dan Hedaya.', 'Vernon Wells.'],
    'filmeserien-089-total-recall-2': ['Len Wiseman.', 'Colin Farrell.', 'Kate Beckinsale.'],
    'filmeserien-090-robocop': ['Nancy Allen.', 'Kurtwood Smith.', 'Miguel Ferrer.'],
    'filmeserien-091-robocop-2': ['Tom Noonan.', 'Belinda Bauer.', 'Dan O\'Herlihy.'],
    'filmeserien-092-starship-troopers': ['Casper Van Dien.', 'Dina Meyer.', 'Denise Richards.'],
    'filmeserien-093-enterprise-d': ['Brent Spiner.', 'Patrick Stewart.', 'LeVar Burton.'],
    'filmeserien-094-trek-discovery': ['Sonequa Martin-Green.', 'Doug Jones.', 'Anthony Rapp.'],
    'filmeserien-095-trek-picard': ['Patrick Stewart.', 'Alison Pill.', 'Michelle Hurd.'],
    'filmeserien-096-trek-strange': ['Anson Mount.', 'Ethan Peck.', 'Christina Chong.'],
    'filmeserien-097-babylon5': ['Bruce Boxleitner.', 'Claudia Christian.', 'J. Michael Straczynski.'],
    'filmeserien-098-farscape': ['Ben Browder.', 'Claudia Black.', 'Gigi Edgley.'],
    'filmeserien-099-firefly': ['Nathan Fillion.', 'Gina Torres.', 'Alan Tudyk.'],
    'filmeserien-100-serenity': ['Summer Glau.', 'Morena Baccarin.', 'Chiwetel Ejiofor.'],
    'filmeserien-101-game-thrones': ['Emilia Clarke.', 'Lena Headey.', 'Sophie Turner.'],
    'filmeserien-102-breaking-bad': ['Bryan Cranston.', 'Aaron Paul.', 'Dean Norris.'],
    'filmeserien-103-true-detective': ['Matthew McConaughey.', 'Woody Harrelson.', 'Colin Farrell.'],
    'filmeserien-104-house-cards': ['Kevin Spacey.', 'Robin Wright.', 'Michael Kelly.'],
    'filmeserien-105-stranger-things': ['Winona Ryder.', 'David Harbour.', 'Millie Bobby Brown.'],
    'filmeserien-106-westworld': ['Anthony Hopkins.', 'Evan Rachel Wood.', 'Ed Harris.'],
    'filmeserien-107-black-mirror': ['Daniel Kaluuya.', 'Bryce Dallas Howard.', 'San Junipero.'],
    'filmeserien-108-handmaids-tale': ['Elisabeth Moss.', 'Yvonne Strahovski.', 'Joseph Fiennes.'],
    'filmeserien-109-crown': ['Claire Foy.', 'Olivia Colman.', 'Gillian Anderson.'],
    'filmeserien-110-madmen': ['Jon Hamm.', 'Elisabeth Moss.', 'Vincent Kartheiser.'],
    'filmeserien-111-sopranos': ['James Gandolfini.', 'Lorraine Bracco.', 'Steven Van Zandt.'],
    'filmeserien-112-wire': ['Idris Elba.', 'Dominic West.', 'Michael K. Williams.'],
    'filmeserien-113-veep': ['Julia Louis-Dreyfus.', 'Tony Hale.', 'Anna Chlumsky.'],
    'filmeserien-114-ozark': ['Jason Bateman.', 'Laura Linney.', 'Julia Garner.'],
    'filmeserien-115-peaky-blinders': ['Cillian Murphy.', 'Paul Anderson.', 'Helen McCrory.'],
    'filmeserien-116-sherlock': ['Benedict Cumberbatch.', 'Martin Freeman.', 'Mark Gatiss.'],
    'filmeserien-117-mindhunter': ['Rami Malek.', 'Holt McCallany.', 'Wendy Carr.'],
    'filmeserien-118-ozark-crime': ['Billy Bob Thornton.', 'Ryan Reynolds.', 'Jon Bernthal.'],
    'filmeserien-119-narcos': ['Wagner Moura.', 'Pedro Pascal.', 'Boyd Holbrook.'],
    'filmeserien-120-vikings': ['Travis Fimmel.', 'Katheryn Winnick.', 'Ragnar Lothbrok.'],
    'filmeserien-121-witcher': ['Henry Cavill.', 'Anya Chalotra.', 'Freya Allan.'],
    'filmeserien-122-mandalorian': ['Pedro Pascal.', 'Gina Carano.', 'Carl Weathers.'],
    'filmeserien-123-book-boba': ['Temuera Morrison.', 'Ming-Na Wen.', 'Jennifer Beals.'],
    'filmeserien-124-ahsoka': ['Rosario Dawson.', 'Natasha Liu Bordizzo.', 'Ariel Shaffer.'],
    'filmeserien-125-andor': ['Diego Luna.', 'Stellan Skarsgard.', 'Andy Serkis.'],
    'filmeserien-126-obi-wan': ['Hayden Christensen.', 'Joel Edgerton.', 'Bonnie Piesse.'],
    'filmeserien-127-acolyte': ['Lee Jung-jae.', 'Manny Jacinto.', 'Jude Law.'],
    'filmeserien-128-last-jedi': ['Daisy Ridley.', 'Mark Hamill.', 'Adam Driver.'],
    'filmeserien-129-rise-skywalker': ['Oscar Isaac.', 'John Boyega.', 'Kelly Marie Tran.'],
    'filmeserien-130-rings-fellowship': ['Sir Ian McKellen.', 'Cate Blanchett.', 'Billy Boyd.'],
    'filmeserien-131-rings-towers': ['John Rhys-Davies.', 'Orlando Bloom.', 'Viggo Mortensen.'],
    'filmeserien-132-rings-return': ['Treebeard.', 'Shelob.', 'Glorfindel.'],
    'filmeserien-133-the-hobbit-1': ['Peter Jackson.', 'Martin Freeman.', 'Ian McKellen.'],
    'filmeserien-134-hobbit-2': ['The Necromancer.', 'Smaug.', 'Gandalf.'],
    'filmeserien-135-hobbit-3': ['Luke Evans.', 'Aidan Turner.', 'Richard Armitage.'],
    'filmeserien-136-percy-jackson': ['Logan Lerman.', 'Brandon T. Jackson.', 'Alexandra Daddario.'],
    'filmeserien-137-hunger-games': ['Jennifer Lawrence.', 'Josh Hutcherson.', 'Liam Hemsworth.'],
    'filmeserien-138-hunger-2': ['Woody Harrelson.', 'Jena Malone.', 'Philip Seymour Hoffman.'],
    'filmeserien-139-hunger-3': ['Donald Sutherland.', 'Julianne Moore.', 'Natalie Dormer.'],
    'filmeserien-140-hunger-4': ['Jeffrey Wright.', 'Willow Shields.', 'Mahershala Ali.'],
    'filmeserien-141-maze-runner': ['Dylan O\'Brien.', 'Kaya Scodelario.', 'Thomas Brodie-Sangster.'],
    'filmeserien-142-maze-2': ['Giancarlo Esposito.', 'Aiden Gillen.', 'Pattie Boyd.'],
    'filmeserien-143-maze-3': ['Rosa Salazar.', 'Rodrigo Santoro.', 'Lee Pace.'],
    'filmeserien-144-divergent': ['Shailene Woodley.', 'Theo James.', 'Miles Teller.'],
    'filmeserien-145-divergent-2': ['Naomi Watts.', 'Kate Winslet.', 'Jai Courtney.'],
    'filmeserien-146-divergent-3': ['Ansel Elgort.', 'Maggie Q.', 'Jeff Daniels.'],
    'filmeserien-147-the-5th-wave': ['Chloë Grace Moretz.', 'Nick Robinson.', 'Ron Livingston.'],
    'filmeserien-148-the-5th-2': ['Maika Monroe.', 'Liev Schreiber.', 'Maria Bello.'],
    'filmeserien-149-mortal-engines': ['Hera Hilmar.', 'Robert Sheehan.', 'Hugo Weaving.'],
    'filmeserien-150-tomb-raider': ['Alicia Vikander.', 'Daniel Wu.', 'Walton Goggins.'],
    'filmeserien-151-assassins-creed': ['Michael Fassbender.', 'Marion Cotillard.', 'Jeremy Irons.'],
    'filmeserien-152-resident-evil': ['Milla Jovovich.', 'Colin Salmon.', 'Ryan McCluskey.'],
    'filmeserien-153-resident-evil-2': ['Iain Glen.', 'Ali Larter.', 'Colin Salmon.'],
    'filmeserien-154-resident-evil-3': ['Oded Fehr.', 'Ali Larter.', 'Mike Epps.'],
    'filmeserien-155-hitman': ['Timothy Olyphant.', 'Olga Kurylenko.', 'Robert Knepper.'],
    'filmeserien-156-hitman-agent': ['Henry Cavill.', 'Elodie Yung.', 'Sam Rockwell.'],
    'filmeserien-157-sonic': ['Ben Schwartz.', 'James Marsden.', 'Lee Majdoub.'],
    'filmeserien-158-sonic-2': ['Keanu Reeves.', 'Idris Elba.', 'Tika Sumpter.'],
    'filmeserien-159-sonic-3': ['Mark Wahlberg.', 'Alyla Browne.', 'Balthazar Getty.'],
    'filmeserien-160-pokemon': ['Ryan Reynolds.', 'Justice Smith.', 'Kathryn Newton.'],
    'filmeserien-161-detective-pikachu': ['Suki Waterhouse.', 'Hiroyuki Sanada.', 'Litwick.'],
    'filmeserien-162-mario-brothers': ['Chris Pratt.', 'Anya Taylor-Joy.', 'Charlie Day.'],
    'filmeserien-163-uncharted': ['Tom Holland.', 'Mark Wahlberg.', 'Antonio Banderas.'],
    'filmeserien-164-jungle-cruise': ['Dwayne Johnson.', 'Emily Blunt.', 'Jack Whitehall.'],
    'filmeserien-165-kraken': ['Jason Statham.', 'Li Bingbing.', 'Robert Taylor.'],
    'filmeserien-166-rampage': ['Dwayne Johnson.', 'Naomie Harris.', 'Malin Åkerman.'],
    'filmeserien-167-jungle-book': ['Neel Sethi.', 'Bill Murray.', 'Scarlett Johansson.'],
    'filmeserien-168-lion-king': ['Donald Glover.', 'Beyoncé.', 'Chiwetel Ejiofor.'],
    'filmeserien-169-aladdin': ['Will Smith.', 'Mena Massoud.', 'Naomi Scott.'],
    'filmeserien-170-mulan': ['Liu Yifei.', 'Donnie Yen.', 'Jet Li.'],
    'filmeserien-171-cinderella': ['Lily James.', 'Cate Blanchett.', 'Richard Madden.'],
    'filmeserien-172-beauty-beast': ['Emma Watson.', 'Dan Stevens.', 'Luke Evans.'],
    'filmeserien-173-sleeping-beauty': ['Elle Fanning.', 'Angelina Jolie.', 'Sharlto Copley.'],
    'filmeserien-174-prince-charming': ['Lily Collins.', 'Julia Roberts.', 'Armie Hammer.'],
    'filmeserien-175-encanto': ['Stephanie Beatriz.', 'John Leguizamo.', 'Wilmer Valderrama.'],
    'filmeserien-176-coco': ['Anthony Gonzalez.', 'Gael García Bernal.', 'Benjamin Bratt.'],
    'filmeserien-177-moana': ['Auli\'i Cravalho.', 'Dwayne Johnson.', 'Rachel House.'],
    'filmeserien-178-frozen': ['Idina Menzel.', 'Kristen Bell.', 'Jonathan Groff.'],
    'filmeserien-179-frozen-2': ['Evan Rachel Wood.', 'Sterling K. Brown.', 'Alfreda James.'],
    'filmeserien-180-tangled': ['Mandy Moore.', 'Zachary Levi.', 'Donna Murphy.'],
    'filmeserien-181-rapunzel': ['Billy Magnussen.', 'Ryan Gosling.', 'Kristen Chenoweth.'],
    'filmeserien-182-brave': ['Kelly Macdonald.', 'Billy Connolly.', 'Emma Thompson.'],
    'filmeserien-183-merida': ['Brenda Chapman.', 'Mark Andrews.', 'Steve Purcell.'],
    'filmeserien-184-toy-story': ['Tom Hanks.', 'Tim Allen.', 'John Ratzenberger.'],
    'filmeserien-185-toy-story-2': ['Wallace Shawn.', 'Don Rickles.', 'Bonnie Hunt.'],
    'filmeserien-186-toy-story-3': ['Michael Keaton.', 'Ned Beatty.', 'John Ratzenberger.'],
    'filmeserien-187-toy-story-4': ['Tony Hale.', 'Tom Hanks.', 'Christina Hendricks.'],
    'filmeserien-188-cars': ['Owen Wilson.', 'Paul Newman.', 'Bonnie Hunt.'],
    'filmeserien-189-cars-2': ['John Turturro.', 'Michael Caine.', 'Emily Mortimer.'],
    'filmeserien-190-cars-3': ['Larry the Cable Guy.', 'Armie Hammer.', 'Cristela Alonzo.'],
    'filmeserien-191-ratatouille': ['Lou Romano.', 'Ian Holm.', 'Paul Lieberstein.'],
    'filmeserien-192-wall-e': ['Eve.', 'Auto.', 'B.N.L.'],
    'filmeserien-193-up': ['Edward Asner.', 'Christopher Plummer.', 'Bob Peterson.'],
    'filmeserien-194-inside-out': ['Amy Poehler.', 'Phyllis Smith.', 'Richard Kind.'],
    'filmeserien-195-finding-nemo': ['Bruce.', 'Dory.', 'Crush.'],
    'filmeserien-196-finding-dory': ['Hank.', 'Bailey.', 'Destiny.'],
    'filmeserien-197-monsters-inc': ['Mike.', 'Celia.', 'Yeti.'],
    'filmeserien-198-monsters-university': ['Dean Hardscrabble.', 'Celia.', 'Fungus.'],
    'filmeserien-199-bugs-life': ['A Bug\'s Life.', 'Antz.', 'DreamWorks.'],
    'filmeserien-200-incredibles': ['Syndrome.', 'Mirage.', 'Omnidroid.'],
}

filepath = 'lib/filmSerienCards.ts'

with open(filepath, 'r', encoding='utf-8') as f:
    content = f.read()

count = 0
for card_id, dists in distractors.items():
    dists_json = ', '.join([f"'{d}'" for d in dists])
    pattern = f"(id: '{card_id}'[^}}]*?)sources: {{}}"
    replacement = f"\\1sources: {{}}, distractors: [{dists_json}]"
    
    if re.search(pattern, content, flags=re.DOTALL):
        content = re.sub(pattern, replacement, content, flags=re.DOTALL, count=1)
        count += 1

with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"✓ Added distractors to {count}/200 filmSerienCards")
